### ISSUE TITLE
VMStat missing

### ISSUE THREAD

**Issue by FrenchBen** [play-with-docker/play-with-docker#119]
Could we have VMStat installed by default?
```
$ apk add --update procps
```

**Comment by marcosnils** [comment]
hmm we try to keep the images as small as possible. Even though vmstat is slim, I still don't see the need to add it for all the sessions.

**Comment by FrenchBen** [comment]
Only reason is the workshop by jpetazzo recommends PWD and uses VMStat:
https://jpetazzo.github.io/orchestration-workshop

**Comment by marcosnils** [comment]
@FrenchBen the thing is that I'm not sure if vmstat actually makes sense in PWD because `/proc` is not containerized. So you'll be looking at the host metrics instead of the container, which in this case is a large machine shared by many people. 

@jpetazzo ?

**Comment by FrenchBen** [comment]
@marcosnils we can leave it out for now then - I'll defer to @jpetazzo if we need it

**Comment by marcosnils** [comment]
Got it. Let me know if there's something else we can do.
