### ISSUE TITLE
Add ENV variable in instance

### ISSUE THREAD

**Issue by jmaitrehenry** [play-with-docker/play-with-docker#124]
Hi, I try to create some script for running UCP and DTR inside PWD.
For having the less manual step, I would like to have some ENV available inside my instance for building url like this one: `https://pwd10_0_32_3-443.host3.labs.play-with-docker.com`:

```
[node2] (local) root@10.0.32.4 ~
$ printenv
INSTANCE_IP=10.0.32.4
INSTANCE_HOST=host3
INSTANCE_URL=labs.play-with-docker.com OR pwd10_0_32_3-PORT.host3.labs.play-with-docker.com
```

My script for now: https://gist.github.com/jmaitrehenry/131d541b5a7ca437ea08776d20ceb60d

Thanks

**Comment by xetorthio** [comment]
That sounds pretty good! The IP address can be retrieved from the network interface right?
If that is the case, then the only env variable needed would be:
`INSTANCE_URL=pwd10_0_32_3-PORT.host3.labs.play-with-docker.com`
Pretty much everything can be extracted from there, right?

Would that be enough for your needs?

**Comment by jmaitrehenry** [comment]
If I have an `INSTANCE_URL` env variable, it will be perfect for my use case.
And, yes, other information could be extracted from this one.

Thanks!

**Comment by xetorthio** [comment]
Perfect! I will try to add this ASAP
