### ISSUE TITLE
Can you create a new terminal session of the same instance?

### ISSUE THREAD

**Issue by radu-matei** [play-with-docker/play-with-docker#126]
Just as the title suggests, how would one create a new terminal session in the same instance?

Thanks,
Radu M

**Comment by xetorthio** [comment]
Right now it is not possible. But we are planning on adding it.

**Comment by Cinderhaze** [comment]
Is it possible to get screen/tmux in the session as a stopgap?

**Comment by marcosnils** [comment]
@Cinderhaze yes. tmux is installed and works.

**Comment by radu-matei** [comment]
@Cinderhaze Thanks a lot for the `tmux` hint!
