### ISSUE TITLE
Remove underscores from exposed port URLs

### ISSUE THREAD

**Issue by mikesir87** [play-with-docker/play-with-docker#128]
Example URL: `http://pwd10_0_10_3-2376.host1.labs.play-with-docker.com/`

Unfortunately, underscores are not valid characters in hostnames.  Since PWD is using a wildcard DNS entry, the DNS resolution is still occurring.  However, if you try to use the hostname somewhere else that validates that a hostname contains `[A-Za-z0-9\-\.]+`, the verification will fail.

http://stackoverflow.com/questions/3523028/valid-characters-of-a-hostname

**Example of where this matters**: created a Swarm cluster on PWD and tried to enroll it into Docker Cloud to demo Desktop2Cloud.  Since it can't autodetect the endpoint, I tried to specify the endpoint by using the exposed port URL.  But, the hostname isn't valid, so wouldn't accept the custom endpoint.

### Proposal

Swap underscores for dashes: `pwd10-0-10-3-2376.host1.labs.play-with-docker.com`

Pros:
- Now compliant hostname
- Still very readable
- Keeps everything still one level below host1.labs.play-with-docker.com, reducing the number of subdomain wildcards needed for DNS/SSL certs

Work required:
- Splitting the first segment now becomes: last segment is port, replace rest with `.` for IP address

I'd be happy to contribute to fix this, but couldn't find where the URL is generated and the proxy rules are created/applied.

Thoughts?

**Comment by xetorthio** [comment]
Hi!
Yes! This is very important. The change should be simple too. Thanks for
reporting.

**Comment by mikesir87** [comment]
Thanks @xetorthio. I went ahead and took a stab at it with a PR, which made it all work locally.

**Comment by marcosnils** [comment]
hey @mikesir87 just had time to check this. If this works it's really awesome. I'm wondering if you had the opportunity to make this chance locally in your computer and testing that desktop2cloud actually works without the underscores. I'm just wondering if this is the only change needed or if we might have to change something else.

**Comment by mikesir87** [comment]
@marcosnils - I couldn't test Desktop2Cloud on my machine (my machine wasn't globally accessible) but did deploy on AWS. The routing all worked as expected, but ran into an issue still getting Desktop2Cloud working. Didn't have time to look into it at that point, as I had a meetup right then, and haven't had a chance to loop back around. So, there might still be something else needed to get it working. I'll be happy to loop back around with it, as I should have a little extra time over the next few days.

**Comment by marcosnils** [comment]
@mikesir87 just tried a very basic example and I could join a swarm created in PWD to docker cloud. Now, when trying to launch a terminal to manage my swarm, I got a TLS error. How did you realize that the underscore thing was the problem?

**Comment by mikesir87** [comment]
@marcosnils - when I tried to join a Swarm earlier, it would "join", but the dashboard would say it had trouble talking to the swarm.  I think it's because it tried to autodetect the Swarm endpoint, which it couldn't quite do since it's being proxied and what-not. 

So, I tried providing my own endpoint for the Swarm (in the Docker Cloud interface). But, providing the URL with underscores wouldn't persist. The error displayed on the screen didn't provide a lot of hints, but looking at the actual HTTP response, I saw that the new URL was invalid. Then, it hit me that the URL has underscores in it, which aren't valid characters in hostnames.  So, I quickly tried swapping the underscores with dashes and the save request went through.  That then led me to make the PR.  Like you, I still got the TLS error, but at least the custom endpoint persisted (which is what I alluded to earlier by still having an error when trying to use the swarm on my machine).

**Comment by marcosnils** [comment]
Got it. Even if Desktop2Cloud doesn't work I think this PR is still valid as having a compliance hostname might help in other situations. One thing we need to make sure before merging this PR is that the sdk.js of the training site and that the machine driver will continue working.

**Comment by mikesir87** [comment]
Good point.  Hadn't thought of the other locations.  Another idea... I wonder if we could add a URL mask as part of the instance metadata (from the REST API) that allows the client to build out the URL?  That way, there's only one place that really knows/cares about the structure of the full URL.  Maybe something like this...

```json
{
  // other metadata
  "proxyUrlMask" : "pwd10-0-27-3-{{PORT}}.host1.labs.play-with-docker.com"
}
```

Then, each client only needs to swap out the `{{PORT}}` value and not need to know about the rest of the structure. Then, if we ever need to change the URLs in the future, we only need to change it on the backend.  Thoughts?

We could even make this change before merging this PR? Merging this could then be a true test of each of the clients.

**Comment by marcosnils** [comment]
That's a good idea. There's one detail though. The machine driver **needs** the session to be created beforehand, so it's not possible to use the proxyUrlMask to decode the url to configure itself 😢

**Comment by mikesir87** [comment]
Ok. I haven't looked at how the driver is implemented yet, but I can take a look. Since it would immediately benefit the JavaScript-based clients, I can go ahead and work up a PR for that real quick. Maybe we can leave the driver as-is for the moment and think of a way to update the driver as round two.

**Comment by marcosnils** [comment]
done!. Thx @mikesir87 for reporting and the patience.

**Comment by rcjsuen** [comment]
Should the FAQ at the bottom of [README.md](https://github.com/play-with-docker/play-with-docker/blob/b82e8308bd94cbfa81e6d1b2c2aa9d3bfb2b08ac/README.md) be updated to reflect this change?
