### ISSUE TITLE
Select keyboard layout automatically based on User-Agent

### ISSUE THREAD

**Issue by marcosnils** [play-with-docker/play-with-docker#131]
This shouldn't be difficult to do, basically select Mac or None as default

@mikesir87 , any spare time to give us a hand with this  :roll_eyes: ???

**Comment by mikesir87** [comment]
I thought it was already doing this, at least for the Mac. Are you seeing something else?

**Comment by marcosnils** [comment]
Hmmm seems like it does for mac. But sometimes I get this
![image](https://cloud.githubusercontent.com/assets/1578458/25727749/5bd9bcf2-3101-11e7-8551-9d24afa7ffae.png)


and I need to manually select None from the combo box as no layout is selected by default.

**Comment by mikesir87** [comment]
Ah. Gotcha. That'll be an easy fix. Will get to it in a little bit.
