### ISSUE TITLE
I guess I broke the play with docker

### ISSUE THREAD

**Issue by rosineygp** [play-with-docker/play-with-docker#145]
1 . Create new session
2 . Close the session
3 . Reload page

Page stop to working after it.

Page return :(

PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 748281245 [running]:
github.com/urfave/negroni.(*Recovery).ServeHTTP.func1(0x7f58a36bc658, 0xc4d2b5b128, 0xc42054a600)
	/go/src/github.com/urfave/negroni/recovery.go:41 +0x150
panic(0x92fd60, 0xc420012040)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/play-with-docker/play-with-docker/handlers.Home(0x7f58a36bc658, 0xc4d2b5b128, 0xc449aedb30)
	/go/src/github.com/play-with-docker/play-with-docker/handlers/home.go:15 +0x7d
net/http.HandlerFunc.ServeHTTP(0xa1ae80, 0x7f58a36bc658, 0xc4d2b5b128, 0xc449aedb30)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42038d810, 0x7f58a36bc658, 0xc4d2b5b128, 0xc449aedb30)
	/go/src/github.com/gorilla/mux/mux.go:114 +0x10d
github.com/urfave/negroni.Wrap.func1(0x7f58a36bc658, 0xc4d2b5b128, 0xc4a6942000, 0xc420a26700)
	/go/src/github.com/urfave/negroni/negroni.go:46 +0x4d
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc420334d00, 0x7f58a36bc658, 0xc4d2b5b128, 0xc4a6942000, 0xc420a26700)
	/go/src/github.com/urfave/negroni/negroni.go:29 +0x4e
github.com/urfave/negroni.middleware.ServeHTTP(0xc3b9a0, 0xc420334d00, 0xc420334d80, 0x7f58a36bc658, 0xc4d2b5b128, 0xc4a6942000)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0xa7
github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7f58a36bc658, 0xc4d2b5b128, 0xc4a6942000)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0x60
github.com/urfave/negroni.(*Static).ServeHTTP(0xc42054ae10, 0x7f58a36bc658, 0xc4d2b5b128, 0xc4a6942000, 0xc420a266c0)
	/go/src/github.com/urfave/negroni/static.go:53 +0x72f
github.com/urfave/negroni.middleware.ServeHTTP(0xc399e0, 0xc42054ae10, 0xc420334d60, 0x7f58a36bc658, 0xc4d2b5b128, 0xc4a6942000)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0xa7
github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7f58a36bc658, 0xc4d2b5b128, 0xc4a6942000)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0x60
github.com/urfave/negroni.(*Logger).ServeHTTP(0xc42054a660, 0x7f58a36bc658, 0xc4d2b5b128, 0xc4a6942000, 0xc420a26660)
	/go/src/github.com/urfave/negroni/logger.go:65 +0x86
github.com/urfave/negroni.middleware.ServeHTTP(0xc39920, 0xc42054a660, 0xc420334d40, 0x7f58a36bc658, 0xc4d2b5b128, 0xc4a6942000)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0xa7
github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7f58a36bc658, 0xc4d2b5b128, 0xc4a6942000)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0x60
github.com/urfave/negroni.(*Recovery).ServeHTTP(0xc42054a600, 0x7f58a36bc658, 0xc4d2b5b128, 0xc4a6942000, 0xc420a26640)
	/go/src/github.com/urfave/negroni/recovery.go:64 +0x82
github.com/urfave/negroni.middleware.ServeHTTP(0xc399a0, 0xc42054a600, 0xc420334d20, 0x7f58a36bc658, 0xc4d2b5b128, 0xc4a6942000)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0xa7
github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc42054ae70, 0xc3fb60, 0xc43056b930, 0xc4a6942000)
	/go/src/github.com/urfave/negroni/negroni.go:86 +0x112
net/http.serverHandler.ServeHTTP(0xc4203fc200, 0xc3fb60, 0xc43056b930, 0xc4a6942000)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc48d1d9280, 0xc40620, 0xc436e45200)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d

**Comment by xetorthio** [comment]
Thanks for reporting! I will fix it asap

**Comment by xetorthio** [comment]
Fix is on the way :)
