### ISSUE TITLE
Can't launch PWD on my infrastructure

### ISSUE THREAD

**Issue by anmonteiro** [play-with-docker/play-with-docker#148]
I'm following the wiki page (https://github.com/play-with-docker/play-with-docker/wiki/Deploying-PWD-in-your-own-infrastructure) and having a little trouble launching the executable per the command:
```
docker run -d \
        -e DIND_IMAGE=franela/dind:overlay2 \
        -e GOOGLE_RECAPTCHA_DISABLED=true \
        -e MAX_PROCESSES=10000 \
        -e EXPIRY=4h \
        --name pwd \
        -p 80:3000 \
        -p 443:3001 \
        -p 53:53/udp \
        -p 53:53/tcp \
        -v /var/run/docker.sock:/var/run/docker.sock -v sessions:/app/pwd/ \
        --restart always \
        franela/play-with-docker:latest --cname host1 --save ./pwd/sessions
```

It doesn't accept the arguments, failing with: 
```
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"--cname\": executable file not found in $PATH".
```

**Comment by marcosnils** [comment]
Just updated the README, try now.

**Comment by anmonteiro** [comment]
That works great, thanks. 

I'm now having a problem with redirection. Do I need to set up `host1` anywhere else or is it misconfiguration on my part?

**Comment by anmonteiro** [comment]
It's working now that I added a CNAME record for `host1`
