### ISSUE TITLE
Swarm templates not available

### ISSUE THREAD

**Issue by gilleslabs** [play-with-docker/play-with-docker#155]
Hi Team,

I did a local deployment of play-with-docker in a VM, everything works fine except that there the features to deploy swarm cluster is not available ?
Do you know how I can get in working ?

Or is it simply that this feature has not yet been pushed to github ?

Thank you in advance for your feedback

Best Regards,

Gilles

**Comment by marcosnils** [comment]
Hey @gilleslabs that feature hasn't been merged yet as it's not completely tested. We're planning to include it soon.

**Comment by gilleslabs** [comment]
Hi,

Thank you for your feedback :)

Looks like to be in tests branch
Going to try with this branch

FYI, If your interested with, I'm preparing some Vagrantfile for having this sandbox environment so that people can play locally on their laptop.

(yes I know everything should move to the cloud ;) )

**Comment by matjohn2** [comment]
+1 Wanting to hack on the "templates" functionality.

Is there a public version, even if not fully ready for merge?

**Comment by marcosnils** [comment]
not yet. We'll try to merge it here this week.

**Comment by marcosnils** [comment]
We just meged this into `master`.
