### ISSUE TITLE
pwd driver for Docker Machine

### ISSUE THREAD

**Issue by lucj** [play-with-docker/play-with-docker#156]
Hi, 

as docker-machine binary is available in each instance, do you think the pwd driver could be installed as well ? This would help to demo Docker Machine without any link to cloud provider's driver and issue command like:

```docker-machine create -d pwd dm-node0```

**Comment by marcosnils** [comment]
@lucj think so. Does it make sense to manage PWD withing PWD? :face_with_head_bandage: ?

**Comment by lucj** [comment]
@marcosnils I think the use case could be to demo Docker-Machine directly within PWD, instead of popping up test instances on AWS, DO, ..
During a training, people using "Docker for Windows" were not able to play with Docker Machine as it was not possible to create a new VM on VirtualBox nor on Hyper-V.

**Comment by marcosnils** [comment]
@lucj the thing is that it's not possible to do `docker-machine ssh` in PWD at this moment. I wouldn't like users to "learn" how to use machine with some missing features. It makes the experience quite ackward.

**Comment by lucj** [comment]
@marcosnils I totally agree with you.
A workaround for the problem I had last time could be to have D4W users to install pwd driver then.
Thanks a lot.
