### ISSUE TITLE
Cannot connect to the Docker daemon in instances

### ISSUE THREAD

**Issue by patrick-mota** [play-with-docker/play-with-docker#166]
First I tried to install PWD following the README in a remote server but couldn't configure HAProxy or iptables redirection to access it outside the local machine.

So I tried install PWD with the following documentation from the wiki:
https://github.com/play-with-docker/play-with-docker/wiki/Deploying-PWD-in-your-own-infrastructure

I got the PWD up and running and can go to the web ui and create a new instance.
But when I do 

> docker ps

> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

This is the cmd I used to start my PWD container

> docker run -d \
        -e DIND_IMAGE=franela/dind:overlay2 \
        -e GOOGLE_RECAPTCHA_DISABLED=true \
        -e MAX_PROCESSES=10000 \
        -e EXPIRY=4h \
        --name pwd \
        -p 80:3000 \
        -p 443:3001 \
        -p 53:53/udp \
        -p 53:53/tcp \
        -v /var/run/docker.sock:/var/run/docker.sock -v sessions:/app/pwd/ \
        --restart always \
        franela/play-with-docker:latest ./play-with-docker --name pwd --cname pwdlinux.dev --save ./pwd/sessions

The socket seems to be mounted

>   docker exec -ti pwd ls /var/run/
docker.sock

Any idea ?

**Comment by marcosnils** [comment]
in your PWD session try staring the docker daemon with `dockerd` and check why it fails.

**Comment by patrick-mota** [comment]
Thank you for your fast answer !

> $ dockerd
WARN[0000] The "graph" config file option is deprecated. Please use "data-root" instead.
WARN[0000] Running experimental build
WARN[0000] could not change group /var/run/docker.sock to docker: group docker not found
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock)
WARN[0000] [!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]
DEBU[0000] Listener created for HTTP on tcp (0.0.0.0:2375)
INFO[0000] libcontainerd: new containerd process, pid: 133
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=2 memory=3791 runtime=docker-runc runtimeArgs=[] stateDir="/var/run/docker/libcontainerd/containerd"
DEBU[0000] libcontainerd: containerd health check returned error: rpc error: code = 14 desc = grpc: the connection is unavailable
DEBU[0001] Using default logging driver json-file
DEBU[0001] Golang's threads limit set to 27090
DEBU[0001] [graphdriver] trying provided driver: overlay2
DEBU[0001] Cleaning up old mountid : start.
Error starting daemon: error initializing graphdriver: driver not supported

So it seems related to overlay2.
Gonna google and try to find a solution.
Maybe it's because I'm running in centos 7 and I changed (like the wiki said) to storage-driver: devicemapper.

**Comment by marcosnils** [comment]
@patrick-mota try changing your `DIND_IMAGE` variable to `franela/dind` without the `overlay2` tag

**Comment by patrick-mota** [comment]
@marcosnils Thank you it seems working ! :) Just the first instance when I click at add new instance takes a while (around 3mn) but after the next ones are instant.

**Comment by marcosnils** [comment]
the first one took some time because PWD probably pulled the image. You should be good now. :+1:
