### ISSUE TITLE
Cannot Access PWD GUI after following steps from development section in README

### ISSUE THREAD

**Issue by SainathM** [play-with-docker/play-with-docker#169]
I followed the steps listed below as described in the Readme section:

tart the Docker daemon on your machine and run docker pull franela/dind.

1. Install go 1.7.1+ with brew on Mac or through a package manager.

2. go get -v -d -t ./...

3. Start PWD as a container with docker-compose up.

4. Point to http://localhost and click "New Instance"

----------------------------------------------------------------------------------------------------------------------

So all my containers are up and running and I can access my grafana container at http://ip:3000 but I cannot do the same for my pwd sessions. Is there something I need to do, to get this working? In other words step 4 is not working for me.

I appreciate the help.

**Comment by marcosnils** [comment]
Hi. You need to use `localhost` as your hostname. Check the haproxy.conf file.

**Comment by SainathM** [comment]
Hi, Thank you for the quick response. I did use localhost as my hostname, instead of getting directed to a page where I can add instances, I get directed to a Windows Internet Information Services page.
