### ISSUE TITLE
Using PWD on iPad Pro

### ISSUE THREAD

**Issue by lrsvendsen** [play-with-docker/play-with-docker#170]
Hi,

I use my iPad Pro extensively when I travel and like what you have created. However the shell ends up at the bottom of the web page conflicting with the auto completion menu bar. A solution cloud be to reposition the shell higher on the page.

Regards,
Lars

**Comment by marcosnils** [comment]
Hi Lars,

Thx for the feedback. We're doing a re-work on the frontend. We'll make sure to take this into account. Thx for the feedback

**Comment by lrsvendsen** [comment]
Thanks for the response. It is highly appreciate if you can make the small change to the UI. I am happy to test it out.

Regards,
Lars

On 27 Jul 2017, at 22.21, Marcos Nils <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Lars,

Thx for the feedback. We're doing a re-work on the frontend. We'll make sure to take this into account. Thx for the feedback

**Comment by todaywasawesome** [comment]
This issue still exists.

**Comment by marcosnils** [comment]
> This issue still exists.

Sorry about that, reworking the UI for tablets has being deprioritized and there's no roadmap that it'll be implemented. I'll just close this issue since there's no on-going work on this. PR's and proposals are welcome
