### ISSUE TITLE
Which image to use for no restrictions on time and number of instances

### ISSUE THREAD

**Issue by SainathM** [play-with-docker/play-with-docker#174]
Hi, I am running a copy of PWD locally and I want to try to modify the image so there are no restrictions on time and number of instances. In the Readme you suggested changing the environment variable for the image used. Do we have to change the environment variable in the config.go file?

Thanks

**Comment by marcosnils** [comment]
HI, instance number is hardcoded here: 

https://github.com/play-with-docker/play-with-docker/blob/master/handlers/new_instance.go#L22

And session time is controlled here:

https://github.com/play-with-docker/play-with-docker/blob/master/config/config.go#L46-L61

**Comment by SainathM** [comment]
Thank you for the quick reply. What would I have to do after I make the changes for those changes to take effect?
