### ISSUE TITLE
[PWK] Default kube-dns dnsmasq configuration only allows 150 concurrent DNS req's

### ISSUE THREAD

**Issue by matjohn2** [play-with-docker/play-with-docker#179]
Hi All,

Awesome work with PWK. Tried myself ontop of the existing PWD but was having issues exposing the necessary bits and overlays to satisfy kubeadm. (Noticed this is now CentOS based, that makes sense.. But another conversation for another day!)

Wanted to highlight an issue with the default dnsmasq configuration inside kube-dns, it bombs out at a configured limit of 150 concurrent requests, leading to a failed healthcheck and a restart, meaning DNS goes away for 15+ seconds cluster wide at random times. 

It's pretty easy to get to 150 requests across even a demo cluster, especially given real-world DNS requests get stuck for a little bit as theres no forward resolver configured.

Affected clusters will have the following logs:
`kubectl --namespace=kube-system logs <kube-dns-podxyz> dnsmasq`

```
I0809 13:43:47.485776      45 nanny.go:108] dnsmasq[64]: Maximum number of concurrent DNS queries reached (max: 150)
I0809 13:43:57.500488      45 nanny.go:108] dnsmasq[64]: Maximum number of concurrent DNS queries reached (max: 150)
I0809 13:44:07.512986      45 nanny.go:108] dnsmasq[64]: Maximum number of concurrent DNS queries reached (max: 150)
```

`kubectl --namespace=kube-system logs <kube-dns-podxyz> sidecar`

```
ERROR: logging before flag.Parse: W0809 13:40:41.250002       7 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:35703->127.0.0.1:53: i/o timeout
ERROR: logging before flag.Parse: W0809 13:40:54.273636       7 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:45732->127.0.0.1:53: i/o timeout
ERROR: logging before flag.Parse: W0809 13:41:01.274108       7 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:46985->127.0.0.1:53: i/o timeout
```

With an increasing dnsmasq restart count in 
`kubectl --namespace=kube-system describe po <kube-dns-podxyz>`

**Comment by matjohn2** [comment]
PS.. If the "right" answer is just to scale DNS, fair enough, but it may be worth putting the scale command in the start instructions for node 1, or indeed changing the manifest so 2-3 instances get deployed.

**Comment by JockDaRock** [comment]
Yes and thank you @matjohn2 for raising this issue. this is a problem when deploying [faas-netes](https://github.com/alexellis/faas-netes) to PWK.

Also, outside DNS is disabled by default.  can you configure dnsmasq to allow for outside name resolution fo containers?

**Comment by marcosnils** [comment]
> Awesome work with PWK. Tried myself ontop of the existing PWD but was having issues exposing the necessary bits and overlays to satisfy kubeadm. (Noticed this is now CentOS based, that makes sense.. But another conversation for another day!)

Hey there, glad you like PWK!. Regarding the CentOS image, the main reason we used it in the first place is because kubeadm needs systemctl and the only image that seemed to have proper systemd configuration was CentOS (we couldn't find a proper ubuntu one at that time). However, in PWK we finally  managed to hack and mock systemd so it should be pretty simple to switch to another distro. I'd love to know your reasons to move away from CentOS to see if it's worth the effort ATM.

> Wanted to highlight an issue with the default dnsmasq configuration inside kube-dns, it bombs out at a configured limit of 150 concurrent requests, leading to a failed healthcheck and a restart, meaning DNS goes away for 15+ seconds cluster wide at random times.

Makes sense, kubeadm automatically deploys and provision kube-dns. Do you know if there's a way to tell kube-adm to change this?. We're not K8s experts and I haven't seen an option for kubeadm to override this configuration

**Comment by marcosnils** [comment]
> Also, outside DNS is disabled by default. can you configure dnsmasq to allow for outside name resolution fo containers?

Sure, what do you need exactly to work?. Is this a kube-dns configuration or a `dind` thing?.

**Comment by matjohn2** [comment]
Hey @marcosnils Actually I've no problem with it being CentOS, i was just wondering if you needed something that wasnt available in alpine... systemd, got it! :)

Looking deeper, you're right; I think both of these things are kubeadm 'defaults' rather than specifically PWK. I'll see if I can get a kubeadm init to change these settings then let you know.

**Comment by jjo** [comment]
Just completeness, as per #181, I can workaround it to allow extn DNS resolution with:
```
kubectl get deployment --namespace=kube-system kube-dns -oyaml|sed -r 's,(.*--server)=(/ip6.arpa/.*),&\n\1=8.8.8.8,'|kubectl apply -f -
```

**Comment by alexellis** [comment]
@jjo anything we can add to the config in FaaS or no?

**Comment by marcosnils** [comment]
Hey @luxas is there anything we can do from kubeadm perspective to bootstrap kube-dns with this option by default?. Haven't seen anything for that AFAIK.
