### ISSUE TITLE
[PWK] allow external dns resolution

### ISSUE THREAD

**Issue by jjo** [play-with-docker/play-with-docker#181]
While testing some external connectivity, I found that extn DNS was not working, until I added an explicit ``--server ...` to kube-dns with:

`kubectl get deployment --namespace=kube-system kube-dns -oyaml|sed -r 's,(.*--server)=(/ip6.arpa/.*),&\n\1=8.8.8.8,'|kubectl apply -f -`

After above, I could resolve extn resources from inside the pods.

**Comment by marcosnils** [comment]
@jjo thx for the notice. Have you checked https://github.com/play-with-docker/play-with-docker/issues/179 ?. Seems like this requires a kube-dns change. As we're using kubeadm to bootstrap the cluster doesn't seem something that we can easily change.

Thougts?

**Comment by jjo** [comment]
Ah right, indeed - thus above `kubectl` indeed does nicely workaround it 0:)

**Comment by marcosnils** [comment]
I'll close this issue and leave #179 open to evaluate this in the future whenever kubeadm allows kube-dns easy configuration..
