### ISSUE TITLE
[PWK][hint] using tmate inside PWK

### ISSUE THREAD

**Issue by jjo** [play-with-docker/play-with-docker#182]
This is not an issue but rather a hint: to be able to reach PWK from a terminal (thru an encrypted ssh session fwiw ;), after creating a new session I usually do:

```
wget https://github.com/tmate-io/tmate/releases/download/2.2.1/tmate-2.2.1-static-linux-amd64.tar.gz && tar zxf tmate-*.tar.gz && ln -sf $PWD/tmate-*/tmate /usr/local/bin
script -qfc tmate |egrep -o ssh.session:.*
```
Then connect to the displayed tmate.io ssh session parameters from a comfy
local terminal, and kick the browser attached `tmate` from inside it with:
`pkill -1 tmate`.

Just in case it helps other (and/or we can haz tmate installed by default ;).

Thanks for the awesome stuff! --jjo

**Comment by marcosnils** [comment]
Thx!.

**Comment by marcosnils** [comment]
@jjo BTW, there's no need to install tmate, you can actually ssh into the PWK instances automatically. Check https://medium.com/@marcosnils/pwd-ssh-c12080ea11d1 and https://github.com/kelseyhightower/kubeadm-single-node-cluster/pull/1

**Comment by arapulido** [comment]
Hello, 

I tried to SSH into my instance following that medium.com advice and it failed for me.

My instance dashboard is at: http://ip10-0-11-3-30618.host2.labs.play-with-k8s.com

So I did:

ssh -p 1022 10-0-11-3-30618@host2.labs.play-with-k8s.com

But it closes the connection.

Am I doing anything wrong? Thanks!

**Comment by marcosnils** [comment]
hey @arapulido!. Take into account that the `30618` is the service port and not the short session id. You should replace that with the `short` session identifier that you see here:

![image](https://user-images.githubusercontent.com/1578458/29369975-7a99ef52-827a-11e7-9518-4c1eb69a5eec.png)

You need to use the characters up to the underscore
