### ISSUE TITLE
Provide a way for user to generate tutorials

### ISSUE THREAD

**Issue by jonocodes** [play-with-docker/play-with-docker#184]
I would like to provide an HTML page to my users on my site for my app, and have it look like this page:
http://training.play-with-docker.com/multi-stage/

This way, the can click the bash commands on the left and see them execute on the right in my terminal.

**Comment by marcosnils** [comment]
You can do this today, PWD has an SDK to you can use for this https://github.com/play-with-docker/sdk. Additionally, the training site material is also open source. Code can be found here: https://github.com/play-with-docker/play-with-docker.github.io
