### ISSUE TITLE
Links with query parameters

### ISSUE THREAD

**Issue by jonocodes** [play-with-docker/play-with-docker#188]
For the most part the links are working, but I have one with a query parameter that is being ignored.

For example, this link:
`<a href="/article?id=abc/xyz" data-term=".term1" data-port="8015">Article abc</a>`

Sends me to:
http://pwd10-0-63-3-8015.host2.labs.play-with-docker.com/article

Instead of sending me here where I would prefer
http://pwd10-0-63-3-8015.host2.labs.play-with-docker.com/article?id=abc/xyz

**Comment by marcosnils** [comment]
This is part of the SDK, can you please open an issue in this repo https://github.com/play-with-docker/sdk with a sample HTML file that reproduces the issue?. Thx!.
