### ISSUE TITLE
Add support for new releases

### ISSUE THREAD

**Issue by rcjsuen** [play-with-docker/play-with-docker#190]
Are there any plans for providing instances that use the next version of Docker? I would like to test the Docker 17.09 RCs in PWD.

**Comment by stealthybox** [comment]
You can choose the base image for the cluster which allows you to use the rc's.
IIRC there's a URL argument for it.

**Comment by marcosnils** [comment]
We haven't yet buidt 17.09 images. We'll try to update them this weekend.

sent from mobile

**Comment by marcosnils** [comment]
Done!. 

![image](https://user-images.githubusercontent.com/1578458/30510382-19d5f850-9a99-11e7-9e86-55145d808c91.png)

**Comment by rcjsuen** [comment]
@marcosnils Can confirm! Thanks for doing this!

Should this issue be closed or are you leaving it open so that the image is updated again when 17.09 is officially released?

**Comment by marcosnils** [comment]
You can go ahead and close this. We usually try to update PWD images at the same time as releases, but sometime we just forget about it :)
