### ISSUE TITLE
PWD fails to start with client.IsErrImageNotFound

### ISSUE THREAD

**Issue by daveolker** [play-with-docker/play-with-docker#194]
A couple months back I setup PWD successfully on a RHEL 7.X system.  This week I attempted to setup PWD again on a newly installed RHEL 7.4 system and it is failing with the following messages:

pwd2          | # github.com/play-with-docker/play-with-docker/docker
pwd2          | docker/docker.go:278:6: undefined: client.IsErrImageNotFound
pwd2          | docker/docker.go:349:83: cannot use types.ExecConfig literal (type types.ExecConfig) as type types.ExecStartCheck in argument to d.c.ContainerExecAttach
pwd1          | # github.com/play-with-docker/play-with-docker/docker
pwd1          | docker/docker.go:278:6: undefined: client.IsErrImageNotFound
pwd1          | docker/docker.go:349:83: cannot use types.ExecConfig literal (type types.ExecConfig) as type types.ExecStartCheck in argument to d.c.ContainerExecAttach
pwd2 exited with code 2
pwd1 exited with code 2

Here are all the versions of products installed and the steps I used to reproduce:

# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME=Storage
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"

# docker --version
Docker version 17.09.0-ce, build afdb6d4

# docker-compose --version
docker-compose version 1.14.0, build c7bdf9e

# go version
go version go1.8.3 linux/amd64

# modprobe xt_ipvs

# docker pull franela/dind

# docker swarm init

# git clone https://github.com/play-with-docker/play-with-docker.git
Cloning into 'play-with-docker'...
remote: Counting objects: 1957, done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 1957 (delta 57), reused 70 (delta 46), pack-reused 1857
Receiving objects: 100% (1957/1957), 976.72 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1227/1227), done.

# cd play-with-docker
[play-with-docker]# go get -v -d -t ./...
github.com/gorilla/handlers (download)
created GOPATH=/root/.go; see 'go help gopath'
github.com/gorilla/mux (download)
github.com/miekg/dns (download)
github.com/play-with-docker/play-with-docker (download)
github.com/docker/docker (download)
github.com/googollee/go-socket.io (download)
github.com/googollee/go-engine.io (download)
github.com/gorilla/websocket (download)
github.com/inconshreveable/go-vhost (download)
github.com/docker/distribution (download)
github.com/docker/go-connections (download)
github.com/pkg/errors (download)
github.com/docker/go-units (download)
github.com/prometheus/client_golang (download)
github.com/beorn7/perks (download)
github.com/golang/protobuf (download)
github.com/prometheus/client_model (download)
github.com/prometheus/common (download)
github.com/matttproud/golang_protobuf_extensions (download)
github.com/prometheus/procfs (download)
github.com/twinj/uuid (download)
Fetching https://golang.org/x/text/encoding?go-get=1
Parsing meta tags from https://golang.org/x/text/encoding?go-get=1 (status code 200)
get "golang.org/x/text/encoding": found meta tag main.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/encoding?go-get=1
get "golang.org/x/text/encoding": verifying non-authoritative meta tag
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
golang.org/x/text (download)
github.com/gorilla/securecookie (download)
github.com/shirou/gopsutil (download)
Fetching https://golang.org/x/crypto/ssh?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ssh?go-get=1 (status code 200)
get "golang.org/x/crypto/ssh": found meta tag main.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ssh?go-get=1
get "golang.org/x/crypto/ssh": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
github.com/urfave/negroni (download)
github.com/stretchr/testify (download)

[play-with-docker]# docker-compose up
...
pwd2          | # github.com/play-with-docker/play-with-docker/docker
pwd2          | docker/docker.go:278:6: undefined: client.IsErrImageNotFound
pwd2          | docker/docker.go:349:83: cannot use types.ExecConfig literal (type types.ExecConfig) as type types.ExecStartCheck in argument to d.c.ContainerExecAttach
pwd1          | # github.com/play-with-docker/play-with-docker/docker
pwd1          | docker/docker.go:278:6: undefined: client.IsErrImageNotFound
pwd1          | docker/docker.go:349:83: cannot use types.ExecConfig literal (type types.ExecConfig) as type types.ExecStartCheck in argument to d.c.ContainerExecAttach
pwd2 exited with code 2
pwd1 exited with code 2

# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
golang              latest              99e596fc807e        41 hours ago        733MB
haproxy             latest              4bb854517f75        47 hours ago        136MB
prom/prometheus     latest              03f045a7680f        5 days ago          75.4MB
grafana/grafana     latest              1d2e2705fd26        2 weeks ago         303MB
franela/dind        latest              cf7825f158f8        3 months ago        479MB

Any suggestions?

**Comment by marcosnils** [comment]
This is beacuse docker/docker changed and we're not vendoring dependecies. We're working in a different branch fixing all this dependency issues.

**Comment by daveolker** [comment]
Thanks Marcos.  Is there a PWD branch I can clone from that resolves these dependency issues, or will you post an update here when the branch is published?

**Comment by marcosnils** [comment]
@daveolker not ATM. I'll close this issue when we merge our branch into master after making sure everything works as expected

**Comment by pushou** [comment]
Got the same error with Ubuntu 16.04. 
pwd2          | # github.com/play-with-docker/play-with-docker/docker
pwd2          | docker/docker.go:278:6: undefined: client.IsErrImageNotFound
pwd2          | docker/docker.go:349:83: cannot use types.ExecConfig literal (type types.ExecConfig) as type types.ExecStartCheck in argument to d.c.ContainerExecAttach
pwd1          | # github.com/play-with-docker/play-with-docker/docker
pwd1          | docker/docker.go:278:6: undefined: client.IsErrImageNotFound
pwd1          | docker/docker.go:349:83: cannot use types.ExecConfig literal (type types.ExecConfig) as type types.ExecStartCheck in argument to d.c.ContainerExecAttach
pwd2 exited with code 2
pwd1 exited with code 2

Waiting for the new branch

**Comment by moyni77** [comment]
Is there any further update, or a time line when the new branch will be made available?

**Comment by marcosnils** [comment]
Yes, next branch will be available next week.

**Comment by moyni77** [comment]
Excellent news will keep an eye out for it.

**Comment by leseb** [comment]
I'm facing the same problem on my project.
I'm not sure how this got resolved here, can anyone help me?
Thanks.

I'm getting:

`cannot use options (type types.ExecConfig) as type types.ExecStartCheck in argument to cli.ContainerExecAttach`.
