### ISSUE TITLE
short-url https://git.io/kube-dashboard no longer supported by kubernetes

### ISSUE THREAD

**Issue by unthought** [play-with-docker/play-with-docker#195]
The k8s PWK welcome screen states:

```
 3. (Optional) Initialize kube-dashboard:

 curl -L -s https://git.io/kube-dashboard  | sed 's/targetPort: 9090/targetPort: 9090\n  type: LoadBalancer/' |\
    kubectl apply -f -
```

According to kubernetes/dashboard#2477, https://git.io/kube-dashboard is no longer supported, and should probably be https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

**Comment by floreks** [comment]
Yes it should point to full link as `git.io` shortened links can not be updated, we prefer not to use them anymore.

**Comment by marcosnils** [comment]
Instructions have been updated. Seems like kube dashboard now uses https and requires authentication. @floreks is there a way to disable both?. As we'd like the PWK experience to be as smooth as possible.

**Comment by marcosnils** [comment]
Just found the alternate deployment method. Now figuring out a way to deal with the Authorization header.
