### ISSUE TITLE
Can't ssh into PWD instances

### ISSUE THREAD

**Issue by anthonydahanne** [play-with-docker/play-with-docker#196]
Hello,
I've tried following instructions from @marcosnils  provided at https://medium.com/@marcosnils/pwd-ssh-c12080ea11d1 , but I could not connect to my instances from my laptop : 

```
$ ssh -p 1022 10-0-4-4-98c8d0f6@host3.labs.play-with-docker.com
ssh: connect to host host3.labs.play-with-docker.com port 1022: Connection refused
```

What did I do wrong ? Thanks !

**Comment by marcosnils** [comment]
hey @anthonydahanne!. Thx for noticing Can you please try now?, I've noticed that something was missing in that particular PWD node.

**Comment by anthonydahanne** [comment]
that worked ! thanks a lot !
btw, I was wondering if it was possible, instead of ssh'ing into any single node, is it possible to tie my docker and docker-compose clis to the PWD created swarm ?

**Comment by marcosnils** [comment]
yes indeed. Check this out:

https://www.youtube.com/watch?v=-h2VTE9WnZs

**Comment by sangam14** [comment]
how to plugin after downloading docker-machine-pwd source code
