### ISSUE TITLE
Add sudo tool to ease blog instruction

### ISSUE THREAD

**Issue by jmkhael** [play-with-docker/play-with-docker#200]
Several blogs are now referencing PWD as the de-facto playground for running instructions.
However, to make these instructions transposable to user machines, one have to specify two flavors of commands if running on PWD or locally when it comes to `sudo` commands, as the command is not installed on PWD instances.

e.g.: 

run locally:
```
curl -sSL https://cli.openfaas.com | sudo sh
```
or on **PWD**:
```
curl -sSL https://cli.openfaas.com | sh
```

Can you add the sudo command to the default packages installed?
`apk add sudo --no-cache`

**Comment by marcosnils** [comment]
we thought about it, the problem is that sudo sometimes causes problems when it's executed in containers is it does some funky stuff with the tty. We came up with some problems in the past, that's why we're not including it.

**Comment by jonocodes** [comment]
I know its hacky, but what if there was a dummy sudo script that when executed as root just passed the commands along. Then they would not into this problem.

**Comment by jmkhael** [comment]
That historically happened when /etc/sudoers has the `requiretty` setting.
This isn't the case on Alpine. (Was on Redhat OSes though: https://bugzilla.redhat.com/show_bug.cgi?id=1020147)

```
[node1] (local) root@10.0.25.3 ~
apk add sudo --no-cache
$  grep req /etc/sudoers | wc -l
0
```
I couldn't check the reason of why the below sentence was added to https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#user.
>"You should avoid installing or using sudo since it has unpredictable TTY and signal-forwarding behavior that can cause more problems than it solves"
(https://github.com/docker/docker.github.io/commits/master/engine/userguide/eng-image/dockerfile_best-practices.md)

Maybe this could shed a light. (or checking with someone in Docker Slack community)

@jonocodes workaround maybe useful too in case all else fails...

**Comment by marcosnils** [comment]
@jonocodes that could work. @jmkhael if you can give it a try withti  your use-case with a dummy sudo, I'll be happy to include it

**Comment by jmkhael** [comment]
workaround works. 

1. create sudo script
```
$ cat sudo
eval ${@:1:2}
```
2. avoid the ./:
`export PATH=$PATH:.`

3. Profit

```
$ sudo echo "Hello, play with docker"
Hello, play with docker
```
http://host4.labs.play-with-docker.com/p/6f744891-2e1d-4f47-b48f-d71c4f8bda09#6f744891_node2

**Comment by marcosnils** [comment]
what about an alias?

`alias sudo=""`?

**Comment by jonocodes** [comment]
@marcosnils yes, that alias seems good. And works with the openfaas example above.

But I also like the shell solution because it is a little more transparent to the user. If they even run into and issue with it, they will see it and see the note in the home directory.

Here is my new recommendation, slight modification to the script from @jmkhael 

/root/sudo
```
#!/usr/bin/env bash

# This is shim to help with the case were pasted commands from a readme assume you are not root. Since this is to be run by root, it should effectively be a dummy command that allows the parameters to pass through.

$@
```

```
chmod +x sudo
export PATH=$PATH:/root
```

I can fish around and file a PR if you think this is ok.

**Comment by marcosnils** [comment]
@jonocodes thx!. No need to open a PR, I'll update the images in a second.

**Comment by jmkhael** [comment]
that's great! thank you @marcosnils @jonocodes!

**Comment by jonocodes** [comment]
sure thing. I wrote a readme a while back with your exact openfaas example above and ran into this  issue.

**Comment by marcosnils** [comment]
@jmkhael @jonocodes done!. Change deployed!.

**Comment by stealthybox** [comment]
Bumping this -- shouldn't the script exec so that the process is replaced?

**Comment by marcosnils** [comment]
@stealthybox probably. Is there a specific case where current approach doesn't work?

**Comment by stealthybox** [comment]
@marcosnils guessing the shell script won't trap/forward signals. `exec` should fix that

**Comment by stealthybox** [comment]
^ this was implemented:
```bash
[node1] (local) root@192.168.0.43 ~
$ cat `which sudo`
#!/usr/bin/env bash

# This is shim to help with the case were pasted commands from a readme assume you are not root. Since this isto be run by root, it should effectively be a dummy command that allows the parameters to pass through.

exec $@
```

**Comment by marcosnils** [comment]
Yes, forgot to update the issue
