### ISSUE TITLE
Issue on k8s branch

### ISSUE THREAD

**Issue by dungeonmaster18** [play-with-docker/play-with-docker#205]
Problem: So the k8s branch contains the kubernetes playground code. When the instance is created there is some predefined commands for creating kubenetes environment in that the url for dashboard gives 404 file not found error.

Proposed solution: we need to update the file url.

File to be changed:  play-with-docker/dockerfiles/k8s/motd

P.S I would like to take this issue as well.

**Comment by marcosnils** [comment]
This has been fixed already. If you go to play-with-k8s.com you should see the new dashboard URL.
