### ISSUE TITLE
Some big changes to run play-with-docker

### ISSUE THREAD

**Issue by pgonyan** [play-with-docker/play-with-docker#208]
I had to write some big  changes to run play-with-docker.

- I changed Dockerfile, Dockerfile.l2 and docker-compose.yml
Here are the files https://github.com/etsiiull/desktop-playbook/tree/master/no-ansible-scripts/conf-pwd
(some changes are go dep, added some apk packages, ...)
(build: . in docker-compose.yml)

- I had to pull franela/dind:hybrid

Here is a basic install script 
https://github.com/etsiiull/desktop-playbook/blob/master/no-ansible-scripts/instala-pwd

Now it's working but I think I'm loosing something (it's something wrong in this repo??)

**Comment by marcosnils** [comment]
> I changed Dockerfile, Dockerfile.l2 and docker-compose.yml

You shouldn't have to run any `dep` stuff inside the Dockerfile. Vendor files should be in the host and copied with the code in the COPY step so Docker doesn't download them every time.

> I had to pull franela/dind:hybrid

no need to do this as well.

> Now it's working but I think I'm loosing something (it's something wrong in this repo??)

Nope. Just clone the repo and follow the README instructions to get it working
