### ISSUE TITLE
Error installing over Ubuntu 16.04

### ISSUE THREAD

**Issue by pgonyan** [play-with-docker/play-with-docker#210]
This video shows an error installing a executing play-with-docker.
https://youtu.be/7uNWnkDd0RY

This is the error:
`Attaching to haproxy, l2, pwd
haproxy    | <7>haproxy-systemd-wrapper: executing /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -Ds 
pwd        | /bin/sh: 1: cd: can't cd to /go/src/github.com/play-with-docker/play-with-docker
l2         | /bin/sh: 1: cd: can't cd to /go/src/github.com/play-with-docker/play-with-docker/router/l2
pwd        | stat api.go: no such file or directory
l2         | stat l2.go: no such file or directory
pwd exited with code 1
l2 exited with code 1`

Those are the steps i following
`
# go things...
cd /usr/local
curl -O https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz
tar xvfz go1.8.linux-amd64.tar.gz
rm -f go1.8.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin:/root/go/bin
export GOPATH=/root/go
mkdir -p $GOPATH/src/github.com

cd /root/go/src
go get -u github.com/golang/dep/cmd/dep

# play-with-docker things...
cd /root/go/src/github.com
git clone https://github.com/play-with-docker/play-with-docker.git
dep init
dep ensure

# docker things...
docker pull franela/dind
docker swarm init
curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

cd /root/go/src/github.com/play-with-docker
docker-compose up

`

**Comment by marcosnils** [comment]
> cd /root/go/src/github.com
> git clone https://github.com/play-with-docker/play-with-docker.git
Here's the issue. 

You need to clonse PWD in `$GOPATH/src/github.com/play-with-docker` and not `$GOPATH/src/github.com` like you did
