### ISSUE TITLE
How to use 'Try in PWD' button to launch multi node swarm cluster on PWD

### ISSUE THREAD

**Issue by achautha** [play-with-docker/play-with-docker#212]
I have added **Try in PWD**  button in my github [repo](https://github.com/achautha/PiggyMetrics) to launch a stack of services. However, I have more than 10 services in the stack which can't fit into one node. 

How do I launch 5 node cluster using the PWD url ? 

[http://play-with-docker.com/?stack=https://raw.githubusercontent.com/achautha/PiggyMetrics/master/docker-compose-3.yml&stack_name=piggymetrics](http://play-with-docker.com/?stack=https://raw.githubusercontent.com/achautha/PiggyMetrics/master/docker-compose-3.yml&stack_name=piggymetrics)

**Comment by marcosnils** [comment]
This is not supported for the moment. The button only launches just one instance.
