### ISSUE TITLE
Published ports are not routed

### ISSUE THREAD

**Issue by lmakarov** [play-with-docker/play-with-docker#213]
After starting an instance and launching an nginx container with `docker run -d -p 80 nginx` the nginx container port was not routed:

![image](https://user-images.githubusercontent.com/1205005/32692053-28695688-c6c6-11e7-8b9f-81346334b110.png)

The URL pattern for published ports mentioned in README.md also looks to be outdated:

```
http://pwd<hyphen-ip>-<port>.<host#>.labs.play-with-docker.com (i.e: http://pwd10-2-135-3-80.host3.labs.play-with-docker.com)
```
My session had a different URL structure and a different IP range assigned to individual nodes:

```
https://labs.play-with-docker.com/p/b83jgu363jcg00f93rt0#b83jgu36_b83jh0363jcg00f93rtg
```

**Comment by marcosnils** [comment]
Try with docker run -d -p 8080:80 nginx. That should work

sent from mobile

**Comment by lmakarov** [comment]
@marcosnils I tried that as well, but the result was the same.

**Comment by marcosnils** [comment]
fixed!.
