### ISSUE TITLE
Minor Documentation Issue

### ISSUE THREAD

**Issue by max-neverov** [play-with-docker/play-with-docker#214]
It states in [networking lab](http://training.play-with-docker.com/docker-networking-hol) (Step 4: Test the network) that after we ran two services and ping one from another there is 100% packet loss. The output of ping command is shown after words "Now, lets ping 10.0.0.3.".
I believe the output should be opposite, something like "5 packets transmitted, 5 received, 0% packet loss, time 3997ms".

**Comment by marcosnils** [comment]
Can you please open this issue here: https://github.com/play-with-docker/play-with-docker.github.io. This repo is for the PWD code, it doesn't hold the interactive tutorials.

**Comment by max-neverov** [comment]
Ok, thanks.
