### ISSUE TITLE
Can install UCP, but can't reach it

### ISSUE THREAD

**Issue by witsec** [play-with-docker/play-with-docker#220]
Hi,

I tried running Docker UCP in PWD. It installs just fine, all the containers seem to be created, but when I click the "443" port, my browser wants to download some binary file, it doesn't open a new window to UCP. I tried multiple browsers, doesn't seem to help. Running other images is no problem though, they work as expected.

I found this issue, https://github.com/play-with-docker/play-with-docker/issues/158, where it is confirmed it's possible, but I can't get it to work (some links are outdated there, but found the correct stack.yml and such).

Any idea what to do?

Thanks.

**Comment by marcosnils** [comment]
@witsec when you click in the `443` badge by default PWD opens the url in `http` because it doesn't know what you're trying to expose. Just change that url to `https` and it should work.
