### ISSUE TITLE
franela/dind:hybrid image needed

### ISSUE THREAD

**Issue by pgonyan** [play-with-docker/play-with-docker#226]
After installing and running PWS this error appear when I try to create a new instance in the web browser.
`
pwd        | [negroni] Started POST /sessions/b8c0hmno1vfgd9qort6g/instances
pwd        | 2017/11/24 11:56:14 Error: No such image: franela/dind:hybrid
pwd        | 2017/11/24 11:56:14 Error: No such image: franela/dind:hybrid
`

**Comment by pgonyan** [comment]
Here is my instalation script
https://gist.github.com/pgonyan/7704792507fbbb0166735c62fb9041bf

After pulling franela/dind:hybrid I can create instances. But I get some error in logs

`
cond. Try #1. Got: Get http://ip10-0-0-3-b8c1033b2ujgd9ivl9k0-10255/pods: EOF
l2         | 2017/11/24 12:30:09 Proxying http connection to ip10-0-0-4-b8c1033b2ujgd9ivl9k0-10255. Discover took 130.514µs. Http read took 40.029µs
l2         | 2017/11/24 12:30:09 Error dialing backend 10.0.0.4:10255: dial tcp 10.0.0.4:10255: getsockopt: connection refused
pwd        | 2017/11/24 12:30:09 Connection to k8s api has failed, maybe instance is not ready yet, sleeping and retrying in 1 second. Try #2. Got: Get http://ip10-0-0-4-b8c1033b2ujgd9ivl9k0-10255/pods: EOF
l2         | 2017/11/24 12:30:09 Proxying http connection to ip10-0-0-5-b8c1033b2ujgd9ivl9k0-10255. Discover took 116.538µs. Http read took 36.685µs
l2         | 2017/11/24 12:30:09 Error dialing backend 10.0.0.5:10255: dial tcp 10.0.0.5:10255: getsockopt: connection refused
pwd        | 2017/11/24 12:30:09 Connection to k8s api has failed, maybe instance is not ready yet, sleeping and retrying in 1 second. Try #4. Got: Get http://ip10-0-0-5-b8c1033b2ujgd9ivl9k0-10255/pods: EOF
l2         | 2017/11/24 12:30:10 Proxying http connection to ip10-0-0-3-b8c1033b2ujgd9ivl9k0-10255. Discover took 72.099µs. Http read took 15.971µs

`

**Comment by marcosnils** [comment]
Those errors are normal.
