### ISSUE TITLE
PWD only accesible from localhost

### ISSUE THREAD

**Issue by pgonyan** [play-with-docker/play-with-docker#227]
I've installed PWD.
It's runnig an accesible from localhost, but I can't access it from others hosts (or the same) using IP address.
(any special configuration in dnsmasq.conf required?)

`
503 Service Unavailable
No server is available to handle this request. `

**Comment by marcosnils** [comment]
you have to change the haproxy.conf to match the host you want to use.

**Comment by marcosnils** [comment]
Btw, one thing is to run it locally and other is to deploy it for other to use. Check https://github.com/play-with-docker/play-with-docker/wiki/Deploying-PWD-in-your-own-infrastructure
