### ISSUE TITLE
Clarification: stack parameter + stacks

### ISSUE THREAD

**Issue by strarsis** [play-with-docker/play-with-docker#230]
Is it possible to let the play-with-docker live site also use a stack from a repository from my GitHub account? Apparently the paths passed to stack parameter are resolved relative to 
`https://github.com/play-with-docker/stacks`.

**Comment by marcosnils** [comment]
Yes, just send the full url of the raw file from your got repo in the stack parameter

**Comment by strarsis** [comment]
@marcosnils: I just tried this out using this URL:
http://play-with-docker.com/?stack=https://raw.githubusercontent.com/strarsis/twentyseventeen-onepage/master/live-demo/docker-compose.yml

The virtual terminal stays empty, just the cursor is visible.

**Comment by marcosnils** [comment]
@strarsis it worked for me. But the deployment threw an error because some stuff is invalid in the yml. 

Take into account that PWD deploys the stack file as services with `docker stack deploy` and it doesn't use compose.

![image](https://user-images.githubusercontent.com/1578458/33609035-4cd70cb2-d9a5-11e7-8fe2-eb95afc52d5c.png)

**Comment by strarsis** [comment]
@marcosnils: It doesn't work in my browser though. Windows 10, recent Chrome.

**Comment by marcosnils** [comment]
Do you see any errors in the JavaScript console

**Comment by strarsis** [comment]
Now it works.

**Comment by marcosnils** [comment]
?. What did you change?

**Comment by strarsis** [comment]
Nothing, I just restarted the browser and opened the link again I posted above.
Then the terminal logged some text.

**Comment by marcosnils** [comment]
:+1: can we close this?

**Comment by strarsis** [comment]
@marcosnils: It is already closed 😄
