### ISSUE TITLE
Changing "vm.max_map_count" sysctl conf in a node does not work

### ISSUE THREAD

**Issue by yogeek** [play-with-docker/play-with-docker#232]
To launch an ELK stack, the "vm.max_map_count" (/etc/sysctl.conf) parameter must be set to at least "262144" as mentionned in the documentation. 
But the command to change it does not seem to work in PWD nodes :

```
[node1] (local) root@192.168.0.53 ~/swarm-elk
$ sysctl -w vm.max_map_count=262144

[node1] (local) root@192.168.0.53 ~/swarm-elk
$ sysctl vm.max_map_count
vm.max_map_count = 65530
```

Without this parameter set to 262144, elastic container does not start and logs the following error :
```
ERROR: [1] bootstrap checks failed
myself_elasticsearch.1.zbqincb3vovv@node1    | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increaseto at least [262144]
```

I think it must have been worked before because some tutorial indicates so. For example : http://collabnix.com/test-drive-elasticsearch-logstash-kibana-on-pwd-platform-running-docker-17-06-ce-swarm-mode-in-5-minutes/

Is it a regression or it this another way to change this option ?

Thank you for your help

**Comment by marcosnils** [comment]
hey @yogeek thx for reporting the issue. This is probably a regression. Just changed that flag in the PWD sessions.

**Comment by yogeek** [comment]
Great ! Thank you for the fix and the quick answer.
And thanks for this awesome project 👍

**Comment by jangaraj** [comment]
@marcosnils Could you check it again, pls? ELK stack has a problem to start:
```
ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```
http://play-with-docker.com/?stack=https://raw.githubusercontent.com/docker-library/docs/9efeec18b6b2ed232cf0fbd3914b6211e16e242c/elasticsearch/stack.yml

**Comment by marcosnils** [comment]
@jangaraj fixed!.

**Comment by yogeek** [comment]
@marcosnils Sorry but the problem seems to be still here :
```
[node1] (local) root@192.168.0.27 ~
$ sysctl -w vm.max_map_count=262144

[node1] (local) root@192.168.0.27 ~
$ sysctl vm.max_map_count
vm.max_map_count = 65530
```

Do you know why it appears again ? Thank you

**Comment by marcosnils** [comment]
@yogeek fixed. I haven't applied the change in the base PWD image and the server got recycled recently. That's why changes got discarded. I'll try to make it permanently soon
