### ISSUE TITLE
session_jd value within the container

### ISSUE THREAD

**Issue by jangaraj** [play-with-docker/play-with-docker#233]
I would like to provision SSL cert (Let's encrypt) in my bootstrap script. For that I need some variables: http://**\<hyphen-ip\>**-**\<session_jd\>**-<port>.direct.labs.play-with-docker.com. How to get these variables within the running container?

Thanks.

**Comment by marcosnils** [comment]
session_id can be obtained from the env variables in the container. Regarding the hyphen IP you have to do some bashery with IP addr show and parameter expansion

**Comment by jangaraj** [comment]
Thank you @marcosnils. That was my first idea, but I was not able to find any related env variable:
```
# 1st container
[node1] (local) root@192.168.0.33 ~
$ printenv
TERM=xterm
SHELL=/bin/bash
SSH_CLIENT=172.18.0.1 47525 22
SSH_TTY=/dev/pts/2
USER=root
PAGER=less
MAIL=/var/mail/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/go/bin
PWD=/root
PS1=\e[1m\e[31m[\h] \e[32m($(docker-prompt)) \e[34m\u@$(hostname -i)\e[35m \w\e[0m\n$
SHLVL=1
HOME=/root
LOGNAME=root
SSH_CONNECTION=172.18.0.1 47525 172.18.0.24 22
CHARSET=UTF-8
_=/bin/printenv

# 2nd nested container
[node1] (local) root@192.168.0.33 ~
$ docker run --rm -ti ubuntu bash -c printenv
HOSTNAME=0d8544823ca9
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
SHLVL=1
HOME=/root
_=/usr/bin/printenv
```
Do you have any example or variable name for session_id? Your are right, if I have values, then I can pass them to the 2nd nested containver via env variables. IP part is simple, only that session_id is my blocker.

**Comment by marcosnils** [comment]
Where are you trying this?. If you do it in play-with-docker.com you'll see
that the session_id is there



sent from mobile

**Comment by jangaraj** [comment]
You are right. I can see it in the web session:
![image](https://user-images.githubusercontent.com/1182932/34341194-67353f00-e992-11e7-8ff5-a6203384a770.png)
But I can't see it in my SSH session. Let me play. Thx.
