### ISSUE TITLE
Ports links are missing for stack services

### ISSUE THREAD

**Issue by yogeek** [play-with-docker/play-with-docker#234]
Hello,

I am doing the following training : http://collabnix.com/test-drive-elasticsearch-logstash-kibana-on-pwd-platform-running-docker-17-06-ce-swarm-mode-in-5-minutes

When I deploy the visualizer via docker-compose up, the port link "8080" is displayed in the up part.
But when I deploy the stack, the service ports links are not... I must type the URL directly in my browser to access to the web UI (e.g. http://ip172-18-0-16-b978opol9m7g009qi49g-5601.direct.labs.play-with-docker.com)

I already saw this behaviour before but I am not sure if the problem is on my side only...
I do not know if it helps but I'm using "Chrome Version 63.0.3239.84 (Build officiel) (64 bits)"

Thank you for your help and keep up the good work, PWD is awesome !!

**Comment by marcosnils** [comment]
I was able to reproduce the bug. I'll take a look tomorrow and hopefully fix it.

**Comment by sugizo** [comment]
tested for single instance port link is also missing
steps i took
- login into pwd 
- add new instance
- no memory or cpu value on there (below ip and above ssh)
- copas the code

cat << EOF > Dockerfile
FROM alpine:latest

#LABEL stifix

RUN apk add --no-cache build-base gcc make libffi-dev ruby ruby-dev ruby-json && \
 gem install --no-document jekyll bundler jekyll-sitemap jekyll-minifier && \
 cd / && \
 jekyll new site

EXPOSE 4000

WORKDIR /site

CMD bundle exec jekyll serve --host 0.0.0.0

EOF
cat Dockerfile

docker build -t username/alpine-jekyll .
docker run -d -v site:/site -p 4000:4000 --name alpine-jekyll username/alpine-jekyll

is there a way to test it in pwd?

**Comment by marcosnils** [comment]
@sugizo your use case should be fixed alread.y

**Comment by sugizo** [comment]
fixed, thx

**Comment by schmunk42** [comment]
Any updated on this? I remember being able to access published `ports` a while ago, but now I can't see them popping up in the WebUI, neither does the public IP.

**Comment by yogeek** [comment]
@marcosnils Currently having a session where the problem occurs, if it can help :

[PWD url](https://labs.play-with-docker.com/p/b9vck1np7tr000904u40#b9vck1np_b9vck2np7tr000904u4g)

Commands :

- create a swarm cluster 
- docker run -d --rm -p 80:80 nginx
- docker service create -p 81:80 nginx

No port displayed in both cases

**Comment by marcosnils** [comment]
Fixed.

**Comment by yogeek** [comment]
@marcosnils This issue is happening again :

```
# Go to PWD, create a "3 managers/ 2 workers" swarm cluster from the template option

# On the 1st manager
git clone https://github.com/docker/example-voting-app && cd example-voting-app
docker stack deploy --compose-file=docker-stack.yml voting_stack
```

Ports are not displayed as links at the top of the page.
Any idea why this issue comes back from time to time ? 
(I often use PWD with students and I really miss having the port feature to make them easily understand port-forwarding in docker) 
Thank you !
