### ISSUE TITLE
ssh copy not work with chrome

### ISSUE THREAD

**Issue by zgfh** [play-with-docker/play-with-docker#235]
chrome version:   63.0.3239.132
![image](https://user-images.githubusercontent.com/11729624/34859035-caad1a3a-f78e-11e7-8f5f-68c589a3509c.png)

can we just show the ssh text like this?
![image](https://user-images.githubusercontent.com/11729624/34859025-bc3a4bb2-f78e-11e7-91a3-e38bd1f6d699.png)

**Comment by marcosnils** [comment]
Fixed in the latest release!.
