### ISSUE TITLE
(PWK) pods status pending, while the same command is running in katacoda

### ISSUE THREAD

**Issue by sugizo** [play-with-docker/play-with-docker#237]
steps to reproduce :
**pwk**
- open https://labs.play-with-k8s.com
- login 
- add new instance

```
kubeadm init --apiserver-advertise-address $(hostname -i)
kubectl apply -n kube-system -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 |tr -d '\n')"
kubectl apply -f https://k8s.io/docs/user-guide//nginx-app.yaml
kubectl get pods
```

NAME                        READY     STATUS    RESTARTS   AGE
my-nginx-569477d6d8-56sdx   0/1       Pending   0          1m
my-nginx-569477d6d8-lrklk   0/1       Pending   0          1m
my-nginx-569477d6d8-xrcp7   0/1       Pending   0          1m

**katacoda**
- open https://www.katacoda.com/courses/kubernetes/playground
- login

```
kubectl apply -f https://k8s.io/docs/user-guide//nginx-app.yaml
kubectl get pods
```

NAME                        READY     STATUS    RESTARTS   AGE
my-nginx-569477d6d8-wln2k   1/1       Running   0          21s
my-nginx-569477d6d8-wzv29   1/1       Running   0          21s
my-nginx-569477d6d8-xrlpg   1/1       Running   0          21s

**Comment by marcosnils** [comment]
@sugizo this is because kubernetes master node by default doesn't schedule any pods. You need to either add a second "worker" node to schedule or taint (https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/) the master node so it can schedule pods.

**Comment by sugizo** [comment]
tried to learn from the https://kubernetes.io/docs still not clear what to do to make simple tutorial work in play-with-k8s.com, perhaps give some additional info in bootstrap a cluster in play-with-k8s.com, like how to add a second "worker" node to schedule or taint the master node so it can schedule pods
