### ISSUE TITLE
can't ssh to running PWD

### ISSUE THREAD

**Issue by jimo4242** [play-with-docker/play-with-docker#238]
Hello, I have seen it should be possible to SSH to running instance. I have also checked issue https://github.com/play-with-docker/play-with-docker/issues/196 and links inside, but that didn't help.
There is probably a new feature in PWD which is showing the ssh, but even copying it doesn't work.

In comparison with how-to, the address provided in the link to copy contains "ïp" at the begining (ie. ssh ip172-18-0-41-b9rqlaqr91k00089c16g@direct.labs.play-with-docker.com) and looks like it's using standard port 22, not 1022.

However, the attempts are rejected always. It looks as the only allowed auth mechanism is with keys. I tried to add my public ssh key to the machine's authorized_keys, but that still didn't help.

Could you please check? The ssh would be a very nice function, making things a lot easier.

And maybe if things have changed, it would be good to fix the how-to on https://medium.com/@marcosnils/pwd-ssh-c12080ea11d1

**Comment by marcosnils** [comment]
Hey @jimo4242 do you still have issues?. What error do you get?

**Comment by 4goodapp** [comment]
Am Having the same exact issue.

**Comment by 4goodapp** [comment]
Hi, @marcosnils Any reason why you close the issue?

**Comment by 4goodapp** [comment]
@marcosnils It's working now, thanks.

**Comment by marcosnils** [comment]
Yes, because I've requested for more information and nobody is providing it. Seems to me like it's a dupe of https://github.com/play-with-docker/play-with-docker/issues/196 but I can't do anything unless I got more info. Just tried sshing into a PWD instance and it works.

**Comment by marcosnils** [comment]
There's no need to set the port to 1022 anymore. You can just use `ssh ip172-18-0-9-bfe8s7iv9dig00cuhdsg@direct.labs.play-with-docker.com`

**Comment by sidebo** [comment]
I see. With this I however get `Permission denied (publickey).` Do I need to set something up?

**Comment by ironpython2001** [comment]
i am having the same issue

**Comment by ParampreetR** [comment]
To all those who are here for same issue.
Thanks @sidebo
#247 solved my  problem. 

1. Run `ssh-keygen` and fill out name of file and empty passphrase.
2. Run `ssh -i <File name entered in first step> <docker ssh address>`. Example: `ssh -i ida_rsa ip172-18-0-9-bfe8s7iv9dig00cuhdsg@direct.labs.play-with-docker.com`

**Comment by davidmorales0722** [comment]
> To all those who are here for same issue.
> Thanks @sidebo
> #247 solved my problem.
> 
>     1. Run `ssh-keygen` and fill out name of file and empty passphrase.
> 
>     2. Run `ssh -i <File name entered in first step> <docker ssh address>`. Example: `ssh -i ida_rsa ip172-18-0-9-bfe8s7iv9dig00cuhdsg@direct.labs.play-with-docker.com`

Hello, I did this and still get the same error 
Permission denied (publickey)
I'm on Fedora 33

**Comment by mabdullahadeel** [comment]
For anyone getting this error 👇

`Permission denied (publickey).`

I solved it by just creating ssh keys like this

my environment:
 - Ubuntu (WSL2)

`ssh-keygen`

accept all defaults and it worked for me the next time I tried to ssh into the running playground docker machine.

**Comment by gitdlnow** [comment]
In ubuntu 22, in u need to gen keys like: 
`
ssh-keygen -t ed25519 -P "" -f ~/.ssh/id_ed25519
`
then do regular ssh x@y    #-i was not req in my case

**Comment by vikasz1** [comment]
@gitdlnow I used it in Ubuntu 23.10. It worked. I think most people here are from ubuntu only.

**Comment by adithyaamara** [comment]
> In ubuntu 22, in u need to gen keys like: `ssh-keygen -t ed25519 -P "" -f ~/.ssh/id_ed25519` then do regular ssh x@y #-i was not req in my case

@gitdlnow This worked for me. So rsa is not the correct key format to use in this authentication.

**Comment by elmelali** [comment]
> To all those who are here for same issue. Thanks @sidebo #247 solved my problem.
> 
> 1. Run `ssh-keygen` and fill out name of file and empty passphrase.
> 2. Run `ssh -i <File name entered in first step> <docker ssh address>`. Example: `ssh -i ida_rsa ip172-18-0-9-bfe8s7iv9dig00cuhdsg@direct.labs.play-with-docker.com`

Thank you its worke fo me

**Comment by Manav-Khandurie** [comment]
To those using windows + gitbash like me 

Use these steps [works as of Aug 2024]

S-1) Create the key pair by `ssh-keygen -t ed255 -P "" -f ~/.ssh/id_ed255`

S-2) Copy ssh like shown below
![image](https://github.com/user-attachments/assets/b7334179-aea8-48f7-9c1c-2bcc242d30d5)

S-3) Connect using the command
` ssh -i ~/.ssh/id_ed255 ip172-18-0-18-cr3re9iim2rg00c46avg@direct.labs.play-with-docker.com`

![image](https://github.com/user-attachments/assets/c01d3e78-061c-49a5-bd28-b5c41c33d0c5)
