### ISSUE TITLE
Text selection cursor on the screen not align with mouse pointer

### ISSUE THREAD

**Issue by azizasm** [play-with-docker/play-with-docker#239]
When make text selection on the terminal screen ,  the cursors not align with the selection. Instead selection happen at several line above the mouse pointer. This inconvenience especially wanted to copy code in the terminal screen

![iss1](https://user-images.githubusercontent.com/1859108/35909134-976b375c-0c2d-11e8-9f55-267cf0022c43.png)

**Comment by marcosnils** [comment]
It's an xtermjs thing. Nothing we can do from our end :(
