### ISSUE TITLE
Alert when PWD doesn't work

### ISSUE THREAD

**Issue by xetorthio** [play-with-docker/play-with-docker#24]
The idea is to write a simple script that:
1. Creates a new session
2. Creates an instance
3. Closes the session

We will run this script every few minutes on every PWD server. If it works, nothing happens. If it doesn't work, we will send a message to a slack channel.

**Comment by marcosnils** [comment]
I'd love to see something in the /ping endpoint so we don't have to depend on a  "script" to be alerted.

**Comment by marcosnils** [comment]
We've added some basic cloudwatch alarms but they only fix part of the problem. We still need to find a reliable way to make a healthcheck that asserts that an instance can be successfully created

**Comment by marcosnils** [comment]
Should be fixed by #137
