### ISSUE TITLE
Minimize header and left-hand menu

### ISSUE THREAD

**Issue by richardjq** [play-with-docker/play-with-docker#241]
The header (IP, Memory, CPU, SSH, etc.) and left-hand menu (Close Session, New Instance, etc.) take up too much real estate on the screen. 

Enhancement Request:
Please add the ability to minimize these sections of the screen (or just make them smaller by default).

Thanks!

**Comment by marcosnils** [comment]
@richardjq thx for the suggestions. We accepts PR's also :wink:

**Comment by richardjq** [comment]
Would love to take a look, but it requires dep which appears to only care about folks installing on MacOs. No deb packages?

**Comment by marcosnils** [comment]
dep is available on all platforms including windows.

https://github.com/golang/dep/releases

**Comment by marcosnils** [comment]
@richardjq wondering if you're still working on this and if you need any help.

**Comment by richardjq** [comment]
Hi @marcosnils - I haven't had a chance to look at this. Though I did discover that Alt-Enter causes the terminal to go "full screen" so probably not needed...

**Comment by richardjq** [comment]
Sure.
