### ISSUE TITLE
Unable to install Jupyter Data Science notebook

### ISSUE THREAD

**Issue by arpit620** [play-with-docker/play-with-docker#243]
Tried using the following Jupyter notebook:
https://hub.docker.com/r/jupyter/datascience-notebook/

`docker run -it --rm -p 8888:8888 jupyter/datascience-notebook`

But unable to download the image. 
Throws following error:
```
docker: failed to register layer: Error processing tar file(exit status 1): open /opt/conda/lib/python3.6/site-packages/seaborn/tests/__pycache__/test_categorical.cpython-36.pyc: disk quota exceeded.
```

**Comment by vsxen** [comment]
there is no space on the disk .
use this command 

`docker run -it --rm -p 8888:8888 jupyter/minimal-notebook`

**Comment by arpit620** [comment]
I was wondering if there is any generic solution to this. This specific use case has an alternative but let's say we want to download an image which does not have a minimal version, is there any workaround?

I tried setting the "-g" / "--graph" parameters to change the download image location but was facing issues while restarting the daemon. By default, it downloads the image to "/var/lib/docker/" but you can see using "df -h" that there are other places with plenty of space. Is there a way we can specify the location of where we want our image to download in play-with-docker environment?

**Comment by marcosnils** [comment]
> I was wondering if there is any generic solution to this. This specific use case has an alternative but let's say we want to download an image which does not have a minimal version, is there any workaround?

Nope, you can't do anything in this case. `/var/lib/docker` is capped at 5Gb per instance and seems like the jupyter image once uncompressed is bigger than that. We can't increase that limit as it'll have a direct effect on the amount of instances we can launch per session.
