### ISSUE TITLE
traffic not routed properly when containers listen on same port

### ISSUE THREAD

**Issue by riznob** [play-with-docker/play-with-docker#244]
Login to play-with-docker.com. Create 3 instances. Run swarm init on 1. Make the other 2 instances join the swarm. Then run...
docker stack deploy -c example-voting-app-stack.yml voteapp
... using the file found here...
https://github.com/BretFisher/udemy-docker-mastery/blob/master/swarm-stack-1/example-voting-app-stack.yml
Then try to hit the port links in your browser. The traffic is not sent to the correct instance.

**Comment by BretFisher** [comment]
Hi @riznob I just deployed that stack file on PWD and ports 5000, 5001, and 8080 worked as expected by clicking the little link bubbles in the top of the PWD UI, can you try again on a fresh swarm and describe what you're seeing more? How do you know traffic is going to the wrong instance?

**Comment by riznob** [comment]
So weird. I tried this from another computer and it seems to work as expected. This looks like another case of corporate security software protecting me from the evils of thinks working properly. We can close this ticket. Thanks for looking.

**Comment by marcosnils** [comment]
:thumbsup:  thx @bretfisher for helping out.
