### ISSUE TITLE
Registry

### ISSUE THREAD

**Issue by maiermic** [play-with-docker/play-with-docker#245]
I'd like to use a private registry in the playground (with multiple instances). How can I create one?

**Comment by marcosnils** [comment]
Yo should be able to follow https://docs.docker.com/registry/deploying/ in PWD without any problems.

**Comment by maiermic** [comment]
I suppose that I can't use a local registry. Am I right?

**Comment by marcosnils** [comment]
what do you mean by a **local registry**?. An internal registry you have in your company?. Or just spawn a local registry in the playground to push images in there?

**Comment by maiermic** [comment]
https://docs.docker.com/registry/deploying/#run-a-local-registry

**Comment by marcosnils** [comment]
Yes, you can do that. I already mentioned that here: https://github.com/play-with-docker/play-with-docker/issues/245#issuecomment-370244237

**Comment by maiermic** [comment]
I'd like to run multiple instances (machines). I assume that I have to run a registry on one instance and make it accessible from the other instances. That's why I suppose that I need to [run an externally-accessible registry:](https://docs.docker.com/registry/deploying/#run-an-externally-accessible-registry)

> These examples assume the following:
>
> Your registry URL is https://myregistry.domain.com/.
> Your DNS, routing, and firewall settings allow access to the registry’s host on port 443.
> You have already obtained a certificate from a certificate authority (CA).

In case of PWD, I run the registry for example on an instance with IP `192.168.0.8` and like to access the registry on another instance with IP `192.168.0.7`. What URL and certificates should I use? `192.168.0.8` and a self signed certificate?

**Comment by marcosnils** [comment]
> That's why I suppose that I need to run an externally-accessible registry:

not really because the PWD instances live in the same private network. So it's not necessary to configure the registry as external.

BTW, have you seen this? https://training.play-with-docker.com/linux-registry-part1/
and this? https://training.play-with-docker.com/linux-registry-part2/

**Comment by maiermic** [comment]
No, I haven't seen that yet, but I'll have a look at. Thanks.

I tried to run a local registry on node1. I added its IP `192.168.0.8` to `/etc/docker/daemon.json` (like described in [Deploy a plain HTTP registry](https://docs.docker.com/registry/insecure/#deploy-a-plain-http-registry))

```
$ cat /etc/docker/daemon.json
{
    "experimental": true,
    "debug": true,
    "log-level": "info",
    "insecure-registries": ["127.0.0.1", "192.168.0.8"],
    "hosts": ["unix:///var/run/docker.sock", "tcp://0.0.0.0:2375"],
    "tls": false,
    "tlscacert": "",
    "tlscert": "",
    "tlskey": ""
}
```

Then I ran the registry and added an image (like described in [Copy an image from Docker Hub to your registry](https://docs.docker.com/registry/deploying/#copy-an-image-from-docker-hub-to-your-registry)):

```
[node1] (local) root@192.168.0.8 ~
$ docker run -d -p 5000:5000 --restart=always --name registry registry:2
3685de2db57d377dc15b6adf12383ecf49d4942d170101ff4fb56099b91d55a1
[node1] (local) root@192.168.0.8 ~
$ docker pull ubuntu:16.04
16.04: Pulling from library/ubuntu
Digest: sha256:e27e9d7f7f28d67aa9e2d7540bdc2b33254b452ee8e60f388875e5b7d9b2b696
Status: Image is up to date for ubuntu:16.04
[node1] (local) root@192.168.0.8 ~
$ docker tag ubuntu:16.04 localhost:5000/my-ubuntu
[node1] (local) root@192.168.0.8 ~
$ docker push localhost:5000/my-ubuntu
The push refers to repository [localhost:5000/my-ubuntu]
6f4ce6b88849: Pushed
92914665e7f6: Pushed
c98ef191df4b: Pushed
9c7183e0ea88: Pushed
ff986b10a018: Pushed
latest: digest: sha256:7c308c8feb40a2a04a6ef158295727b6163da8708e8f6125ab9571557e857b29 size: 1357
```

Then I added the IP of the registry `192.168.0.8` to `/etc/docker/daemon.json` on node2 and tried to pull the image from the registry:

```
[node2] (local) root@192.168.0.7 ~
$ docker pull 192.168.0.8:5000/my-ubuntu
Using default tag: latest
Error response from daemon: Get https://192.168.0.8:5000/v2/: http: server gave HTTP response to HTTPS client
```

Why does it complain?

**Comment by maiermic** [comment]
Do I need to restart the docker service (like described in [Part 1 - Running a Registry Container in Linux](https://training.play-with-docker.com/linux-registry-part1/)) although they modify `/etc/docker/docker` instead of `/etc/docker/daemon.json`?

```
service docker restart
```

How can I restart the docker service in PWD? Is that even possible?

**Comment by marcosnils** [comment]
Yes. You can kill it with `pkill -9 -f docker` and start it again with `dockerd > /docker.log &`

**Comment by maiermic** [comment]
Restarting docker didn't help. I edited `/etc/docker/daemon.json` on both nodes and restarted docker as you described. Then I ran the the same commands as before, but I still get

```
[node2] (local) root@192.168.0.7 ~
$ docker pull 192.168.0.8:5000/my-ubuntu
Using default tag: latest
Error response from daemon: Get https://192.168.0.8:5000/v2/: http: server gave HTTP response to HTTPS client
```

**Comment by marcosnils** [comment]
If you run `docker info` in node2 can you see the IP I'm insecure registries? Also, try adding the port 192.168.0.8:5000 to the insecure registry flag in the daemon.json file

**Comment by maiermic** [comment]
You're right. I had to add the port. Thanks for your help :1st_place_medal:
