### ISSUE TITLE
Unable to ssh from an ec2 instance

### ISSUE THREAD

**Issue by PrinceDhaliwal** [play-with-docker/play-with-docker#247]
I tried accessing play-with-docker instance using ssh from ec2 instance (can't do from my local machine because of firewall blocking port 22). I checked the outbound rules but all ports are open.

Following error shows up when I try to ssh a pwd machine,
```
Permission denied (publickey).
```

**Comment by marcosnils** [comment]
This is because you need to generate a key locally to connect. Try with `ssh-keygen`

**Comment by audioscavenger** [comment]
> This is because you need to generate a key locally to connect. Try with `ssh-keygen`

thanks but doesn't help

**Comment by aleskxyz** [comment]
I add my public key into the node and authentication goes well but I get "Exit status -1"
Here is the debug log:

```
debug1: Authentication succeeded (publickey).
Authenticated to direct.labs.play-with-docker.com (via proxy).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug1: Entering interactive session.
debug2: callback start
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug2: channel 0: request shell confirm 1
debug2: callback done
debug2: channel 0: open confirm rwindow 2097152 rmax 32768
debug2: channel 0: rcvd ext data 33
Connecting to 13.82.134.94:8022
debug2: channel 0: written 33 to efd 7
debug2: channel 0: rcvd close
debug2: channel 0: output open -> drain
debug2: channel 0: close_read
debug2: channel 0: input open -> closed
debug3: channel 0: will not send data after close
debug2: channel 0: obuf empty
debug2: channel 0: close_write
debug2: channel 0: output drain -> closed
debug2: channel 0: almost dead
debug2: channel 0: gc: notify user
debug2: channel 0: gc: user detached
debug2: channel 0: send close
debug2: channel 0: is dead
debug2: channel 0: garbage collecting
debug1: channel 0: free: client-session, nchannels 1
debug3: channel 0: status: The following connections are open:
  #0 client-session (t4 r0 i3/0 o3/0 fd -1/-1 cc -1)

Connection to direct.labs.play-with-docker.com closed.
Transferred: sent 3548, received 1660 bytes, in 1.9 seconds
Bytes per second: sent 1898.2, received 888.1
debug1: Exit status -1
```

**Comment by marcosnils** [comment]
Which ssh client and version are you using?

**Comment by aleskxyz** [comment]
> Which ssh client and version are you using?

ssh -V
OpenSSH_7.1p2, OpenSSL 1.0.2g  1 Mar 2016

Cygwin on Windows
I also check it on my linux machine but I get the same output

**Comment by marcosnils** [comment]
Are you behind some sort of firewall or nat network somehow? It works ok from here.

**Comment by aleskxyz** [comment]
> Are you behind some sort of firewall or nat network somehow? It works ok from here.

I have found the reason!
I have edited some parameters in sshd_config file, it seems your ssh gateway doesn't like these modifications.

**Comment by marcosnils** [comment]
Nice. Would be nice if you can share here so others don't have the same issue.

**Comment by aleskxyz** [comment]
> Nice. Would be nice if you can share here so others don't have the same issue.

I don't know whats goes on exactly, but I edited "/etc/ssh/sshd_config" in the node to enable root authentication with password and permit port forwarding and reset root password.
Those changes didn't let me to authenticate neither with password nor publickey.
Then I rollback my changes, but no success. It seems those changes had a permanent effect on ssh service.
Finally I test a new node without any modification and everything was ok.
