### ISSUE TITLE
no space left on device.

### ISSUE THREAD

**Issue by GitHub30** [play-with-docker/play-with-docker#249]
Tried using the following command.

https://hub.docker.com/r/jinpengli/tesseract-trainer-docker/

`docker run -d -p 20022:22 --name training_tesseract jinpengli/tesseract-trainer-docker`

But unable to extract the image.
Throws following error:

```bash
$ docker run -d -p 20022:22 --name training_tesseract jinpengli/tesseract-trainer-docker
Unable to find image 'jinpengli/tesseract-trainer-docker:latest' locally
latest: Pulling from jinpengli/tesseract-trainer-docker
af49a5ceb2a5: Pull complete
8f9757b472e7: Pull complete
e931b117db38: Pull complete
47b5e16c0811: Pull complete
9332eaf1a55b: Pull complete
05eab16c35a9: Extracting [==================================================>]   3.81GB/3.81GB
57e233c0ee6f: Download complete
c1e4993c3efb: Download complete
254880901971: Download complete
ab9d04a611ef: Download complete
55a6ec868576: Download complete
84adf2921d87: Download complete
5402028a2c5f: Download complete
32d5a603de0b: Download complete
docker: failed to register layer: Error processing tar file(exit status 1): write /lib/x86_64-linux-gnu/libdns-export.so.162.1.3: no space left on device.
See 'docker run --help'.
```

![screenshot from 2018-03-30 14-39-56](https://user-images.githubusercontent.com/12811398/38125967-5a304a9e-3428-11e8-891a-faecf6385fc3.png)

**Comment by marcosnils** [comment]
Nothing to do here. PWD has a space limit of 5gb for pulling images. Looks like this image after uncompressed is larger than this.

**Comment by giansalex** [comment]
Other option, use https://www.katacoda.com/

**Comment by user18x** [comment]
I think that's not my problem, because i use zammad and first it worked.
After the second test of installation it don't work!

I only use 2 commands of the website:
https://docs.zammad.org/en/latest/contributing/install-docker.html

Why, in first test, zammad worked and in second i get the message "no space left on device" too?
