### ISSUE TITLE
When switching nodes, the shell is not the active cursor

### ISSUE THREAD

**Issue by leandroreox** [play-with-docker/play-with-docker#253]
When moving aroung nodes on the node list, the shell is not the actual cursor and you have to click on the black shell screen in order to start typing on the command line of that particular node. 
I constantly start typing on the nothingness itself till i realize that the shell is not active.  The CLI should be the active cursor when moving trough nodes :)

**Comment by marcosnils** [comment]
Already deployed in PWK.
