### ISSUE TITLE
PWD port forwarding not working today

### ISSUE THREAD

**Issue by hessfr** [play-with-docker/play-with-docker#255]
Hi there,

it seems that the port forwarding in PWD is not working today: when clicking on the generated link for the port, I am getting a 503 (see screenshot below)

Is anybody else facing this issue?

I can still curl from the host itself and get the expected response, mean the container is running as expected.

![image](https://user-images.githubusercontent.com/7280001/39109587-1332a80e-4700-11e8-9131-aedcfa2948cc.png)

Thanks a lot in advance and many thanks for the awesome PWD tool!

**Comment by iyovcheva** [comment]
Hi @hessfr , for me the VM is not accessible at all:

From another machine:
```
$ ping 192.168.0.13
PING 192.168.0.13 (192.168.0.13): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
```

On the VM:
```
$ ping 192.168.0.13
PING 192.168.0.13 (192.168.0.13): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
```

**Comment by marcosnils** [comment]
@hessfr looking at the response headers seems like that 503 is not from PWD. Seems like that's coming from whatever you're running in your instance.

Can you provide more info about your error?

**Comment by hessfr** [comment]
thanks for your replies @iyovcheva , @marcosnils ! It seems to have been an intermittent issue yesterday, because now everything works perfectly fine again. So I will close this ticket
