### ISSUE TITLE
PWD in own infrastructure

### ISSUE THREAD

**Issue by vgerm** [play-with-docker/play-with-docker#257]
Hi,
I followed WIKI as I wanted to try PWD in my own machine:
https://github.com/play-with-docker/play-with-docker/wiki/Deploying-PWD-in-your-own-infrastructure
Container is running and I can see the welcome page, but when I click on "Start" button it shows Error 500
From the container log I am seeing:
`
{"log":"2018/05/02 14:59:56 Listening on port 3000\n","stream":"stderr","time":"2018-05-02T14:59:56.135062468Z"}
{"log":"[negroni] Started GET /users/me\n","stream":"stdout","time":"2018-05-02T15:00:06.547368708Z"}
{"log":"2018/05/02 15:00:06 Cannot read cookie\n","stream":"stderr","time":"2018-05-02T15:00:06.547629891Z"}
{"log":"[negroni] Completed 401 Unauthorized in 491.576µs\n","stream":"stdout","time":"2018-05-02T15:00:06.547713371Z"}
{"log":"[negroni] Started GET /oauth/providers\n","stream":"stdout","time":"2018-05-02T15:00:06.55008984Z"}
{"log":"[negroni] Completed 200 OK in 422.285µs\n","stream":"stdout","time":"2018-05-02T15:00:06.550532879Z"}
{"log":"[negroni] Started POST /\n","stream":"stdout","time":"2018-05-02T15:00:08.877733669Z"}
{"log":"2018/05/02 15:00:08 NewSession id=[bbkt4u25go7g00cusuag]\n","stream":"stderr","time":"2018-05-02T15:00:08.877938865Z"}
{"log":"2018/05/02 15:00:08 Network [bbkt4u25go7g00cusuag] created for session [bbkt4u25go7g00cusuag]\n","stream":"stderr","time":"2018-05-02T15:00:08.887040098Z"}
{"log":"[negroni] Completed 500 Internal Server Error in 10.636055ms\n","stream":"stdout","time":"2018-05-02T15:00:08.888423064Z"}
{"log":"2018/05/02 15:00:08 Connection container to network err [Error response from daemon: No such container: l2]\n","stream":"stderr","time":"2018-05-02T15:00:08.888485987Z"}
{"log":"2018/05/02 15:00:08 Error response from daemon: No such container: l2\n","stream":"stderr","time":"2018-05-02T15:00:08.88850732Z"}
{"log":"2018/05/02 15:00:08 Error response from daemon: No such container: l2\n","stream":"stderr","time":"2018-05-02T15:00:08.88852217Z"}
{"log":"2018/05/02 15:00:08 Error response from daemon: No such container: l2\n","stream":"stderr","time":"2018-05-02T15:00:08.888536003Z"}
`
It tries to find l2, but there is no l2 container...
Can someone help with that?

Thank you in advance!
`
# docker version 
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:09:15 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:13:03 2018
  OS/Arch:	linux/amd64
  Experimental:	false
`
`
# docker image ls
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
franela/play-with-docker   latest              2a4b53926250        5 months ago        21.8MB
franela/dind               overlay2            f52c6d1a446d        6 months ago        527MB
`
`
# docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                                                                 NAMES
d2e3dfc58ce1        franela/play-with-docker:latest   "./play-with-docker …"   15 minutes ago      Up 15 minutes       0.0.0.0:53->53/tcp, 0.0.0.0:53->53/udp, 0.0.0.0:80->3000/tcp, 0.0.0.0:443->3001/tcp   pwd
`
OS : RHEL 7.2

**Comment by marcosnils** [comment]
Instructions are a bit outdated. PR's are welcome.

**Comment by scornelissen85** [comment]
Actually, I'm still trying to get it working. I had the old version, without SSH support and without the l2 container running. But I want to run it with SSH and (I think) with l2. I think that even the Haproxy config is not correct anymore (as it use a HTTP frontend which won't forward SSH). @marcosnils Could you give some hints about how the l2 container should work? How should it know about the running playgrounds? I see pwd has a volume sessions. Should this be available to l2? If I have it running I will create a PR.

**Comment by scornelissen85** [comment]
I have improved the wiki page. But there is no way (as far as I see) to make a PR for wiki's. See https://github.com/scornelissen85/play-with-docker-wiki/blob/master/Deploying-PWD-in-your-own-infrastructure.md

**Comment by n3uz** [comment]
my method to install PWD on my VM ubuntu16.04 and it works
https://github.com/n3uz/play-with-docker/blob/master/ubuntu16.04-deploy-en.md
