### ISSUE TITLE
Connect to a published port from the outside world : difference between PWD and PWK

### ISSUE THREAD

**Issue by yogeek** [play-with-docker/play-with-docker#259]
Hi,

There is a difference in the FAQ between "master" tag and "k8s" tag concerning access to published port :

[master README.md (PWD)](../blob/master/README.md)

```
If you need to access your services from outside, use the following URL pattern http://ip<hyphen-ip>-<session_jd>-<port>.direct.labs.play-with-docker.com (i.e: http://ip-2-135-3-b8ir6vbg5vr00095iil0-8080.direct.labs.play-with-docker.com).
```

[k8s README.md (PWK)](../blob/k8s/README.md)

```
If you need to access your services from outside, use the following URL pattern http://pwd<underscore_ip>-<port>.<host#>.labs.play-with-docker.com (i.e: http://pwd10_2_135_3-80.host3.labs.play-with-docker.com/).
```

1. hyphen or underscore ?
2. 'ip' or 'pwd' prefix ?
3. 'play-with-docker.com' or 'play-with-k8s.com' suffix ?

I am trying to display kubernetes dashboard on PWK as advised in #258 but does not manage to have the right URL... 
Are these differences normal and what is the right configuration to access K8S dashboard after deploying it and starting 'kubectl proxy --port=8080' ?

Thanks

**Comment by marcosnils** [comment]
Try deploying the dashboard service and expose it as either `NodePort` or `LoadBalancer`. You can use this command to dynamically change it in the `kubectl apply`. 
`curl -L -s https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard.yaml  | sed 's/targetPort: 9090/targetPort: 9090\n  type: LoadBalancer/' |    kubectl apply -f -`

That should populate the blue badge at the top so you can click in there

**Comment by rahgadda** [comment]
No blue badge is not getting displayed. Can you please help
![no blue link](https://user-images.githubusercontent.com/13075415/41507178-fe7714b0-724a-11e8-802b-619f54e13522.png)

**Comment by yogeek** [comment]
> Try deploying the dashboard service and expose it as either `NodePort` or `LoadBalancer`. You can use this command to dynamically change it in the `kubectl apply`.
> `curl -L -s https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard.yaml | sed 's/targetPort: 9090/targetPort: 9090\n type: LoadBalancer/' | kubectl apply -f -`
> 
> That should populate the blue badge at the top so you can click in there

@marcosnils This command displays the following error message :
```
[node1 install]$ curl -L -s https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernet
es-dashboard.yaml | sed 's/targetPort: 9090/targetPort: 9090\n type: LoadBalancer/' | kubectl apply -f -
serviceaccount "kubernetes-dashboard" created
role "kubernetes-dashboard-minimal" created
rolebinding "kubernetes-dashboard-minimal" created
deployment "kubernetes-dashboard" created
error: error converting YAML to JSON: yaml: line 13: did not find expected key
```

Do you have a new way to be able to use the dashboard in PWK ?

Plus, I ma sorry but my initial question about the differences between PWD and PWK instructions in README remains unanswered... Can you please explain these differences ?

**Comment by collabnix** [comment]
Quick suggestions:

1. The URL ```https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernet
es-dashboard.yaml ``` is no longer valid. The correct link is:

```kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml```

Also, the default port is 8443 and NOT 9090. Hence you might need to correct it to:

```
sed 's/targetPort: 8443/targetPort: 9090\n type: LoadBalancer/' 
```

Hope it helps

**Comment by pjiocnic** [comment]
This doesn't work as suggested

I see the external IP in pending state and no port shows up on the dashboard

I ran the command on PWK:
```
curl -L -s https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml | sed 's/targetPort: 8443/targetPort: 9090\n  type: LoadBalancer/' | kubectl apply -f -

```
and checked on the service as follows:
```
node1 ~]$ kubectl -n kube-system get service kubernetes-dashboard
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
kubernetes-dashboard   LoadBalancer   10.107.252.233   <pending>     443:31593/TCP   8m


```

**Comment by rahgadda** [comment]
We are still not able to view blue badge. Please help

**Comment by marcosnils** [comment]
@rahgadda this documentation is a bit old. We'll try to fix it :)

**Comment by sharvana85** [comment]
@marcosnils - I also did not get the Blue Badge to access the K8 Dashboard from external IP, no external IP is assigned to me. also wen i run "kubectl proxy --port=8443" it is running for long time without exiting. Appreciate your help and guidance

**Comment by rBarreraAeolabs** [comment]
how do they connect from abroad??
