### ISSUE TITLE
Out of capacity

### ISSUE THREAD

**Issue by strarsis** [play-with-docker/play-with-docker#264]
Some days ago I tried to start the sample WordPress stack (https://labs.play-with-docker.com/?stack=/wordpress/latest/stack.yml#), but it failed with this notice:
````
We are really sorry but we are out of capacity and cannot create your session at the moment. Please try again later.
````
The issue still persists.

**Comment by marcosnils** [comment]
Just tried this and it works for me. Try again.

**Comment by strarsis** [comment]
@marcosnils: Yes, I tried again and now it works for me, too.

**Comment by SimranSinghi** [comment]
This issue is still there

**Comment by marcosnils** [comment]
> This issue is still there

Just tried this and it works fine to me.

**Comment by Mohamed-Zakaria333** [comment]
We are really sorry but we are out of capacity and cannot create your session at the moment. Please try again later.
same problem!!!

**Comment by akshayjain-tmdc** [comment]
Anyone up with a solution to this?
