### ISSUE TITLE
How to access the dashboard externally

### ISSUE THREAD

**Issue by neliel123** [play-with-docker/play-with-docker#267]
I posted this question https://stackoverflow.com/questions/50511393/kubernetes-play-dashboard-access-from-outside

I cant seem to find a document on how to access it correctly?

Any hints?

I tried everything that I have known so far but I still am struggling with this.

**Comment by marcosnils** [comment]
Just replied in SO. If you hitting against the wall you can contact me in the #dockercommunity slack channel (https://community.docker.com/registrations/groups/4316)
