### ISSUE TITLE
Authenticating between GitHub or Docker Hub

### ISSUE THREAD

**Issue by rcjsuen** [play-with-docker/play-with-docker#270]
Hi, thanks as always for creating this wonderful project!

Today I opened the PWK site for the first time. Unlike the PWD site, I can authenticate with either `github` or `docker`. The PWD site only lets me use `docker`.

1. Why should I authenticate with one over the other?
2. Should PWD also support authentication via `github`?

**Comment by marcosnils** [comment]
> Hi, thanks as always for creating this wonderful project!

Glad you like it, we're always looking for new ways to improve it and make it easier for the community to learn and experiment with new things.

> Why should I authenticate with one over the other?

There's really no difference, we just provide different alternatives to avoid forcing users to create an account.

> Should PWD also support authentication via github?

PWD is currently sponsored (infrastructure costs) by Docker.Inc. It was their decision to only allow Dockerhub login in that site. 

I'll close this issue as there's not too much we can do from our end.
