### ISSUE TITLE
play-with-docker.com session expires and closes after 4 minutes

### ISSUE THREAD

**Issue by manios** [play-with-docker/play-with-docker#271]
During this week I am trying every day to test docker image creation using [https://labs.play-with-docker.com/](https://labs.play-with-docker.com/). However when I try to create the image, the session expires after 4 minutes. In the meantime, the page claims that the session it will end after 4 hours.

### Environment:

|Key|Value|
|--|--|
Operating system | Windows NT 10.0
Javascript enabled | Yes
Cookies enabled | Yes
Flash version | Not installed
Java version | Not installed
Websockets supported | Yes
Browser size | 1252 x 549
Screen size | 1280 x 720 (Retina)
Color depth | 24 bit
Timezone|Europe/Athens
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

### Steps to reproduce:

Create a new environment, add a new instance and then run:

```shell
git clone https://github.com/rsyslog/rsyslog-docker \
&& cp rsyslog-docker/dev_env/common/setup-projects.sh rsyslog-docker/dev_env/ubuntu/base/16.04/ \
&& sed -i 's/--enable-mmgrok//g' rsyslog-docker/dev_env/ubuntu/base/16.04/Dockerfile \
&& sed -i 's/RUN \.\/setup-system.sh/RUN .\/setup-system.sh \&\& .\/setup-projects.sh/g' rsyslog-docker/dev_env/ubuntu/base/16.04/Dockerfile \
&& echo "make install" | tee -a rsyslog-docker/dev_env/ubuntu/base/16.04/setup-projects.sh \
&& cd rsyslog-docker/dev_env/ubuntu/base/16.04 \
&& docker build -t mylocal/rsyslog .
```

**Comment by hexed** [comment]
Does the same to me

**Comment by marcosnils** [comment]
Should be fixed

**Comment by shrn01** [comment]
Same thing happened with me today !

**Comment by marcosnils** [comment]
> Same thing happened with me today !

what are you running? There are some workloads in the environment that are not allowed and we terminate the session for those

**Comment by shrn01** [comment]
I just tried to clone a github repo and run the dockerfile and it just said session was terminated. it was in pip install phase, maybe that hit the workload limit or something?

**Comment by marcosnils** [comment]
can you share exactly what you were trying so I can test?

**Comment by shrn01** [comment]
I cloned this repository https://github.com/sherlock-project/sherlock

`cd sherlock`

Then ran `python3 -m pip install -r requirements.txt`

This operation did not complete, and the playground timed out.

**Comment by marcosnils** [comment]
Hi, programs like sherlock or any sort of scanner are not allowed. The purpose of the environment is to learn docker and / or try different examples, running these types of programs for your own benefit is not allowed.
