### ISSUE TITLE
qemu-user not detecting binary format

### ISSUE THREAD

**Issue by 1138-4EB** [play-with-docker/play-with-docker#276]
The test script in [1138-4EB/test-qemu](https://github.com/1138-4EB/test-qemu/blob/master/run.sh) statically cross-compiles a Hello World C program inside a `ubuntu:18.04` container and then executes it in a different container with `qemu-user`. It works as expected in Ubuntu and Fedora hosts (x86_64), and produces the following last two lines:

```
Hello world!
Hello world!
```

However, in play-with-docker, this is the result:

```
bash: ./main: cannot execute binary file: Exec format error
Hello world!
```

The difference between the two calls to the executable is:

```
./main; \
qemu-aarch64 ./main
```

I'd like prepending `qemu-aarch64` not to be required, because this is just a stripped down version of a problem produced when trying to cross-compile `libelf` (where adding it is not so straighforward).

Is there any additional tweak or argument required in play-with-docker for it work?

Just in case it might be relevant, the same error occurs in travis-ci: https://travis-ci.com/1138-4EB/test-qemu/builds/77530556

**Comment by marcosnils** [comment]
I believe because binfmt_misc needs to be mounted in order to work and it's not there in PWD. Can you run `mount` in the container where it works to see what you're getting?

**Comment by 1138-4EB** [comment]
This is what I get if I run `mount` just after `./main; qemu-aarch64 ./main`:

```
Hello world!
Hello world!
overlay on / type overlay (rw,relatime,seclabel,lowerdir=/var/lib/docker/overlay2/l/BIC3SGB3IXNF56EPVTCAJXVPWI:/var/lib/docker/overlay2/l/RVBCHSLESVHF42HY3EVX6LHTHZ:/var/lib/docker/overlay2/l/SNG2HDOZG6HVJ2NFZQD7EYB6IK:/var/lib/docker/overlay2/l/DG3RBKLMOIWN2ZNBTQSN6LPP4G:/var/lib/docker/overlay2/l/EWUQQKY7SVFGCN2LYIJC32FP7Z:/var/lib/docker/overlay2/l/GZDT3DZGFE5DMRPYQ244JB4JTH,upperdir=/var/lib/docker/overlay2/21853927a700a669f4a02ebb2b810dbbe63e36e547ebfa9c8fb0e642b15851a5/diff,workdir=/var/lib/docker/overlay2/21853927a700a669f4a02ebb2b810dbbe63e36e547ebfa9c8fb0e642b15851a5/work)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,seclabel,size=65536k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=666)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime,seclabel)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,relatime,seclabel,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,cpuset)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,hugetlb)
cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,perf_event)
cgroup on /sys/fs/cgroup/pids type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,pids)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,cpu,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,memory)
cgroup on /sys/fs/cgroup/freezer type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,freezer)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,net_cls,net_prio)
cgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,devices)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime,seclabel)
/dev/mapper/VolGroup-lv_root on /src type ext4 (rw,relatime,seclabel)
/dev/mapper/VolGroup-lv_root on /etc/resolv.conf type ext4 (rw,relatime,seclabel)
/dev/mapper/VolGroup-lv_root on /etc/hostname type ext4 (rw,relatime,seclabel)
/dev/mapper/VolGroup-lv_root on /etc/hosts type ext4 (rw,relatime,seclabel)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,size=65536k)
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=666)
proc on /proc/asound type proc (ro,relatime)
proc on /proc/bus type proc (ro,relatime)
proc on /proc/fs type proc (ro,relatime)
proc on /proc/irq type proc (ro,relatime)
proc on /proc/sys type proc (ro,relatime)
proc on /proc/sysrq-trigger type proc (ro,relatime)
tmpfs on /proc/kcore type tmpfs (rw,nosuid,seclabel,size=65536k,mode=755)
tmpfs on /proc/keys type tmpfs (rw,nosuid,seclabel,size=65536k,mode=755)
tmpfs on /proc/latency_stats type tmpfs (rw,nosuid,seclabel,size=65536k,mode=755)
tmpfs on /proc/timer_list type tmpfs (rw,nosuid,seclabel,size=65536k,mode=755)
tmpfs on /proc/sched_debug type tmpfs (rw,nosuid,seclabel,size=65536k,mode=755)
tmpfs on /proc/scsi type tmpfs (ro,relatime,seclabel)
tmpfs on /sys/firmware type tmpfs (ro,relatime,seclabel)
```

This is a Fedora 28 host.

**Comment by marcosnils** [comment]
can you please run the following also:

`findmnt binfmt_misc`
`ls -al /proc/sys/fs/binfmt_misc`

**Comment by marcosnils** [comment]
There's a missing "c" in the misc word

**Comment by 1138-4EB** [comment]
My bad. Sorry. This is it:

```
total 0
dr-xr-xr-x. 2 root root 0 Jun 28 01:38 .
dr-xr-xr-x. 1 root root 0 Jun 28 01:38 ..
```

The directory exists, but it is empty.

**Comment by marcosnils** [comment]
Do you have qemu installed in your system?

**Comment by 1138-4EB** [comment]
I had when I tried this yesterday. However, now I removed all qemu packages (`sudo dnf remove qemu*`) and executed it again. It is still working ok. Yet, these are the outputs I get on the host:

```
findmnt binfmt_misc
TARGET                   SOURCE      FSTYPE      OPTIONS
/proc/sys/fs/binfmt_misc binfmt_misc binfmt_misc rw,relatime

ls -al /proc/sys/fs/binfmt_misc
total 0
drwxr-xr-x. 2 root root 0 Jun 28 11:08 .
dr-xr-xr-x. 1 root root 0 Jun 28 12:08 ..
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-aarch64
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-alpha
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-arm
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-armeb
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-cris
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-m68k
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-microblaze
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-microblazeel
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-mips
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-mips64
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-mips64el
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-mipsel
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-ppc
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-ppc64
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-ppc64abi32
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-ppc64le
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-s390x
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-sh4
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-sh4eb
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-sparc
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-sparc32plus
-rw-r--r--. 1 root root 0 Jun 28 11:08 qemu-sparc64
--w-------. 1 root root 0 Jun 28 11:08 register
-rw-r--r--. 1 root root 0 Jun 28 11:08 status
```

I am going to restart the system and try it again, in order to check if these registered formats are an artifact.

**Comment by marcosnils** [comment]
I believe that's why. Because in your system you have a bunch a of binfmt
stuff that qemu probably registered which are not present in PWD servers.

**Comment by 1138-4EB** [comment]
Indeed, after a restart these are the outputs in my hots:

```
$ findmnt binfmt_misc
TARGET                   SOURCE      FSTYPE      OPTIONS
/proc/sys/fs/binfmt_misc binfmt_misc binfmt_misc rw,relatime

$ ls -al /proc/sys/fs/binfmt_misc
total 0
drwxr-xr-x. 2 root root 0 Jun 28 15:52 .
dr-xr-xr-x. 1 root root 0 Jun 28  2018 ..
--w-------. 1 root root 0 Jun 28 15:52 register
-rw-r--r--. 1 root root 0 Jun 28 15:52 status
```

And the script fails now, just as it does in PWD.

Thanks a lot for helping me narrow it down. I'll try a couple of approaches to work around it:

- Use a modified version of the 'register' image in https://github.com/multiarch/qemu-user-static, to register qemu-user-* formats instead of qemu-user-*-static ones.
- Use just some of the scripts from there instead of the image itself.

I'll get back and close this issue after I try those. Anyway, feel free to close it earlier, as the original question is answered from the PWD point of view.

**Comment by 1138-4EB** [comment]
- Is it possible to execute PWD in ones own infraestructure with less restrictive permissions?
- Does it make any sense to execute `register.sh` in the hosts where PWD is going to be running, but before PWD is actually executed? I understand that it is not sensible to allow any user to tinker with kernel level stuff. However, this is something that can be provided as-is, and let the user know which interpreters should he/she put in the images for it to work.

**Comment by marcosnils** [comment]
> Is it possible to execute PWD in ones own infraestructure with less restrictive permissions?

yes



> Does it make any sense to execute register.sh in the hosts where PWD is going to be running, but before PWD is actually executed?

No, we're not going to do it in PWD servers.

**Comment by bam80** [comment]
> No, we're not going to do it in PWD servers.

Could I rise this problem again?
Registering binfmt interpreters on PWD host should be safe as it all happens in the container anyway: 
https://lwn.net/Articles/679500/

Adding ability to run foreign executables could be valuable addition:
https://gitlab.manjaro.org/manjaro-arm/applications/manjaro-arm-tools/-/issues/47
