### ISSUE TITLE
setup Https in play-with-docker using letsencrypt ?

### ISSUE THREAD

**Issue by zysm** [play-with-docker/play-with-docker#278]
Most common way for https is using letsencrypt but seems initiate a docker container to listen to 443 port  not successful .
also   letsencrypt require full domain address to verify host. 
any suggested solution for this  ? 

		$ sudo docker run -it --rm \
		> -v /docker-volumes/etc/letsencrypt:/etc/letsencrypt \
		> -v /docker-volumes/var/lib/letsencrypt:/var/lib/letsencrypt \
		> -v /docker/letsencrypt-docker-nginx/src/letsencrypt/letsencrypt-site:/data/letsencrypt \
		> -v "/docker-volumes/var/log/letsencrypt:/var/log/letsencrypt" \
		> certbot/certbot \
		> certonly --webroot \
		> --register-unsafely-without-email --agree-tos \
		> --webroot-path=/data/letsencrypt \
		> --staging \
		> -d ip172-18-0-11-bd2nljts2ti000bg8h9g-80.direct.labs.play-with-docker.com
		Saving debug log to /var/log/letsencrypt/letsencrypt.log
		Plugins selected: Authenticator webroot, Installer None
		Obtaining a new certificate
		Performing the following challenges:
		http-01 challenge for ip172-18-0-11-bd2nljts2ti000bg8h9g-80.direct.labs.play-with-docker.com
		Using the webroot path /data/letsencrypt for all unmatched domains.
		Waiting for verification...
		Cleaning up challenges
		Failed authorization procedure. ip172-18-0-11-bd2nljts2ti000bg8h9g-80.direct.labs.play-with-docker.com (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://ip172-18-0-11-bd2nljts2ti000bg8h9g-80.direct.labs.play-with-docker.com/.well-known/acme-challenge/5buceCPogf7T64hWQCG4B6jLRJTw616ANx052NudyXs: Connection refused

		IMPORTANT NOTES:
		 - The following errors were reported by the server:

		   Domain:
		   ip172-18-0-11-bd2nljts2ti000bg8h9g-80.direct.labs.play-with-docker.com
		   Type:   connection
		   Detail: Fetching
		   http://ip172-18-0-11-bd2nljts2ti000bg8h9g-80.direct.labs.play-with-docker.com/.well-known/acme-challenge/5buceCPogf7T64hWQCG4B6jLRJTw616ANx052NudyXs:
		   Connection refused

		   To fix these errors, please make sure that your domain name was
		   entered correctly and the DNS A/AAAA record(s) for that domain
		   contain(s) the right IP address. Additionally, please check that
		   your computer has a publicly routable IP address and that no
		   firewalls are preventing the server from communicating with the
		   client. If you're using the webroot plugin, you should also verify
		   that you are serving files from the webroot path you provided.

**Comment by marcosnils** [comment]
Not a PWD issue.
