### ISSUE TITLE
Request to increase Disk space

### ISSUE THREAD

**Issue by zysm** [play-with-docker/play-with-docker#281]
Humble request  to PDW team to increase disk space so that docker image > 5Gb be able to be installed. 

Instead of now allowing to create multiple PWD instance , why not allow one instance with more combined disk space ?  

Appreciate if this can be considered as many docker images especially data science related docker images  e.g : cloudera, hadoop, and jupyter-spark could not be install into  PDW because of images size after been deflated exceeded 5GB.

**Comment by marcosnils** [comment]
@ManoMarks ?.
