### ISSUE TITLE
POST commands to container in DIND not supported?

### ISSUE THREAD

**Issue by eshnil2000** [play-with-docker/play-with-docker#283]
On the PWD site, i setup the following Ethereum JSON RPC server (https://github.com/ethereum/wiki/wiki/JSON-RPC#web3_clientversion), here are the commands I used to install:
`apk add --update nodejs`
`npm install ganache-core -g`
`sudo npm install ganache-core -g`
`sudo npm install ganache-cli -g`
`docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest`
At this point, the port shows up as expected. My instance ID:
https://labs.play-with-docker.com/p/bdeaqvkhlgn000f8q2b0#bdeaqvkh_bdear0khlgn000f8q2bg

I try to curl POST request:
`
curl -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}'
 http://ip172-18-0-3-bdeaqvkhlgn000f8q2b0-8545.direct.labs.play-with-docker.com
`
I don't get the expected response, instead I get:
`
curl: (52) Empty reply from server
`
When I use the same commands against a Docker container on my local machine or AWS instance [not in PWD infrastructure], the POST command works fine and returns results as expected:
`
{
  "id":67,
  "jsonrpc":"2.0",
  "result": "Mist/v0.9.3/darwin/go1.4.1"
}
`
On the same PWD instance, I can launch an nginx container:
`
docker run -d -p 8080:80 nginx
`
and CURL successfully with a PUT request.

Are POST commands routed into the PWD infrastructure? 
I'm assuming yes, but wanted to check if there are any special considerations that I'm missing.

**Comment by marcosnils** [comment]
Sorry, but we don't provide support for custom projects. We just can't allocate the time to test them
