### ISSUE TITLE
Unable to SSH into PWD Instance

### ISSUE THREAD

**Issue by sam340** [play-with-docker/play-with-docker#285]
Hi Everyone,

I'm finding difficulty to SSH my PWD Instances.
Refered Thread #196
 https://medium.com/@marcosnils/pwd-ssh-c12080ea11d1
But I still could not connect.

I have tried with,
ssh ip###-##-#-##-#####@direct.labs.play-with-docker.com    (whole string copied from ssh field as it is).
ssh -p 1022 ip###-##-#-##-#####@direct.labs.play-with-docker.com  (same string plus port number).
ssh -p 1022 ###-##-#-##-#####@direct.labs.play-with-docker.com   (same string but removed the word ip from string).

I have also copied the private key using the editor option and paste it into .ssh folder with file name id_rsa without any extension.But no luck.
Everytime when i try to ssh I get a prompt for **paraphrase** then, I'm getting error as **Permission denied(public key).**
I am using windows 7 ,Git Bash terminal.
@marcosnils and others could you'll please guide me where am i going wrong.

**Comment by marcosnils** [comment]
@sam340 you don't need to copy the PWD private key. Just run `ssh-keygen` from your git bash terminal and it should generate a key for you. After that you should be able to access without issues.

**Comment by marcosnils** [comment]
> But in order to connect to the PWD Instance i need the PWD Instance private key on my client ssh folder right.But still the problem will persist if i guessed it right....

no, that's not correct. You just need a key in your machine and that's it.

**Comment by 1138-4EB** [comment]
@sam340, since you are in Git Bash, are you using `eval $(ssh-agent -s)` prior to `ssh-add`? https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#adding-your-ssh-key-to-the-ssh-agent

**Comment by marcosnils** [comment]
> @sam340, since you are in Git Bash, are you using eval $(ssh-agent -s) prior to ssh-add?

I'm not a windows user.

**Comment by sam340** [comment]
@marcosnils  Thnx mate it worked like charm. Just one request could you please help me how can i connect it using putty.

**Comment by marcosnils** [comment]
> @marcosnils Thnx mate it worked like charm. Just one request could you please help me how can i connect it using putty.

IDK, I haven't tried but it should be pretty straightforward. Can you please close this?

**Comment by sam340** [comment]
Yup sure.

**Comment by UmamaheshMaxwell** [comment]
> ssh-keygen

This did the trick !!! Thank you [marcosnils](https://github.com/marcosnils)

**Comment by thanhsang2606** [comment]
> @sam340 you don't need to copy the PWD private key. Just run `ssh-keygen` from your git bash terminal and it should generate a key for you. After that you should be able to access without issues.

thanks guy, it's work to me.
