### ISSUE TITLE
HTTPS Setup Documentation

### ISSUE THREAD

**Issue by IantheFlyingHawaiian** [play-with-docker/play-with-docker#287]
Hi @marcosnils , do you guys have documentation on how to properly setup SSL (https) for Play With Docker?  Similar to this website  play-with-docker.com --> https://labs.play-with-docker.com/

**Comment by marcosnils** [comment]
PWD supports let's encrypt by default. We don't have any instructions or provide any support about how to set it up but following the code should be straightforward

https://github.com/play-with-docker/play-with-docker/blob/b363a35a61f60f7908b8a31e8c3dcaba54183f61/handlers/bootstrap.go#L132
