### ISSUE TITLE
Error connecting WebSocket

### ISSUE THREAD

**Issue by thobalose** [play-with-docker/play-with-docker#288]
I am trying to get [this stack](https://github.com/COMBAT-TB/combatb-db/blob/dev/stack.yml) up and running on PWD but I keep hitting ```can’t establish a connection to the server at ws://ip172-18-0-43-bdqnnsbt07tg00bkd2v0-7474.direct.labs.play-with-docker.com:7687/```. However, port: `7687` is exposed.

`curl 0.0.0.0:7687` results in `"not a WebSocket handshake request: missing upgrade"`.

Not so sure if it's related to https://github.com/play-with-docker/play-with-docker/issues/10 or not.

**Comment by marcosnils** [comment]
We don't provide support for third party stacks. PWD has support for redirecting WS.
