### ISSUE TITLE
Instance subnet

### ISSUE THREAD

**Issue by orangeswim** [play-with-docker/play-with-docker#289]
How do I change the instance subnet? I've looked through the code and have no luck on where it is being set.

For example each session will generate a unique 10.0.... subnet when deployed on your own infrastructure. The PWD website has it so that it is  192.168....
On my own infrastructure it is 10.0 and in the test files they also use 10.0...
I've changed the bip on the docker host and on the franela/dind image, and they both don't address the issue. 

It would also be great if it can be customized on the api.go cli

**Comment by marcosnils** [comment]
The PWD site is using an enterprise PWD version which is sold to customers which allows subnet change amongst other features. It's not possible to change the subnet in the OS version as-is today. PR's are welcome though.
