### ISSUE TITLE
Session get closed while building images

### ISSUE THREAD

**Issue by couraudt** [play-with-docker/play-with-docker#290]
Hello,

When I try to build a simple Docker image, the session get closed automatically, even if it's the only thing I've done just after opening a new session. 

Here's a simple `Dockerfile` I use to make a build with the command `docker build -t test .`:
```
FROM ubuntu
RUN apt update && apt install -y firefox

ENTRYPOINT ["id"]
```

Thank you

**Comment by marcosnils** [comment]
Yes, we don't allow some things in PWD. When that happens the session gets closed automatically

**Comment by marcosnils** [comment]
Yes, we don't allow some things in PWD. When that happens the session gets closed automatically
