### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by elliottn** [play-with-docker/play-with-docker#292]
Just running section 3 on https://training.play-with-docker.com/docker-networking-hol/ and I'm getting:
`[node2] (local) root@192.168.0.42 ~
$ ssh ip172-18-0-16-be0ls3jt07tg00d0srmg@direct.labs.play-with-docker.com
Connection to direct.labs.play-with-docker.com closed by remote host.
Connection to direct.labs.play-with-docker.com closed.
[node2] (local) root@192.168.0.42 ~
$ Permission denied (publickey).`

while trying to join worker node to the manager

Got it on labs.play-with-docker.com as well while trying to ssh into an instance from local machine.
`$ ssh ip172-18-0-16-be0ls3jt07tg00d0srmg@direct.labs.play-with-docker.com
Permission denied (publickey).`

**Comment by marcosnils** [comment]
Check other issues. This has been discussed in the past.
