### ISSUE TITLE
Link to port not showing up

### ISSUE THREAD

**Issue by hoschi-it** [play-with-docker/play-with-docker#293]
# What I did
- [Open "Play with docker" webapp](https://labs.play-with-docker.com/)
- pressed "Start"
- added new instance
```bash
$ docker run -p 8080:80 -d nginx
```

# What happend
- container ID at stdout
- container runs in background
- port 8080 is mapped to local 80
- ***no link to port pops up at the top***

# Question
- How can I browse the webpage? Is there some specific URL-pattern or something similar?

**Comment by joaquinito01** [comment]
Hello,
It has been the PWD, but it should be resolved.
Greetings. :)
