### ISSUE TITLE
How can I run https://labs.play-with-k8s.com locally ?

### ISSUE THREAD

**Issue by mydockergit** [play-with-docker/play-with-docker#295]
I really like https://labs.play-with-k8s.com but I want to be able to use it without the timers.

How can I install it on a vmware machine to have a web like https://labs.play-with-k8s.com ?

I read the readme file but it just show how to install the training site and I want to have the site with the option to run Kubernetes environment like it appears in https://labs.play-with-k8s.com.

**Comment by joaquinito01** [comment]
Yes.

**Comment by marcosnils** [comment]
> I read the readme file but it just show how to install the training site and I want to have the site with the option to run Kubernetes environment like it appears in https://labs.play-with-k8s.com.

It's the same instructions as the readme. The only difference is that you need to run the `franela/k8s` image instead of the `franela/dind`

**Comment by joaquinito01** [comment]
What do you mean???

**Comment by joaquinito01** [comment]
You cannot use our services. :(

**Comment by xinity** [comment]
@mydockergit you must run the container in privileged mode 😉
`docker run --rm - - privileged -it franela/k8s`

As it needs to mount protected resources from the host
