### ISSUE TITLE
Driver not detected

### ISSUE THREAD

**Issue by anysz** [play-with-docker/play-with-docker#302]
![nah](https://user-images.githubusercontent.com/26342994/47702824-b3647600-dc50-11e8-8419-eab94ff56134.jpg)
After i download the release, i extracted them on temp folder then move the binary to `/usr/bin` to make it in PATH
But why the `docker-machine -d pwd node` is not detect the driver?

**Comment by marcosnils** [comment]
docker-machine is not under active development anymore. This plugin is no longer supported.
