### ISSUE TITLE
AWS - Load Balanced and scalable

### ISSUE THREAD

**Issue by IantheFlyingHawaiian** [play-with-docker/play-with-docker#306]
Is there any documentation on explaining how to setup PWD within a scaling AWS load balanced environment that uses multiple ec2 instances?

**Comment by marcosnils** [comment]
Nope there isn't. We've done it but only for customers that requested that specific features and were willing to pay for it.

**Comment by IantheFlyingHawaiian** [comment]
If you don't mind me asking, did you guys set it up the docker swarm in docker ucp on AWS? (This project is really amazing btw)

**Comment by marcosnils** [comment]
> If you don't mind me asking, did you guys set it up the docker swarm in docker ucp on AWS? (This project is really amazing btw).

You mean running docker enterprise in PWD using swarm?. Yes, we've done that.

**Comment by IantheFlyingHawaiian** [comment]
Wow that's awesome.

I was just wondering how to setup my own private PWD that's load balanced across two instances (It's a small environment) running PWD. My issue is when I get redirected to the pwd sessions (the sessions work), but I can't always go to the subdomains (i.e. https://ip10-0-1-4-bfhk00opi0200a8adhg0-8080.direct.pwd.us.lmco.com/) because the load balancer sends me to the other instance. 

Do you have any tips of how to deal with?  Maybe use haproxy other than the AWS load balancer to do the load balancing?
