### ISSUE TITLE
Subdomains no longer working

### ISSUE THREAD

**Issue by lmakarov** [play-with-docker/play-with-docker#308]
Subdomains used to work (tried it last time a few month ago), but don't work now.

Example:

http://sub1.ip172-18-0-11-bfjs2m2v9dig00f0q03g-80.direct.labs.play-with-docker.com
http://sub2.sub1.ip172-18-0-11-bfjs2m2v9dig00f0q03g-80.direct.labs.play-with-docker.com

Getting `Empty reply from server` error.

Besides that, I noticed routing is unreliable in general.
I've been having issues today with requests not routed even without a subdomain:

```
docker run -p 80:80 nginx
```

![image](https://user-images.githubusercontent.com/1205005/48309687-28c72500-e534-11e8-84fd-0a28a22c6344.png)

At first the Nginx Welcom page loaded, but then stopped working after a few minutes and was giving the `Empty reply from server` error.

**Comment by marcosnils** [comment]
> Besides that, I noticed routing is unreliable in general.
> I've been having issues today with requests not routed even without a subdomain:
Just tried this and seems to work for me. 

Sub-domains should also work. How are you trying that?

**Comment by marcosnils** [comment]
> Sub-domains should also work. How are you trying that?

Just tried this as well and it also works.

**Comment by lmakarov** [comment]
@marcosnils I tried again today and yes - it worked. But... you can see the screenshot from above, which shows that it did not when I was previously testing.

I will create a separate ticket for routing not being reliable and record a screencast next time I run into this.

**Comment by marcosnils** [comment]
>I will create a separate ticket for routing not being reliable and record a screencast next time I run into this.

That'd be awesome!. Thx!.
