### ISSUE TITLE
Running PWD (on own machine) for local workshops/trainings without authentication

### ISSUE THREAD

**Issue by m4r10k** [play-with-docker/play-with-docker#312]
Hello!

I would like to be able to run a local PWD setup on my eg laptop for example, to host the PWD environment locally during workshops or meetups easily. I've read the https://github.com/play-with-docker/play-with-docker/wiki/Deploying-PWD-in-your-own-infrastructure page, the login page comes up, **but how can I disable the authentication?**

Such setups would be running in a trustful environment on a local network for a limited amount of time. It would be really helpful for the people to just enter my laptops (the trainers) IP address and start working immediately without creating accounts and of course without external dependencies like the online PWD, witch is great though! 

Thanks!

**Comment by marcosnils** [comment]
The version of PWD in this repo doesn't include any authentication at all. Where did you see that?
