### ISSUE TITLE
how to restart docker service ? 

### ISSUE THREAD

**Issue by dipanjanmukherjee83** [play-with-docker/play-with-docker#314]
I have installed openrc but still I am not able to restart docker service. Due to some testing I have to restart the docker service to take the change effect.

$ apk add openrc
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/1) Installing openrc (0.35.5-r4)
Executing openrc-0.35.5-r4.post-install
Executing busybox-1.28.4-r1.trigger
OK: 304 MiB in 111 packages
[manager1] (local) root@192.168.0.18 ~
$ which service
/sbin/service
[manager1] (local) root@192.168.0.18 ~
$ service docker status
 * service: service `docker' does not exist
[manager1] (local) root@192.168.0.18 ~

**Comment by marcosnils** [comment]
You can restart the daemon by killing docker with `pkill -9 -f dockerd` and starting it again with `nohup dockerd > /docker.log &`

**Comment by dipanjanmukherjee83** [comment]
Thanks it is working.
