### ISSUE TITLE
Can't connect to the Websphere administrative console

### ISSUE THREAD

**Issue by mzambrini** [play-with-docker/play-with-docker#315]
**Sorry for my terrible english!**

On a fresh session on https://labs.play-with-docker.com/ I want to create a WebSphere container (version 9.x) with following command:
```term
   git clone https://github.com/mzambrini/tutorial-websphere.git \
   && cd tutorial-websphere \
   && git checkout tags/v1.0.0 \
   && docker build -t my-was9-app -f Dockerfile9 . \
   && docker run --name was9 -p9060:9060 -p9080:9080 -d my-was9-app 
```
After the server has started, I can't connect to the administrative console on port 9060 (security is disabled) with context root  */ibm/console* via external IP like
```
http://ip172-18-0-34-bg78ad43uhdg008486ag-9060.direct.labs.play-with-docker.com/ibm/console
```

If, however, I execute the following command
```term
wget -O index.html http://localhost:9060/ibm/console
```
I get a consistent result.

I can connect to the deployed application at IP like
```
http://ip172-18-0-92-bg78fv8v0j3g00fv3p3g-9080.direct.labs.play-with-docker.com/SampleAjax/simpleTextDisplay.faces
```

Strangely, if I run the build of Webssphere container version 8.5.5.x, instead, with command
```term
   docker build -t my-was8-app -f Dockerfile8 .
```
after creating the container, everything works!

Thanks for your attention!

**Comment by marcosnils** [comment]
try adding `9060` in the end of the admin console url. i.e:
http://<span></span>ip172-18-0-34-bg78ad43uhdg008486ag-9060.direct.labs.play-with-docker.com<b>:9060</b>/ibm/console 

That should make it work
