### ISSUE TITLE
Websocket connection blocked

### ISSUE THREAD

**Issue by 1138-4EB** [play-with-docker/play-with-docker#319]
The following commands start a [GTK+ Broadway](https://developer.gnome.org/gtk3/stable/gtk-broadway.html) HTML display server on port `8085`:

``` bash
$ curl -fsSL https://raw.githubusercontent.com/mviereck/x11docker/master/x11docker | bash -s -- --update-master
$ x11docker -it -- -p=8085:8085 -e BROADWAY=5 -- ghdl/ext:gtk-ide bash
```

The server is properly initialized and the button corresponding to the port is shown at the top middle part of play-with-docker's interface. When browsing it, the HTML content is properly loaded, but the following error is shown in the console:

``` bash
Firefox can't establish a connection to the server at ws://ip172-18-0-37-bh9r2rr0mkfg00b1rr40.direct.labs.play-with-docker.com:8085/socket.
```

Is there some setup on play-with-docker that disables/limits websockets? Or might it be a bug in Broadway?

> NOTE: The same commands work on Win10 host.

**Comment by marcosnils** [comment]
Websockets work in PWD. It should be something else.
