### ISSUE TITLE
using docker-compose instead of docker stack deploy for 'Try in PWD'?

### ISSUE THREAD

**Issue by shankari** [play-with-docker/play-with-docker#320]
I have an open source project that is fairly complex, and users who don't necessarily have a very technical background. So PWD would seem ideal as a way for them to check out that everything works, without first installing docker on their laptops. Which, since most of them have windows laptops (see "non technical background") is a bit non-trivial.

I did implement PWD for the basic server, and it works well for that use case (see https://github.com/e-mission/e-mission-docker/).

However, some users would also like to open a jupyter notebook connected to the server. And I ran into two issues getting this to work:
1. I would like to use the published image for the base server (`emission/e-mission-server`) from dockerhub and just add on the jupyter notebook components to create a new image for the notebook. I thought this should be possible, because the logs seemed to indicate that you were using `docker-compose` to create the containers (`Compose does not support...`)

    <img width="833" alt="screen shot 2019-02-12 at 9 08 37 pm" src="https://user-images.githubusercontent.com/2423263/52688262-8770b600-2f0a-11e9-8bda-12fbcf8e2b0a.png">

    However, that did not work because the `build` tag was apparently not supported. I looked at the code https://github.com/play-with-docker/play-with-docker/blob/3bfb09802a6b41ad98adfee79535f813323b90a9/pwd/session.go#L183 and it looks like you use `docker stack deploy`. So then why do I get a warning from compose?

1. jupyter notebook now requires you to specify a token while connecting to the server for the first time. This token is visible in the logs, but you don't display the logs when you build the stack. So the user has to log in to the service and get the token https://github.com/e-mission/e-mission-docker/blob/master/examples/juypter-notebook/README.md#getting-the-token-when-running-in-pwd. Which kind of defeats the purpose of having a "simple" button for them to click.

So...
1. Do you use `docker-compose` or `docker stack deploy` to create the services in the stack?
1. If you use `docker stack deploy`, is there a way I can specify in the launch URL that I want to use `docker-compose` instead?
   1. Is there a way to have `docker-compose` run without `-d` so that the user can see the URL directly in the log and copy/paste it (similar to https://github.com/e-mission/e-mission-docker/blob/master/examples/juypter-notebook/README.md#getting-the-token-when-running-on-your-own-computer)?

**Comment by marcosnils** [comment]
> 1. Do you use `docker-compose` or `docker stack deploy` to create the services in the stack?

We use both. `docker-compose pull` to show the progress of pulling images and `docker stack deploy` to deploy the stacks because we **don't** clone the GH repo of the user, we just pull the `docker-compose.yml` file and run the services in the environment



> 2\. If you use `docker stack deploy`, is there a way I can specify in the launch URL that I want to use `docker-compose` instead?

No there is not



> 1. Is there a way to have `docker-compose` run without `-d` so that the user can see the URL directly in the log and copy/paste it (similar to https://github.com/e-mission/e-mission-docker/blob/master/examples/juypter-notebook/README.md#getting-the-token-when-running-on-your-own-computer)?

No, we're not planning to support this.

**Comment by shankari** [comment]
well, that was mostly clear :)

For the record, I was asking for the option to drop `-d`, i.e. run `docker-compose` **without** `-d`.

I can understand why you can't support the `build` tag if you don't clone the environment, but I don't see why you have to specify `-d`. It is possible to run `docker-compose -f <file_that_only_has_image_tags>` - I've tried it :)

But if you are only going to support `docker stack deploy`, this is irrelevant, since `docker stack deploy` does not currently have the ability to display logs during launch.

For anybody else who finds this issue and is looking for a similar solution, I am going to look at https://mybinder.org/ as a potential solution to this problem.
