### ISSUE TITLE
the problem "cannot use dgst" occured when i install PWD

### ISSUE THREAD

**Issue by GameCaretaker** [play-with-docker/play-with-docker#323]
i want to install PWD in my docker .
i run "docker swarm init","modprobe xt_ipvs"and "docker pull franela/dind".
because of GFW, i have to clone from github to solve the problem of golang dependencies.but after all,when i run "docker-compose up -d",the problem"cannot use dgst" occured and container l2 and pwd exited with error code 2.
how can i solve this problem?thanks for your help.

this is the information of "docker-compose logs".
Attaching to l2, haproxy, pwd
l2         | # docker.io/go-docker
l2         | /go/src/docker.io/go-docker/service_create.go:128:36: cannot use dgst (type "github.com/opencontainers/go-digest".Digest) as type "github.com/docker/distribution/vendor/github.com/opencontainers/go-digest".Digest in argument to reference.WithDigest
haproxy    | [WARNING] 048/172130 (1) : config : missing timeouts for frontend 'http-in'.
haproxy    |    | While not properly invalid, you will certainly encounter various problems
haproxy    |    | with such a configuration. To fix this, please ensure that all following
haproxy    |    | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
haproxy    | [WARNING] 048/172130 (1) : config : missing timeouts for backend 'pwd'.
haproxy    |    | While not properly invalid, you will certainly encounter various problems
haproxy    |    | with such a configuration. To fix this, please ensure that all following
haproxy    |    | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
haproxy    | [WARNING] 048/172130 (1) : config : missing timeouts for backend 'l2'.
haproxy    |    | While not properly invalid, you will certainly encounter various problems
haproxy    |    | with such a configuration. To fix this, please ensure that all following
haproxy    |    | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
haproxy    | [NOTICE] 048/172130 (1) : New worker #1 (6) forked
pwd        | # docker.io/go-docker
pwd        | /go/src/docker.io/go-docker/service_create.go:128:36: cannot use dgst (type "github.com/opencontainers/go-digest".Digest) as type "github.com/docker/distribution/vendor/github.com/opencontainers/go-digest".Digest in argument to reference.WithDigest

**Comment by GameCaretaker** [comment]
my system is centos7

**Comment by joaquinito01** [comment]
We are sorry...
