### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by zysm** [play-with-docker/play-with-docker#331]
Wanted to build docker image but end up with **no space left on device** possible to help on this  ? 

	[node1] (local) root@192.168.0.28 ~
	$ git clone https://github.com/Kaggle/docker-python.git
	Cloning into 'docker-python'...
	$ cd docker-python/
	[node1] (local) root@192.168.0.28 ~/docker-python
	$ docker build -t zysm/docker-python:latest .
	Sending build context to Docker daemon  1.568MB
	Step 1/37 : ARG BASE_TAG=5.2.0
	Step 2/37 : FROM gcr.io/kaggle-images/python-tensorflow-whl:1.13.1-py36 as tensorflow_whl
	1.13.1-py36: Pulling from kaggle-images/python-tensorflow-whl
	cc1a78bfd46b: Pull complete
	420ea9ce27d9: Pull complete
	ec47037b2b3c: Extracting [>                                                  ]   9.47MB/1.491GB
	3e6fda9de2fe: Download complete
	751d158b13b1: Download complete
	3ad0885a05ab: Download complete
	884aa25f6c44: Download complete
	dd5819f51751: Download complete
	bce34a66e68e: Downloading [==================================================>]  1.671GB/1.671GB
	d7bf6d10c301: Download complete
	250b35ed4e43: Download complete
	1ed6a4632d36: Download complete
	2c18d4e3b3e9: Downloading [==================================================>]  636.4MB/636.4MB
	237a1b86d671: Download complete
	db0bf70c7c9b: Download complete
	write /var/lib/docker/tmp/GetImageBlob397023106: no space left on device

**Comment by marcosnils** [comment]
Nope. This image clearly exceeds the instance capacity.
