### ISSUE TITLE
How to disable oauth for private usage in latest commit?

### ISSUE THREAD

**Issue by m4r10k** [play-with-docker/play-with-docker#333]
Hi!

Sadly in the current commit https://github.com/play-with-docker/play-with-docker/commit/b758b005e93ccdb4c8278c68ca74d9f33008a17d it seams like that oauth is enabled by default.

![image](https://user-images.githubusercontent.com/9364572/57570663-bf51a180-7404-11e9-9d17-e67dbbec5832.png)

Whereas in commit https://github.com/play-with-docker/play-with-docker/commit/f7350b02c3c22c37bb7002be5e0efa5b46d9071f it is was not enabled.

![image](https://user-images.githubusercontent.com/9364572/57570523-469e1580-7403-11e9-9c0f-2956fc76797c.png)

How can I disable the authentication layer? Thanks!

**Comment by ebartz** [comment]
+1

**Comment by m4r10k** [comment]
@ebartz always the same ones around here :laughing:

**Comment by m4r10k** [comment]
@marcosnils For me, it looks like as the changes where introduced with the 4b1dc52c59572afc553c83203460f0780c9d22b8 commit, for example: https://github.com/play-with-docker/play-with-docker/commit/4b1dc52c59572afc553c83203460f0780c9d22b8#diff-651a84f8ad6a38c1f7ccdf63f2692410R55

The usage of the hard-coded Docker ID there doesn't look good to me and also the hard coded parameters are ugly. :open_mouth:

I think there shouldn't be such things like DockerClientSecret in there for the public world... - maybe this was merge oops?

**Comment by marcosnils** [comment]
hey, you're correct. Just reverted the changes. Login shouldn't be prompted anymore. 

Please check it out and close if fixed

**Comment by m4r10k** [comment]
Thank you! I will test it over the weekend and let you know! 😀

**Comment by m4r10k** [comment]
Works perfect right now - tested it with my Ansible setup :+1:
