### ISSUE TITLE
Serve applications running inside PWD over HTTPS

### ISSUE THREAD

**Issue by ibnesayeed** [play-with-docker/play-with-docker#334]
Many web APIs (such as Service Worker, Geolocation, and Notifications etc.) are only exposed over HTTPS. hence, `Try in PWD` button will be more useful if apps are served on HTTP and HTTPS both. Perhaps Let's Encrypt Wildcard Certificate would be a good use case here.

**Comment by marcosnils** [comment]
We don't decide how to expose API's with the `Try in PWD` button. We just proxy the requests (either http or https) to the underlying service. We can't also setup certificates because we proxy the connections to the underlying services. 

I believe that you should be able to request a certificate yourself within the PWD container and tell let's-encrypt to valdiate it through tls-sni-01

**Comment by ibnesayeed** [comment]
I understand that and I meant HTTPS termination on the proxy itself, not the application running or a specific port. Are you suggesting that PWD already exposes every app on HTTP and HTTPS both? Since this morning, PWD service seems to be overloaded, so I cannot test it there, but on the Training with PWD site I cannot get an application to be accessed over HTTPS.

**Comment by marcosnils** [comment]
> I understand that and I meant HTTPS termination on the proxy itself, not the application running or a specific port

We can't do this because if we do termination on the proxy then the underlying services can't actually listen in HTTPS. 

> Are you suggesting that PWD already exposes every app on HTTP and HTTPS both?

Yes, PWD just proxies the request to the underlying container. If your app listens in both http and https both protocols will be proxied.

**Comment by ibnesayeed** [comment]
> We can't do this because if we do termination on the proxy then the underlying services can't actually listen in HTTPS.

I see the issue now. If there was a way to identify whether an app is using TLS, the proxy can then always terminate HTTPS, but talks to the app over HTTP or HTTPS as necessary.

**Comment by marcosnils** [comment]
> I see the issue now. If there was a way to identify whether an app is using TLS, the proxy can then always terminate HTTPS, but talks to the app over HTTP or HTTPS as necessary.

We can't detect that as user can run the application in any port that they want. In any case you can still request an https certificate and use tls-sni to authorized it against let's encrypt. It's not PWD responsibility to handle that. 

Additionally, PWD is just a sandboxing environment. I don't think it makes sense to request certificates for very short lived sandboxs. I'll close this as the use-case doesn't apply to PWD itself and does't really make a lot of sense

**Comment by ibnesayeed** [comment]
If we do want to support this use-case, there is a way to terminate TLS on demand by asking the container to set a label (e.g., `LABEL pwd.terminate_tls=true`) or an environment variable for that matter. In this case, PWD can utilize a wildcard certificate for `*.direct.labs.play-with-docker.com` (or `*.play-with-docker.com`). On the contrary, it will be more wasteful for applications to get Let's Encrypt certificates every time a session is created.

**Comment by marcosnils** [comment]
> On the contrary, it will be more wasteful for applications to get Let's Encrypt certificates every time a session is created.

There hasn't been enough interest that justifies changing the proxy and adding this behavior. We'd also have to poll all the containers in the cluster to check for the label and set certificates and configure proxying accordingly. My vote is to leave this as-is and make the user deal with certificate creation. I'd like to hear other thoughts though

@xetorthio WDYT?

**Comment by ibnesayeed** [comment]
> We'd also have to poll all the containers in the cluster to check for the label and set certificates and configure proxying accordingly.

Which proxy server are we using in PWD? I am guessing that all the containers are already being scanned on every change for the proxy to be automated, unless there is a dynamic rule in place that does not require a template-based proxy config generation/

While I can work-around it for my particular use case, I am thinking along the lines of making it more accessible and easy for everyone without causing too much load on LE as the trend of HTTPS adoption is rising.

Here are a few issues I can see when one tries to enable end-to-end HTTPS per application:

* Self-signed volatile certs are ugly to deal with and pile up in the browser as exceptions
* Generating volatile LE certs is wasteful and may cause throttling/rate limiting for the PWD host if too many people start to do this
* If the app server is built with plain HTTP and relies on a reverse proxy for TLS termination, then an additional proxy layer needs to be put in place
* The host name will not be known until the session starts and ENV vars are made available, which means apps will need yet another bootstrapping script to initialize LE cert generation and configuration
* The app repo will need unnecessary code and bloat just to make Try in PWD to work which might not be needed in other environments

**Comment by marcosnils** [comment]
> Which proxy server are we using in PWD? I am guessing that all the containers are already being scanned on every change for the proxy to be automated, unless there is some sort of a dynamic rule in place that does not require a template-based proxy config generation.

^ this. We're not scanning the containers because the `IP` of the container travels in the URL.



> While I can work-around it for my particular use case, I am thinking along the lines of making it more accessible and easy for everyone without causing too much load on LE as the trend of HTTPS adoption is rising.

I get your point. But as stated before, we haven't gotten many requests that justify adding this feature. I still believe it's much easier to create a docker image that helps with the certificate bootstrap than changing the proxy and adding all this complexity.



> * Self-signed volatile certs are ugly to deal with and pile up in the browser as exceptions

I agree, but PWD is just a playground after all ;). It's not intended to run long-running containers or tasks.



> * Generating volatile LE certs is wasteful and may cause throttling/rate limiting for the PWD host if too many people start to do this

It depends on how many people will use this. You're assuming everyone will start using it right away but as before, we haven't received many requests so far. 

> * The app repo will need unnecessary code and bloat just to make Try in PWD to work which might not be needed in other environments

Yes. Keep in mind that not `all` "Try in PWD" button are web pages. So maybe, for the sake of the environment you can make your application start in `http` mode for the playground.

**Comment by ibnesayeed** [comment]
> I still believe it's much easier to create a docker image that helps with the certificate bootstrap than changing the proxy and adding all this complexity.

I think this is a good idea. Perhaps we can create a reusable `pwd-https-proxy` image that utilizes Caddy Server, Traefik, or something simple. We should think about what would be a smooth way to automate and integrate such an image in other stacks.

> So maybe, for the sake of the environment you can make your application start in `http` mode for the playground.

I would have done that for my app, but as described before, the it would fail to function as intended due to some HTTPS-only Web APIs being used.
