### ISSUE TITLE
Add support for using experimental dockerd

### ISSUE THREAD

**Issue by rcjsuen** [play-with-docker/play-with-docker#337]
I would like to try out the experimental syntaxes provided by [buildkit](https://github.com/moby/buildkit/blob/32918bedc92ba9220ba75aeb754a50ccdabbe14e/frontend/dockerfile/docs/experimental.md).

Would it be possible to add an instance image that runs dockerd in `--experimental` mode? Thanks!

**Comment by rcjsuen** [comment]
I see now I can simply use `DOCKER_BUILDKIT=1` for the experimental syntaxes but it may still be useful to have an image that runs dockerd in `--experimental` mode.

I'll leave it up for the maintainers to decide. Feel free to close if you feel there is little value to be gained here.

**Comment by marcosnils** [comment]
you can enable experimental mode by stopping the docker daemon `pkill -9 -f dockerd` chaning `/etc/docker/daemon.json` to enable experimental mode and then starting it with `dockerd &`
