### ISSUE TITLE
Unable to ssh to self-hosted PWD instance

### ISSUE THREAD

**Issue by ouankou** [play-with-docker/play-with-docker#339]
Hello everyone, I created a self-hosted PWD server. The session and instance can be started without any issue. But when I use ssh to access the instance from outside, it asked for a password, which I have no idea what it is. I tried the password for the host user, which doesn't work. I checked issue #285 and #196, confirmed that an ssh-key has been added in the local system for logging to GitHub. Then I got stuck here.

I followed the link below and official wiki here for creating the PWD server.
https://www.n0r1sk.com/post/running-play-with-docker-on-aws/

I noticed that there's a line in the config file, which may be relevant?
https://github.com/play-with-docker/play-with-docker/blob/cf25f7592a37a1030120e6695534cd58e0dcf4e9/config/config.go#L54

It would be great if anyone could provide some suggestions. Thank you in advance!

**Comment by marcosnils** [comment]
You need to generate a key in your local machine for that to work. This has been asked before, please check the closed issues for a resolution.
