### ISSUE TITLE
Docker Playground is not working

### ISSUE THREAD

**Issue by efoda** [play-with-docker/play-with-docker#343]
After clicking the start, it gives me the following:
"We are really sorry but we are out of capacity and cannot create your session at the moment. Please try again later."
It is giving this message for 7 hours !!

**Comment by marcosnils** [comment]
should be good now. Apologies for the downtime

**Comment by shantkalaidjian** [comment]
I have the same issue here.

**Comment by Shatpoz1288** [comment]
Me too

**Comment by marcosnils** [comment]
Fixed now.

**Comment by Shatpoz1288** [comment]
Thanks!

**Comment by BrunoMonte** [comment]
Hi, I have the same problem. "We are really sorry but we are out of capacity and cannot create your session at the moment. Please try again later." On today's date and I can't access!

**Comment by Freeedim** [comment]
Same here on same day as @BrunoMonte (Friday 10 Dec 2021) and today Monday the 13th. I haven't tried during the weekend though.

**Comment by efoda** [comment]
Hello all,
Docker playground works fine with me:
https://labs.play-with-docker.com/

Maybe it was a glitch.
Please try again.

Thanks,
Engy

**Comment by AzureShruthi** [comment]
@marcosnils Please help.

**Comment by marcosnils** [comment]
> @marcosnils Please help.

? the playground is working fine for me

**Comment by AzureShruthi** [comment]
It worked for me. Thanks :)

**Comment by deineiveu** [comment]
Yes, me too

**Comment by patricia300** [comment]
Mine worked After few minutes..

**Comment by akshayjain-tmdc** [comment]
One solution which you can use is try with Incognito Browser. For me that actually helped!

**Comment by Synergy2022** [comment]
even inconito it didnt worked

**Comment by marcosnils** [comment]
> even on incognito it didnt worked.

Fixed. Try again.

**Comment by foremtehan** [comment]
Seen this message for a day rn.

**Comment by Korsavec** [comment]
does not work

**Comment by nick2195** [comment]
@marcosnils Please help. 
Doesnot work for me.

**Comment by marcosnils** [comment]
What error are you getting?

sent from mobile

Em qua., 7 de dez. de 2022 14:51, Nikolay Yuferev ***@***.***>
escreveu:

**Comment by DarrenDong2002** [comment]
@marcosnils I am having same  "..we are out of capacity and cannot create your session.." error. How can this be resolved? Thank you for your time!

**Comment by nickyichov** [comment]
I have the same problem. I tried using incognito mode and different browsers but the message "We are really sorry but we are out of capacity and cannot create your session at the moment. Please try again later." is still there.

**Comment by KangShanR** [comment]
same problem.

**Comment by rajakandukuru** [comment]
facing same problem

**Comment by efoda** [comment]
@marcosnils date: 8/9/2023: The Docker playground doesn't create any instances and doesn't generate any errors! 
Can you please fix it? 
Thanks in advance!

**Comment by AdamBoniecki** [comment]
I have the same issue here.

**Comment by tchiaspko** [comment]
I have the same issue here.

**Comment by marcosnils** [comment]
should be good now

**Comment by MichalekJan93** [comment]
I have the same probelm "We are really sorry but we are out of capacity and cannot create your session at the moment. Please try again later."

**Comment by marcosnils** [comment]
should be workin now

**Comment by ksgriggs** [comment]
We are really sorry but we are out of capacity and cannot create your session at the moment. Please try again later.

**Comment by marcosnils** [comment]
try again, you should eventually get a session

**Comment by mohamedae17** [comment]
same problem

**Comment by learninn** [comment]
same problem

**Comment by dkryshtopenkomck** [comment]
same problem
https://labs.play-with-docker.com/ooc @marcosnils :( 
<img width="903" alt="Screenshot 2024-06-08 at 9 31 45" src="https://github.com/play-with-docker/play-with-docker/assets/91821923/adb5c550-51a0-4e64-bee5-92755b7b423c">

**Comment by marcosnils** [comment]
> same problem

fixed.

**Comment by 51L3N7-X** [comment]
same here.

**Comment by shreyamittal586** [comment]
same here, also if the session starts I'm not able to create the new instance:

![Image](https://github.com/user-attachments/assets/d22e94f2-a8be-48f9-9d99-eed70f28494e)

**Comment by marcosnils** [comment]
> I'm getting this same error

 try again, should be fixed

**Comment by crashbtz** [comment]
+1

**Comment by svegaj-cenfo** [comment]
Hi, this issue here

"We are really sorry but we are out of capacity and cannot create your session at the moment. Please try again later."

**Comment by efoda** [comment]
@marcosnils @xetorthio Thanks for creating and supporting the Docker Playground over the years!
I am so sad it got shut down. 
It was the best. 
RIP, Docker Playground! :(
