### ISSUE TITLE
Support for external access to applications like kubernetes dashboard

### ISSUE THREAD

**Issue by BIAOXYZ** [play-with-docker/play-with-docker#345]
I have noticed that external access to applications have been disabled,  since the `EXTERNAL-IP` is always `<pending>` in the following picture. I think it is a very useful feature and do not know why it is prohibited. 

```
[node1 ~]$ kubectl get svc
NAME                                          TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
kubernetes                                    ClusterIP      10.96.0.1        <none>        443/TCP        3h27m
my-nginx-svc                                  LoadBalancer   10.109.57.216    <pending>     80:31311/TCP   41m
```

**Comment by marcosnils** [comment]
The external-ip will be seen as "pending" but you can still connect to the exposed services using the displayed instance url
![image](https://user-images.githubusercontent.com/1578458/60758135-2006f000-9fea-11e9-9c71-e0613edfd3e4.png)

**Comment by BIAOXYZ** [comment]
Could you provide some more detailed info? From some other issues like (https://github.com/play-with-docker/play-with-docker/issues/259) I cannot get an effective way to display service to outside (by way of using the url or url+port).

**Comment by marcosnils** [comment]
Sure, here's a briefly GIF to see how that works


![nginx-example](https://user-images.githubusercontent.com/1578458/60759362-7e3bcf00-9ffa-11e9-8578-311cf1caa2d8.gif)

**Comment by BIAOXYZ** [comment]
Thanks. Maybe because I choose another (NodePort) way to expose service, so it failed...

**Comment by yogeek** [comment]
Hi @marcosnils , access to nginx mage does not seem to work anymore by following the GIF above... is there a new way to access to service externally please ?

**Comment by marcosnils** [comment]
hey @yogeek just tried and it worked for me. Can you create a session and share the URL pleae?

**Comment by yogeek** [comment]
Hi @marcosnils , just tried again on a fresh session and now scheduling is not possible apparently caused to disk pressure on a node :
```
Warning  FailedScheduling  60s (x5 over 4m23s)  default-scheduler  0/2 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 1 node(s) had taint {node.kubernetes.io/disk-pressure: }, that the pod didn't tolerate.
```

Here is the URL : https://labs.play-with-k8s.com/p/c3cnjvp75d7000bq6qlg#c3cnjvp7_c3cnk2h75d7000bq6qm0

**Comment by francilioaraujo** [comment]
Hi @marcosnils . I tried the method shown in the GIF with no success too. Also tried including the port with an - after the session id, but it didn't work.
I noted that running `ip -br neigh` show the other nodes as STALE and even inside the cluster we cannot access the services using the node's eth1 ipv4 address.
I used the bootstrap steps to reproduce this

**Comment by marcosnils** [comment]
:wave: is this on the public environment?

**Comment by marcosnils** [comment]
can u try now? I think it should be fixed.

**Comment by francilioaraujo** [comment]
It works now. Thank you @marcosnils

**Comment by rajeshkillercoda** [comment]
Is It not working again ? I tried a lot repeating the steps shown in the GIF file but no luck at all !

**Comment by gertsog333** [comment]
Is It not working again. Could you please help ?
