### ISSUE TITLE
What's wrong with the instance window?

### ISSUE THREAD

**Issue by guest6379** [play-with-docker/play-with-docker#350]
1. Click the "Start" button
2. Click "Add New Instance" button
3. In the new instance window, type "tmux" command

After step 3,  I got a screen like the screenshot shown as below:

![1](https://user-images.githubusercontent.com/15060397/62693957-0819f600-ba06-11e9-9eac-c8024c09d4ae.png)

4. In the tmux window, just press the key`Ctrl+B, %` in order to split the screen horizontally, but I got a screen like the screenshot shown as below:

![2](https://user-images.githubusercontent.com/15060397/62693977-110ac780-ba06-11e9-8bac-68f41a22f0c9.png)

5. Press 'Alt+Enter' to fullscreen, I got:
![3](https://user-images.githubusercontent.com/15060397/62694008-1e27b680-ba06-11e9-948b-5199a8a832f1.png)

It does not fit the width of my screen, it squeezed too much :(

**Comment by marcosnils** [comment]
we upgraded xterm.js recently and seems like we introduced a regression here. @zapaiamarce let's see if we can fix it :(

**Comment by guest6379** [comment]
@marcosnils  How's going on this issue? It's really a matter when using PWD to learn Linux and Docker, especially when you need to open mutiple-panel in one window screen,   check the image below:

![1](https://user-images.githubusercontent.com/15060397/63518878-8b6a3a00-c524-11e9-8d0b-01d1b1f80182.png)


Would you please rollback  PWD online to https://github.com/play-with-docker/play-with-docker/commit/5d868945213206f28e2aa92cd98c5f705a8672f2 , thank you very much.

**Comment by marcosnils** [comment]
This should be fixed now. Can you check @guest6379 ?

**Comment by guest6379** [comment]
I just did very quick check, it seems to be right now. 
If I find any other problems about this issue, I'll point it out, thank you for fixing this!

> This should be fixed now. Can you check @guest6379 ?

I just did very quick check, it seems to be right now. 
If I find any other problems about this issue, I'll point it out, thank you for fixing this!
