### ISSUE TITLE
play-with-k8s.com seems to be down at the moment

### ISSUE THREAD

**Issue by chips-bo** [play-with-docker/play-with-docker#353]
Hello and thanks for all the great work.
Just to let you know that I can go play-with-k8s.com but if I click new instance nothing happens.
Tried in multiple browser and 2 different networks but can't get to a console.
Thanks
Brian

**Comment by chips-bo** [comment]
back up-Awesome-Thank you so much!

**Comment by alexrun** [comment]
The page is up and working. @chips-bo you can close this issue.
