### ISSUE TITLE
Website https://labs.play-with-k8s.com/ returns HTTP 500 on "Add new instance"

### ISSUE THREAD

**Issue by oveits** [play-with-docker/play-with-docker#357]
The Website https://labs.play-with-k8s.com/  returns an HTTP Error 500 when I try to "ADD NEW INSTANCE". This makes the Website unusable.

Tested on Chrome Version 76.0.3809.132 (Offizieller Build) (64-Bit) and Microsoft Edge 44.18362.329.0.

![image](https://user-images.githubusercontent.com/8299115/65386150-1020c180-dd38-11e9-91fc-c55889767b03.png)

**Comment by inductor** [comment]
Reproducted here too

**Comment by paleozogt** [comment]
I see this also.

**Comment by ldmichiels** [comment]
I had the same problem but 30 minutes later it was magically solved (with a new session)

![Captura de pantalla de 2020-04-27 09-04-30](https://user-images.githubusercontent.com/2789528/80375533-db955b00-886e-11ea-87c3-b7f92144361e.png)

![Captura de pantalla de 2020-04-27 10-02-31](https://user-images.githubusercontent.com/2789528/80375530-da642e00-886e-11ea-9a84-ad64ec479366.png)
