### ISSUE TITLE
Failing to upgrade to Kubernetes 1.14 or 1.15, please advice

### ISSUE THREAD

**Issue by SebTardif** [play-with-docker/play-with-docker#365]
Some useful command about namespace management is missing in 1.11, so I tried to upgrade to 1.14 and 1.15 in many ways but they all failed. I don't understand fully, but some complain about systemd, and cgroup plug-in.

**Comment by marcosnils** [comment]
I can try bumping to 1.14 soon. Thx for reporting.

**Comment by marcosnils** [comment]
Bumped it to 1.14. Let me know how it goes
