### ISSUE TITLE
users can mount host device in RW mode after installation

### ISSUE THREAD

**Issue by chunhualiao** [play-with-docker/play-with-docker#366]
Hi, I was able to install PWD on a local Ubuntu machine. I put the steps I used into https://github.com/chunhualiao/freeCompilerCamp/wiki/Deploy-Play-With-Dock-on-a-local-Ubuntu-18.04-machine

However, users can mount host device in RW mode from within the terminal,  using the instructions documented by the first part of https://securityboulevard.com/2019/01/how-i-hacked-play-with-docker-and-remotely-ran-code-on-the-host/

```
[node1] (local) root@10.0.1.4 ~
$ cat /proc/cmdline 
BOOT_IMAGE=/boot/vmlinuz-5.0.0-32-generic root=UUID=6dd99ba4-749e-486f-9289-0b0ac9638869 ro find_preseed=/preseed.cfg auto noprompt priority=critical locale=en_US quiet
[node1] (local) root@10.0.1.4 ~

$ findfs UUID=6dd99ba4-749e-486f-9289-0b0ac9638869
/dev/sda1
[node1] (local) root@10.0.1.4 ~

$ mkdir /mnt1
[node1] (local) root@10.0.1.4 ~

$ mount /dev/sda1 /mnt1
[node1] (local) root@10.0.1.4 ~

$ ls /mnt
mnt/  mnt1/ 
[node1] (local) root@10.0.1.4 ~

$ ls /mnt1/
bin             etc             lib             mnt             run             srv             usr
boot            home            lib64           opt             sbin            swapfile        var
cdrom           initrd.img      lost+found      proc            snap            sys             vmlinuz
dev             initrd.img.old  media           root            src             tmp             vmlinuz.old
[node1] (local) root@10.0.1.4 ~
```
Did I miss any critical steps?  Thanks!

**Comment by marcosnils** [comment]
Now, you didn't. That's how it works by default. The environment in `play-with-docker.com` has some extra security and scalability features which are not part of the open source project. If you want to know more about enterprise pricing you can send me a private message.
