### ISSUE TITLE
How to use external volumes ?

### ISSUE THREAD

**Issue by ricardolimaui** [play-with-docker/play-with-docker#368]
Hello all,

I try to set ExternalDindVolume to true, but then it says plugin xfsvol not found. This is the correct way to bind a volume ?

How we can bind a preset volume for example to use it in a mongo database? 

It is possible ? I want to have the data set already loaded and not doing the upload.

Thank you

**Comment by marcosnils** [comment]
You can't bind an existing volume to the PWD environment currently. The `ExternalDindVolume` is to use a different volume driver so quotas can be applied on PWD volumes. You could implement this quite easily by forking the code and sending the correct argument in the corresponding `ContainerCreate` function.
