### ISSUE TITLE
Session Ends After Initializing Cluster Networking

### ISSUE THREAD

**Issue by lengebre** [play-with-docker/play-with-docker#369]
After attempting to run the second command to initialize cluster networking;

```
kubectl apply -n kube-system -f \
    "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 |tr -d '\n')"
```

The cluster reaches the Ready state, but soon after disconnects and ends the session;
"Your session has expired and all of your instances have been deleted."

**Comment by marcosnils** [comment]
fixed
