### ISSUE TITLE
Not able to connect to published port of mongodb instance

### ISSUE THREAD

**Issue by kailashyogeshwar85** [play-with-docker/play-with-docker#373]
I have deployed mongod container and exposed port 27017 but when I try to connect it remotely it doesn't connect any additional changes are required on PWD host ?

**Comment by marcosnils** [comment]
This is not possible, PWD only tunnels `http, https and websockets` connections through the proxy. You can setup an SSH tunnel to the PWD instance and connect there if you need to

**Comment by ankit-jha** [comment]
> I have deployed mongod container and exposed port 27017 but when I try to connect it remotely it doesn't connect any additional changes are required on PWD host ?

@kailashyogeshwar85 Were you able to finally connect to the instance ?

I'm struggling too
https://stackoverflow.com/questions/66978741/unable-to-connect-to-mysql-server-docker-container-running-in-docker-playground

**Comment by marcosnils** [comment]
You can't do this, it's disabled by design.

**Comment by ankit-jha** [comment]
> This is not possible, PWD only tunnels `http, https and websockets` connections through the proxy. You can setup an SSH tunnel to the PWD instance and connect there if you need to

@marcosnils I thought that once an SSH tunnel is established then I should be able to connect via a mysql command line client

**Comment by marcosnils** [comment]
Nope, SSH tunnels are disabled.

**Comment by ankit-jha** [comment]
@marcosnils 
Thanks for clarification

I think then best would be to run a phpsqladmin in another container being served at the http(s) port

**Comment by marcosnils** [comment]
Yes, you can do that. FWIW SSH tunnels are possible, it's just disabled on the PWD SSH daemon. 

If you want that, you'll have to change the daemon config yourself and restart the SSHD daemon. But we've decided to close it by default to prevent any environment misusage.

**Comment by ankit-jha** [comment]
@marcosnils 
Can you help me with the restart `sshd` ?
I went in `/etc/ssh/sshd_config` and changed `AllowTcpForwarding` to `yes`.
But restarting by issuing `/etc/init.d/sshd stop` `/etc/init.d/sshd start` in sequence didn't seem to work.
