### ISSUE TITLE
Endless loop container creation through PWD button

### ISSUE THREAD

**Issue by evgeniyosipov** [play-with-docker/play-with-docker#374]
Hello,
I have endless loop container creation through GitHub PWD button 

`[![Try in PWD](https://raw.githubusercontent.com/play-with-docker/stacks/master/assets/images/button.png)](https://labs.play-with-docker.com/?stack=https://raw.githubusercontent.com/evgeniyosipov/jbelly/master/docker-compose.yml)`

But when I create container manually and execute following:
```
wget https://raw.githubusercontent.com/evgeniyosipov/jbelly/master/docker-compose.yml
docker-compose up
```
Everything works good.

What am I doing wrong?

Thank you in advance.

**Comment by marcosnils** [comment]
hey @evgeniyosipov!

The problem is that PWD doesn't do `docker-compose up` to start your stack. It does `docker stack deploy` instead.. And docker services don't work with mounts. 

After your session is created, if yo do `docker stack ps pwd` you'll see what I'm referring to.
