### ISSUE TITLE
Help to run PWD in local machine.

### ISSUE THREAD

**Issue by Chococoin** [play-with-docker/play-with-docker#375]
Hi,

I'm a newentry in the docker universe, I love the the layer of simplicity the dockers add in complex projects, but in any case it is a layer more that rear up the learning curve to dominate a project that use Dockers.

I love PWD because make very easy the learning process of docker. I'm trying to traslate init Spanish and Italian some of the tutorial, but I'm having a hard time to make run the repo in my machine because so many requirements to run PWD in local. 

My question is, there isn't a way to run PWD with just a docker command without install so many things in ma machine. Is funny, but I will expect to just pull an image to run a container that allows play with PWD, but the process to do it that I fund in the readme goes against this intuition. 

Thank for your time and support.

**Comment by marcosnils** [comment]
If you're translating the tutorials in https://training.play-with-docker.com/ then you don't need this repo to start the environment locally. Just go to https://github.com/play-with-docker/play-with-docker.github.io  and follow this instructions (https://github.com/play-with-docker/play-with-docker.github.io#running-trainings-site) to run the training site locally. As you said, it's just one `docker run` command

**Comment by Chococoin** [comment]
Thank you very much! I'll keep in touch for the translations.
