### ISSUE TITLE
docker: write /var/lib/docker/tmp/xxx no space left on device.

### ISSUE THREAD

**Issue by bofhbug** [play-with-docker/play-with-docker#376]
can some one take a look about the full filesystem?

[node1] (local) root@192.168.0.48 ~
$ df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  10.0G     96.0K     10.0G   0% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                    15.7G         0     15.7G   0% /sys/fs/cgroup
/dev/sdb                 64.0G     64.0G     16.0K 100% /etc/resolv.conf
/dev/sdb                 64.0G     64.0G     16.0K 100% /etc/hostname
/dev/sdb                 64.0G     64.0G     16.0K 100% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
/dev/sdb                  4.7G    160.0K      4.7G   0% /var/lib/docker
[node1] (local) root@192.168.0.48 ~
$ docker system prune
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all dangling images
  - all dangling build cache

Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B
[node1] (local) root@192.168.0.48 ~
$ docker volume prune
WARNING! This will remove all local volumes not used by at least one container.
Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B
[node1] (local) root@192.168.0.48 ~
$ docker run -d -p 8081:80 --name nc nextcloud:18
Unable to find image 'nextcloud:18' locally
18: Pulling from library/nextcloud
8ec398bc0356: Downloading [==================================================>]  27.09MB/27.09MB
85cf4fc86478: Downloading [==================================================>]     225B/225B
970dadf4ccb6: Downloading [==================================================>]  76.65MB/76.65MB
8c04561117a4: Downloading [==================================================>]     224B/224B
d6b7434b63a2: Downloading [==================================================>]  18.68MB/18.68MB
83d8859e9744: Downloading [==================================================>]     434B/434B
9c3d824d0ad5: Downloading [==================================================>]     491B/491B
9e316fd5b3b3: Downloading [==================================================>]  12.44MB/12.44MB
578b40496c37: Downloading [==================================================>]     493B/493B
814ae7711d3c: Downloading [==================================================>]  14.08MB/14.08MB
4896fed78b6b: Downloading [==================================================>]  2.231kB/2.231kB
e74d71e9611d: Downloading [==================================================>]     245B/245B
46017765526c: Downloading [==================================================>]     213B/213B
280386098458: Downloading [==================================================>]     895B/895B
11a7c8596b56: Downloading [==================================================>]  1.659MB/1.659MB
8d04e75769f6: Downloading [==================================================>]   16.2MB/16.2MB
6561bcc8c65b: Downloading [==================================================>]     504B/504B
d71822075f1a: Downloading [==================================================>]     541B/541B
cc2c4b209ee1: Downloading [==================================================>]  93.94MB/93.94MB
e253f3fed9e0: Downloading [==================================================>]  2.161kB/2.161kB
34ed424daedb: Downloading [==================================================>]  1.186kB/1.186kB
docker: write /var/lib/docker/tmp/GetImageBlob160831802: no space left on device.
See 'docker run --help'.
[node1] (local) root@192.168.0.48 ~
$
[node1] (local) root@192.168.0.48 ~
$ df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  10.0G     96.0K     10.0G   0% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                    15.7G         0     15.7G   0% /sys/fs/cgroup
/dev/sdb                 64.0G     63.5G    480.9M  99% /etc/resolv.conf
/dev/sdb                 64.0G     63.5G    480.9M  99% /etc/hostname
/dev/sdb                 64.0G     63.5G    480.9M  99% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
/dev/sdb                  4.7G    160.0K      4.7G   0% /var/lib/docker
[node1] (local) root@192.168.0.48 ~
$ docker volume prune
WARNING! This will remove all local volumes not used by at least one container.
Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B
[node1] (local) root@192.168.0.48 ~
$ docker system prune
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all dangling images
  - all dangling build cache

Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B
[node1] (local) root@192.168.0.48 ~
$ df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  10.0G    100.0K     10.0G   0% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                    15.7G         0     15.7G   0% /sys/fs/cgroup
/dev/sdb                 64.0G     63.5G    480.2M  99% /etc/resolv.conf
/dev/sdb                 64.0G     63.5G    480.2M  99% /etc/hostname
/dev/sdb                 64.0G     63.5G    480.2M  99% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
/dev/sdb                  4.7G    160.0K      4.7G   0% /var/lib/docker
[node1] (local) root@192.168.0.48 ~
$

**Comment by marcosnils** [comment]
This repository is for the open source project. play-with-docker.com problems are not addressed here.

**Comment by bofhbug** [comment]
@marcosnils ok thanks for the Feedback.
