### ISSUE TITLE
Session is getting timed out 

### ISSUE THREAD

**Issue by joshianurag21** [play-with-docker/play-with-docker#378]
Hello all,

Today When I am trying out things with play with docker. After running docker run command, immediately session is getting timedout. I am not sure if I am missing any setting over there.

![image](https://user-images.githubusercontent.com/20928877/74527522-eddc4a00-4f4b-11ea-8f5c-efa63f0cfcc8.png)

Can you please help me with that.

**Comment by marcosnils** [comment]
Hi, what are you trying to run?

**Comment by joshianurag21** [comment]
I am trying to run localstack over there using below command:

**docker run -it -p 4572:4572 -p 4574:4574 -p 4569:4569 -p 8080:8080 --env SERVICES=lambda,s3,dynamodb --env LAMBDA_EXECUTOR=docker --env DOCKER_HOST=unix:///var/run/docker.sock -v /var/run/docker.sock:/var/run/docker.sock localstack/localstack**


Yesterday I tried same command, at that time it was working fine. But today its getting timed out.

**Comment by marcosnils** [comment]
Fixed
