### ISSUE TITLE
Asking for a RTFM...

### ISSUE THREAD

**Issue by marcbria** [play-with-docker/play-with-docker#381]
I try to run my docker-compose.yml with play-with-docker without success.

My call is:
https://labs.play-with-docker.com/?stack=https://raw.githubusercontent.com/pkp/docker-ojs/master/versions/3_2_0-0/alpine/apache/php73/docker-compose.yml#

Is there any tutorial/manual/documentation to discover what I'm doing wrong?

Thanks in advance,
m.

**Comment by mateuszdrab** [comment]
What errors are you experiencing? I'm having lots of issues running things too, but I managed to get the master branch from PWD to run.

**Comment by marcbria** [comment]
Hi,

As far it was not taking my .env file I tried to give my vars a default value as follows:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-ojsPwd}"

And was not working... till today that I checked it and is working like a charm! :-)

Thanks for the advice!
