### ISSUE TITLE
WebSocket didn't emit data from scheduler

### ISSUE THREAD

**Issue by ii64** [play-with-docker/play-with-docker#382]
Hello, i created CLI version play-with-docker, however when i try to connect to websocket, it didn't receive  any event but able to emit terminal in and successfully displayed in the terminal output, it worked yesterday :/
Ref: https://github.com/ii64/play-with-docker-cli/blob/master/api/dashboard.go#L294
![image](https://user-images.githubusercontent.com/26342994/77472833-16a70780-6e47-11ea-9d13-f97336b0a0ef.png)

**Comment by marcosnils** [comment]
The best place to test this is against the code in this repo, not the production environment.
