### ISSUE TITLE
Unable to ssh to docker host node launched on PWD, from Ubuntu 18.04

### ISSUE THREAD

**Issue by vpatiltech** [play-with-docker/play-with-docker#394]
Unable to ssh to docker host node launched on PWD, from Ubuntu 18.04.

Error is "port 22: connection refused"

It was working fine till yesterday.

**Comment by marcosnils** [comment]
Fixed

**Comment by vpatiltech** [comment]
Bravo.. !! Its working as expected now. Thanks for quick turnaround. Just curious was there some recent change on server side that caused this?
![image](https://user-images.githubusercontent.com/46068997/78471558-c6d21580-774f-11ea-8303-c3f917523fbb.png)
