### ISSUE TITLE
Direct SSH to PWD instance not working

### ISSUE THREAD

**Issue by zasdaym** [play-with-docker/play-with-docker#395]
Trying to ssh to a fresh instance, but got connection refused.

ssh -vv ip172-18-0-45-bq4cl8lim9m000befg8g@direct.labs.play-with-docker.com

```
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: resolving "direct.labs.play-with-docker.com" port 22
debug2: ssh_connect_direct
debug1: Connecting to direct.labs.play-with-docker.com [40.76.55.146] port 22.
debug1: connect to address 40.76.55.146 port 22: Connection refused
ssh: connect to host direct.labs.play-with-docker.com port 22: Connection refused
```

Already check some similar closed issues about ssh not working, but got no solution.

**Comment by marcosnils** [comment]
Fixed

**Comment by YuriSizuku** [comment]
> Fixed

I also have the same problem.
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: resolving "direct.labs.play-with-docker.com" port 22
debug2: ssh_connect_direct
debug1: Connecting to direct.labs.play-with-docker.com [40.76.55.146] port 22.
debug1: connect to address 40.76.55.146 port 22: Connection refused
ssh: connect to host direct.labs.play-with-docker.com port 22: Connection refused
