### ISSUE TITLE
Connection has been lost. Sometimes this happens when a windows instance is joining a swarm. Trying to reconnect terminal7

### ISSUE THREAD

**Issue by YounessELB** [play-with-docker/play-with-docker#397]
- Add new instance in PWD
- docker run -p 8080:8080 registry.gitlab.com/younesselb/spring-petclinic/spring-petclinic:2.2.2

The container works for a while and then the session timed out with this message :

Connection has been lost. Sometimes this happens when a windows instance is joining a swa
![pwd_error](https://user-images.githubusercontent.com/46241238/80307353-6ec38780-87c0-11ea-8092-3c801917a59e.png)
rm. Trying to reconnect terminal7

**Comment by marcosnils** [comment]
Fixed

**Comment by YounessELB** [comment]
Sorry to say that ... But the error appeared again!

![pwd_error2](https://user-images.githubusercontent.com/46241238/80356129-ef41c100-8870-11ea-89ea-31740aa12e40.png)

**Comment by marcosnils** [comment]
Are you running the same container? petclinic runs fine for me.

**Comment by YounessELB** [comment]
It's OK @marcosnils , thanks a lot !
