### ISSUE TITLE
Access instance from netcat

### ISSUE THREAD

**Issue by apogiatzis** [play-with-docker/play-with-docker#399]
Hello,
Is it possible to access the instance using netcat and different protocol than HTTP?

How can I send bytes directly to some port on my instance without HTTP?

**Comment by marcosnils** [comment]
Hi, the instances have SSH, so you can use SCP for that.

**Comment by apogiatzis** [comment]
But I am not interested in transferring files. I am looking for bidirectional communication through sockets. For instance, I have a pure sockets service listening on port 4000. How can I interact with that?

**Comment by marcosnils** [comment]
It's not possible right now since the PWD proxy needs to be http to know which instance to route the request. You can create a tunnel with `ssh` and forward the port to your machine

**Comment by apogiatzis** [comment]
Oh alright, thanks for the clarification.
