### ISSUE TITLE
cannot run docker-compose

### ISSUE THREAD

**Issue by tanvp112** [play-with-docker/play-with-docker#401]
Hi, is docker-compose supported on PWD? Not sure why the application cannot run, please see:

Update: chown to the same as docker command in the same directory yield the same "No such file or directory" error.

![image](https://user-images.githubusercontent.com/57385114/84018757-f6e99f00-a9b2-11ea-98e1-368cafe069dc.png)

**Comment by marcosnils** [comment]
I made some updates in the env during the weekend and I probably broke something. Thx for reporting

**Comment by tanvp112** [comment]
Yeap, version 1.26 shown, works like a charm now!

Thanks, Marco
