### ISSUE TITLE
PwD in DinD

### ISSUE THREAD

**Issue by mateuszdrab** [play-with-docker/play-with-docker#402]
Hey all

Out of curiousity I was trying to see if I could create PwD inside a Docker host that itself is a container using the latest docker:dind image. 

I can get the DinD to work fine but I'm unable to load the xt_ipvs module. It loads fine inside the host but inside the DinD container I get:

`ip: can't find device 'xt_ipvs'`

This is happening after already launching the container with the following arguments:

`docker run --privileged --name DIND-PwD -d --network macvlan_net --ip 192.168.*.* --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules docker:dind`

Additionally, the processes started by docker-compose fail to launch with error code 1.

I ran all the commands specified in the https://github.com/play-with-docker/play-with-docker#development article.

Is DinD with PwD even possible. I read that you should be able to create DinD inside DinD...

Thanks

**Comment by mateuszdrab** [comment]
Thanks @marcosnils 
I since managed to launch the PwD environment on a test VM based on Ubuntu. I noticed I can only access it via the http://localhost and other DNS names don't work. Is this something that is hard coded? I wanted to make PwD available in my network under a dedicated fqdn and also fix up the port exposing feature.

**Comment by mateuszdrab** [comment]
Hey @marcosnils

I've been able to get PWD to work outside localhost just fine by simply adding the following line in the pwd backend in the haproxy config.
`http-request set-header host localhost`

I added the needed DNS entries and I can even SSH into the instances and open ports from the web UI, however the port opening feature is misbehaving... 
If I open access to port 80 and let's say 8000. At first, I can browse both, but after a few moments, they seem to get mixed up. I'm trying to figure out if it's an issue due to my localhost workaround (there is not header translation for accessing the l2 backend) or perhaps the issue is with the l2 backend router...

**Comment by marcosnils** [comment]
Are you still trying to achieve PWD in DinD? Or the previous comment is about deploying PWD in a standalone VM?

**Comment by mateuszdrab** [comment]
I have up on that, currently trying to get it all to just work in a dedicated clean Ubuntu VM, if I can get it all to work like that, I will try DinD again :)

**Comment by marcosnils** [comment]
> I gave up on that, currently trying to get it all to just work in a dedicated clean Azure Ubuntu VM, if I can get it all to work like that, I will try DinD again :)

In that case, the only change that you should do to make this work in a VM and being able to access from the outside is changing the haproxy.conf so it doesn't say "localhost.

**Comment by mateuszdrab** [comment]
There actually isn't anything in haproxy.conf mentioning localhost.
I found that I had to add a line to make haproxy spoof the localhost host header on connections to the pwd container and then it works...

**Comment by marcosnils** [comment]
> There actually isn't anything in haproxy.conf mentioning localhost.

That's correct. You shouldn't have to set the header to localhost since probably some things could break. I'll try deploying PWD in a remote VM today to see what's not working.

**Comment by mateuszdrab** [comment]
Thanks, I was thinking this breaks the reverse proxy functionality, but it can't really, since I'm not forcing the localhost header to the l2 container and setting the option to close http connections after each request fixed it.

Having an issue with the franela/k8s container, the weave network plugin fails to start but works just fine in real play with k8s site, I wonder if I'm missing some module.

**Comment by marcosnils** [comment]
@mateuszdrab just remembered what needed to be done. You need to configure this variable (https://github.com/play-with-docker/play-with-docker/blob/master/config/config.go#L58) with the domain that you're planning to use. That should make it work.

**Comment by mateuszdrab** [comment]
Alright, I will try that later.

I'm still trying to figure out why the k8s cluster doesn't build. 
Health checks fail on the kube-apiserver pod and rest keeps restarting.
The only difference atm in the logs I can see is a different kernel version. 
5.3.0-1028-azure vs 4.4.0-177-generic

**Comment by marcosnils** [comment]
Does it work in your local machine?

I'll try that later today.

**Comment by mateuszdrab** [comment]
Not sure, I will have to try on a non Azure VM, I rebuilt the Azure VM into 16.04 with kernel 4.15.0-1089-azure and still facing same issue.

**Comment by marcosnils** [comment]
Yo should be able to try this in your local machine. No need to use it in
the cloud

**Comment by mateuszdrab** [comment]
Just confirmd the regex hostPattern in host.go catches the name correctly, so it shouldn't cause those issues I have with the router. It doesn't seem to look beyond the first part of the domain, until the first dot.

**Comment by marcosnils** [comment]
> Correct, but I normally don't work with stuff on my local machine, since I want to have this running in a VM in my Azure Stack lab.

I know.. I'm just trying to see if this is specific to your cloud deployment since it "should" work locally. That's how I try it.

**Comment by mateuszdrab** [comment]
So, little summary:
✔ changing playground-domain works, no longer need to inject localhost as a header via haproxy
❌ the port forward proxy still mashes up connections, option `option http-server-close` needs to stay in the l2 backend on haproxy
✔the K8s cluster works fine in PwD deployed on a test Ubuntu VM (not Azure) running kernel 4.8.0-59-generic
I notice that the production PwD website and my Ubuntu VM log this line, the Azure VM didnt:
`[WARNING FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist`

**Comment by marcosnils** [comment]
> the port forward proxy still mashes up connections, option `option http-server-close` needs to stay in the l2 backend on haproxy

Not sure if I completely understand this.

**Comment by mateuszdrab** [comment]
> > the port forward proxy still mashes up connections, option `option http-server-close` needs to stay in the l2 backend on haproxy
> 
> Not sure if I completely understand this.

So, if I start nginx and open a port to that container using the button and enter 80, and then open another web server, for example portainer and open port 9000, for a moment it works fine, but then if I refresh the nginx page, it shows me portainer instead. My investigation led to the discovery that the l2 container doesn't log all requests coming in as connections, which means that the connections have to be reused, and this probably means that the l2 container proxy service caches the host header potentially, and it doesn't recognise when a request comes through for a different service. `option http-server-close` makes haproxy kill the connection after each request, which seems to fix the issue at the expense of reopening a new connection for each request.

Btw, I've now managed to start PwD in DinD on my existing docker host (something I couldn't do earlier). The kubernetes cluster creates and fails with the same issue like it did on the Azure VM, strangely, I'm not seeing the `[WARNING FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist` message. I feel like it has something to do with it...

**Comment by mateuszdrab** [comment]
Turns out the answer to this issue is 
`modprobe nf_conntrack ip_vs_sh ip_vs_rr ip_vs ip_vs_wrr xt_ipvs`
`echo 65536 > /sys/module/nf_conntrack/parameters/hashsize`

After this, I can build k8s clusters in both Azure, DinD and my other test VMs
