### ISSUE TITLE
How to start K8s?

### ISSUE THREAD

**Issue by mateuszdrab** [play-with-docker/play-with-docker#404]
Hey there

I've been able to start PWD from the master branch easily.

I am now scripting an installer for this for my Azure ARM template and I'm having trouble running the same code with the K8s branch.

Lots of errors regarding files missing in /go/src/github.com

I can see the volume mount changes from $PWD:/go/src to $GOPATH/src:/go/src when moving from master to k8s branch.

How do I populate /go/src? Do I actually have to manually git clone all requested libraries?

Thanks

**Comment by marcosnils** [comment]
The k8s branch has been incorporated to master since long time ago. I've just removed it. In order to use k8s, you just need to change your playground image to `franela/k8s` and change the default playground AssetsDir to "k8s" here https://github.com/play-with-docker/play-with-docker/blob/master/api.go#L55

**Comment by mateuszdrab** [comment]
Thanks @marcosnils 

I was wondering if this was the case, I saw the folders under the master branch... will try to get it to run and create some pull requests. If you could take a look at my other issue it would be great. I forked the project and would be happy to PR some changes that I did to fix the issues I had.

Thanks

**Comment by marcosnils** [comment]
> If you could take a look at my other issue it would be great.

Sure! Will try to take a look when I have some time.

**Comment by mateuszdrab** [comment]
Thanks

I just changed the line in api.go to `AvailableDinDInstanceImages: []string{"franela/dind","franela/k8s"}`

Now it seems I can launch both types of containers in the same instance of PwD.

Could you elaborate what you mean by AssetsDir?

**Comment by marcosnils** [comment]
> Could you elaborate what you mean by AssetsDir?

The www folder (https://github.com/play-with-docker/play-with-docker/tree/master/www) is there the front end code of PWD is being served. As you can see, the k8s playground (http://labs.play-with-k8s.com/) has a different set of colors and theme. You can customize that by changing the AssetsDir variable of the `Playground` structure so it uses a different template folder to render the website

**Comment by mateuszdrab** [comment]
Thanks, I will try to update the docs for that. But if I don't manage, we at least got this issue as a reference for future users.

**Comment by z3ky** [comment]
In which file should AssetsDir variable set to k8s?
