### ISSUE TITLE
Tag a release (v0.0.2?)

### ISSUE THREAD

**Issue by myitcv** [play-with-docker/play-with-docker#409]
At the time of writing, there is only a single tag (release) of `play-with-docker`:

```
cd $(mktemp -d)
go mod init mod.com
go list -m -versions github.com/play-with-docker/play-with-docker
```

gives:

```
github.com/play-with-docker/play-with-docker v0.0.1
```

Indeed this tag was created as far back as Dec 2016:

https://github.com/play-with-docker/play-with-docker/releases/tag/v0.0.1

This tag does not, therefore, include https://github.com/play-with-docker/play-with-docker/commit/f1183076e553f3b4ffff868e253ec12c5b197812. Hence someone doing `go get github.com/play-with-docker/play-with-docker@latest` (which is the default behaviour) will get the non-module version of this project. 

At the least, therefore, we should tag `v0.0.2` to include https://github.com/play-with-docker/play-with-docker/commit/f1183076e553f3b4ffff868e253ec12c5b197812

**Comment by marcosnils** [comment]
Tag v0.0.2 pushed. 

@myitcv check it out and LMK if anything's missing

**Comment by myitcv** [comment]
All looks good, thanks.
