### ISSUE TITLE
Location LAB

### ISSUE THREAD

**Issue by vinii8817** [play-with-docker/play-with-docker#410]
Hello everyone,
I am looking for software to create docker laboratories, to learn, the company I work for has resources available (Host VMWare) with great capacity, we are doing some HandsOn for the team to learn, but creating VMs is not being efficient, so I found this project that comes closest to what I would like to do as a laboratory environment.
I managed to do the Deploy but I can only access it as Localhost, is it possible to create a domain (internal) that everyone can access simultaneously, each one with their lab? or can someone show me some other project that can help me with this?

The idea is that everyone has an account in the system, so any free time in daily activities can be used to advance their studies. the fact that everything is work web http helps a lot does not change the company's internal security policies.

Thank you very much for the beautiful work ;-)

**Comment by marcosnils** [comment]
Check https://github.com/play-with-docker/play-with-docker/issues/402
