### ISSUE TITLE
labs.play-with-docker.com can not publish web service like nginx err empty response

### ISSUE THREAD

**Issue by liujian3** [play-with-docker/play-with-docker#413]
Hi
I am not sure github is the right place to ask this question.
Why I can't access the web page I published in the labs.play-with-docker.com using http://ip<hyphen-ip>-<session_jd>-<port>.direct.labs.play-with-docker.com. but it works well last week.
docker run -it -p 80:80 nginx
when I curl inside the playground the responses are ok. But when I click the port link 80, the popup page shows err_empty_response.
I am not sure this is the problem of this project or my environment. but it confused me these days.

**Comment by marcosnils** [comment]
Fixed. Thx for reporting.

**Comment by liujian3** [comment]
Errrr, it‘s happening again. :(
