### ISSUE TITLE
Play-with-K8s environment in need of some attention

### ISSUE THREAD

**Issue by oskapt** [play-with-docker/play-with-docker#423]
There are multiple "nodes" reporting that they are out of disk space, which makes it impossible to start instances. It requires closing the session and creating a new one over and over until an instance will spin up without disk space errors. It's not clear who hosts that site or where to file the issue, so I'm filing it here.

**Comment by marcosnils** [comment]
I must be missing some alarms on disk usage. Let me check that out. Thx for reporting
