### ISSUE TITLE
Cannot start a new session. "Session not found" at labs.play-with-docker.com

### ISSUE THREAD

**Issue by romansegador** [play-with-docker/play-with-docker#426]
Hi,

First, apologies if this is not the right place to add this issue.

When I click on start at https://labs.play-with-docker.com/ it redirects me to the session, but it displays a message "Session not found". 

Page not found after refreshing. 

Thanks!

**Comment by Ejden** [comment]
I have the same problem. Also in https://training.play-with-docker.com/ terminal doesn't work.

**Comment by marcosnils** [comment]
Fixing.. someone funny messed up with the environment.

**Comment by marcosnils** [comment]
Fixed now

**Comment by romansegador** [comment]
@marcosnils Thanks for the quick support and also for providing this useful tool to the community.,
