### ISSUE TITLE
Docker Swarm  volume sharing

### ISSUE THREAD

**Issue by garanews** [play-with-docker/play-with-docker#430]
Hello,
I am trying the labs and need possibility to let containers running on different nodes see same data to process.
Looking around it seems this can be achieved with glusterfs, so I should install it on all nodes and configure it...
Due I would use your labs for test/demo purposes, it would be possible to setup a faster solution? Goal would be a 
/media or a /tmp, or whatever, but common on all nodes for example.

**Comment by marcosnils** [comment]
Yes, u can use sshfs for that https://training.play-with-docker.com/docker-volume-sshfs/
