### ISSUE TITLE
Upgrade the Go SDK to Moby

### ISSUE THREAD

**Issue by ouankou** [play-with-docker/play-with-docker#432]
The Go SDK of Docker currently used in PWD hasn't been updated since 2017. Other than the security concerns, it lacks of many features in the recent Docker releases, such as enabling GPUs in the container.

I'm wondering if the PWD team has any interest to migrate to its successor Moby. We made such changes in our fork FreeCompilerCamp recently. Beside the name of imported modules, only a few APIs need be updated. We don't have a lot of test cases, but it works well on our existing tutorials. So far, no issues are found.

The related commits are https://github.com/freeCompilerCamp/play-with-compiler/commit/bdd5a61af4327ce12cddadd251245c534f6aa64c and https://github.com/freeCompilerCamp/play-with-compiler/commit/dc8d400783520e00907c6891cced6062e88302cf.

If it could also help PWD, I'm happy to apply the same changes to PWD and open a pull request.

**Comment by marcosnils** [comment]
hey @ouankou we're definitely interested! Happy to accept a PR and start discussing there! :)

**Comment by Stavrospanakakis** [comment]
Hey @marcosnils! If you are still interested, I'd be happy to open a PR.

**Comment by marcosnils** [comment]
That'd be great. Give it a shot if you have the time. I can review it afterwards
