### ISSUE TITLE
nodes out of space again

### ISSUE THREAD

**Issue by oskapt** [play-with-docker/play-with-docker#433]
Hi @marcosnils - I'm setting up for a class in a couple hours, and I'm finding nodes that either can't start instances or that die a short while later with errors like:

```
Failed to pull image "rancher/rancher:v2.5.1": rpc error: code = Unknown desc = failed to register layer: write /var/lib/docker/vfs/dir/93bde6ac30fdd4f0f56c847506156c6fc92b03b0642da036e4b92cab6aee04a0/usr/bin/git: no space left on device
```

Can you make a quick pass and run the space recovery job? Thanks.

If you need help managing the environment, I'm happy to assist.

**Comment by marcosnils** [comment]
> I'm setting up for a class in a couple hours, and I'm finding nodes that either can't start instances or that die a short while later with errors like:

I can make some space in the environment now. But take into account that you're not supposed to expect any kind of SLA about PWK or PWD. Sometimes the environment is going to be tight and you just have to wait to use it

**Comment by oskapt** [comment]
understood, and thank you for maintaining it and offering it as a free service.

however, it's frustrating to be using it for 15 minutes and then have it collapse with errors like:
```
Error setting up pivot dir: mkdir /var/lib/docker/vfs/dir/14538ea9869a75a9472e0fff4c57aa3ce764c19e1502dec4de7520a01536cde4/.pivot_root142362186: disk quota exceeded
```

i don't expect an SLA, but it's not unreasonable to expect it to _work_. if PWK accepts new sessions when it can't service them, is that a valuable service or a waste of time? if this is people's opportunity to experience docker and kubernetes, do we want their experience to be one of frustration?

these are rhetorical questions but still worth thinking about. i won't keep going to an ice cream parlor if every time i walk through the door i get hit in the face with a brick.

**Comment by marcosnils** [comment]
> these are rhetorical questions but still worth thinking about. i won't keep going to an ice cream parlor if every time i walk through the door i get hit in the face with a brick.

I agree and unfortunately, disk space started becoming an issue when we launched k8s workloads due to the amount of images and disk space k8s requires just to run. I agree we could do a better job at resource allocation, but unfortunately that's the best we can do for the moment given the contributors and hours we can allocate to the OS project.

**Comment by oskapt** [comment]
that would be great. if we can go through it together, i'll make a video about it for others that want to do the same. pls shoot me an email at adrian@rancher.com to coordinate.
