### ISSUE TITLE
SSH connection refused

### ISSUE THREAD

**Issue by YuriSizuku** [play-with-docker/play-with-docker#438]
I try to use ssh cmd line in the website, to connect pwd in windows git MINGW64, putty and openssh client. All of them returned connection refused.  The information is as bellow: 

ssh -vvv ip172-18-0-34-bu98v8hqckh0009r5ml0@direct.labs.play-with-docker.com
OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: resolving "direct.labs.play-with-docker.com" port 22
debug2: ssh_connect_direct
debug1: Connecting to direct.labs.play-with-docker.com [40.76.55.146] port 22.
debug1: connect to address 40.76.55.146 port 22: Connection refused
ssh: connect to host direct.labs.play-with-docker.com port 22: Connection refused

**Comment by marcosnils** [comment]
Try now plz

**Comment by YuriSizuku** [comment]
> Try now plz

Thank you very much ! I tried again, it works now.
