### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by bryanasdev000** [play-with-docker/play-with-docker#440]
Hi!

I would like to know if there are any development plans for the project or has it reached a stable state?

I found it looking for alternatives to Katacoda and despite having used play with docker a lot in the past, it never occurred to me that it was open source, besides that it seems to me extremely useful, even able to compete with Katacoda itself as an open source solution.

I'm reading the code and playing with my infrastructure, I'm still having some problems (login / authentication, dns and metrics for now, but I'm investigating besides studying the DIND itself) and I would like to know, if the project is still under development, is there anything I can contribute to?

What I noticed is that the documentation would need an update (I managed to create the infrastructure by reading some old issues), besides that, do you have something in mind?

Other things I thought about was login based on LDAP.

**Comment by marcosnils** [comment]
> I would like to know if there are any development plans for the project or has it reached a stable state?

Nope, we're still adding features but a very slow pace. You can see from the commit history that it's still being supported (https://github.com/play-with-docker/play-with-docker/graphs/contributors) even though it's been a while that I haven't worked in any major features due to lack of time and contributors.

> even able to compete with Katacoda itself as an open source solution.
Katacoda tries to compete with PWD  :P 

> and I would like to know, if the project is still under development, is there anything I can contribute to?

There are several issues opened and also users asking for documentation. There's several places where contributions are welcome

> Other things I thought about was login based on LDAP.

Happy to accept PR's. We already have some Oauth login mechanisms and I believe that if there's interesting in adding other ones it'd be a good moment to start thinking about integrating a generic authentication provider that could potentially handle multiple providers like LDAP, Oauth, etc.

**Comment by bryanasdev000** [comment]
> > I would like to know if there are any development plans for the project or has it reached a stable state?
> 
> Nope, we're still adding features but a very slow pace. You can see from the commit history that it's still being supported (https://github.com/play-with-docker/play-with-docker/graphs/contributors) even though it's been a while that I haven't worked in any major features due to lack of time and contributors.
> 
> > even able to compete with Katacoda itself as an open source solution.
> > Katacoda tries to compete with PWD  :P
> 
> > and I would like to know, if the project is still under development, is there anything I can contribute to?
> 
> There are several issues opened and also users asking for documentation. There's several places where contributions are welcome
> 
> > Other things I thought about was login based on LDAP.
> 
> Happy to accept PR's. We already have some Oauth login mechanisms and I believe that if there's interesting in adding other ones it'd be a good moment to start thinking about integrating a generic authentication provider that could potentially handle multiple providers like LDAP, Oauth, etc.

I'm sorry for the delay in responding.

I am happy to know that the project is active, in the short term maybe I will do a PR with infrastructure instructions (a little more robust than the one that exists today in `README.md`).

I believe it would be interesting to disable or remove the old setup described on the wiki.

I will also take a look at what I can contribute with code, I will probably see the LDAP issue because it may be a future need of mine.

**Comment by marcosnils** [comment]
Cool, thx. I'll be around if you come up with any issues.

**Comment by bryanasdev000** [comment]
> Cool, thx. I'll be around if you come up with any issues.

Thanks!
