### ISSUE TITLE
Error 500 pressing 'Start' on labs.play-with-docker.com

### ISSUE THREAD

**Issue by pasqualebasile** [play-with-docker/play-with-docker#445]
I don't know if it is a temporary failure, but I experienced the problem with different browser and machines.

**Comment by Qylwok** [comment]
Same problem here. After loging in, and after pressing the start button, I face this error on FireFox and Brave : https://i.imgur.com/9In6Jir.png

**Comment by marcosnils** [comment]
Fixed
