### ISSUE TITLE
Published labs.play-with-docker.com port mapping returns ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by chris-ault** [play-with-docker/play-with-docker#447]
Port mapping on the live play-with-docker.com demo appears to have broken sometime last night or this morning.  
I'm not sure who manages it as there is no place to report bugs for the published site.

Start new instance..
Execute simple test server: $ `docker run -P -d nginxdemos/hello`

Yields:
The published port link correctly appears next to "Open Port" button but clicking the link says connection refused.

Expected:
Server should be port forwarded and displayed without refusing connection

**Comment by marcosnils** [comment]
Can u try now?

Please close this issue if it's resolved.

**Comment by chris-ault** [comment]
Looks fixed now.

Love the product, thank you.
