### ISSUE TITLE
cannot connect to docker daemon, missing docker group

### ISSUE THREAD

**Issue by gohmc** [play-with-docker/play-with-docker#449]
PWD launched containers continuously failed to connect docker daemon, missing 'docker' group have caused the daemon failed to start.

**Comment by marcosnils** [comment]
Hey @gohmc  can you provide more info on how to reproduce this issue? Is this when starting the service locally?

**Comment by gohmc** [comment]
hi @marcosnils, to reproduce just start a session with any of the template. First thing to notice is the memory and cpu on the page has no data. Try 'docker info' on any instance and server info will fail. Try 'dockerd' command and noticed the missing docker group.

**Comment by marcosnils** [comment]
managed to repro. Will fix tomorrow

**Comment by balasu** [comment]
Hi i am seeing this error  while launching swarm .and docker daemon is not starting. mount: /sys/kernel/security: permission denied.

**Comment by marcosnils** [comment]
Fixed by 7d6e8478eb9f8ab61c9572fb23c0adffe73d6e04.
