### ISSUE TITLE
worker nodes are not joining swarm cluster

### ISSUE THREAD

**Issue by balasu** [play-with-docker/play-with-docker#450]
Hi

worker nodes are not joining automatically when creating swarm cluster frm PWD. have to manually get the worker node added

![image](https://user-images.githubusercontent.com/39425180/103508444-fe105700-4e86-11eb-8494-72c8d478814c.png)

**Comment by marcosnils** [comment]
:scream: just noticed this bug has always exited since @mikesir87 ~2y ago :sweat_smile:  https://github.com/play-with-docker/play-with-docker/blob/9b82e0bb7ac9fa741a42e6bb6c24a93bd9252d97/www/assets/app.js#L684

**Comment by mikesir87** [comment]
Oops! I'm surprised it took this long 🤦  I do remember seeing that flag, but thought "if it's not a manger, it has to be a worker, right?" 😆
