### ISSUE TITLE
Access ssh or open ports don’t work

### ISSUE THREAD

**Issue by t3easy** [play-with-docker/play-with-docker#453]
If I try to access the host via ssh like described this only times out. If I try to open an exposed port like port 80 the browser loads endless. This worked some days ago with the same test stack.

**Comment by t3easy** [comment]
Maybe the same problem as in #447 again.

**Comment by marcosnils** [comment]
Yep, seems like it. Should be fixed now.

**Comment by t3easy** [comment]
Thx!
