### ISSUE TITLE
Version in "docker-compose.yml" is not supported

### ISSUE THREAD

**Issue by arikanorh** [play-with-docker/play-with-docker#454]
I have a standart docker-compose file with 3 services and version: "3.9" but it terminal gives the error

![image](https://user-images.githubusercontent.com/17791032/109766591-6cfbf900-7c07-11eb-8f74-6d35bf1daec6.png)

**Comment by marcosnils** [comment]
Remove the `version` from the compose file?

**Comment by arikanorh** [comment]
Then the problem changes into something else

![image](https://user-images.githubusercontent.com/17791032/109857816-24c2f200-7c6c-11eb-8e35-8c4493ed3b1f.png)

**Comment by marcosnils** [comment]
Seems like we're using an older version of compose. If you use `version: '3.8'` it should work
