### ISSUE TITLE
Impossible to pull new images : "no space left on device"

### ISSUE THREAD

**Issue by remiconnesson** [play-with-docker/play-with-docker#456]
On the official live preview there is an issue that started this afternoon?

We are unable to pull new images : write /var/lib/docker/tmp/GetImageBlob727549809: no space left on device

**Comment by remiconnesson** [comment]
For example impossible to pull **jupyter/scipy-notebook** or **python:latest**

**Comment by marcosnils** [comment]
This is intended. PWD playground is designed to run lightweight images to showcase different use-cases for Docker. Pulling really big images or writing large files to the instance disk is discouraged and has a limit.
