### ISSUE TITLE
NoScript not considered

### ISSUE THREAD

**Issue by Jonta** [play-with-docker/play-with-docker#458]
- Firefox with NoScript - https://addons.mozilla.org/en-GB/firefox/addon/noscript/
- Go to site - https://labs.play-with-docker.com
- Stuff like the [Start]-button doesn't seem to work
- Start enabling domains, one after the other, refreshing inbetween
- Popup appears, domain docker.com
- It's blank
- Popup is of the type that doesn't have the NoScript widget in it, so I can't enable it
- Therefore have to copypaste the URL and open it in a new tab

**Comment by marcosnils** [comment]
Hi, firefox with noscript is not supported. We're happy to accept contributions though.

**Comment by Jonta** [comment]
@marcosnils How about a <noscript>-tag, listing the domains that have to be enabled? =)

**Comment by AriESQ** [comment]
@Jonta That screen might not appear if you are already logged into your docker.com account. When you get a popup window that NoScript is blocking, and there is no address bar/NoScript Widget, you can right-click the page and access NoScript options from the context menu.

However, this has nothing to do this with project, so please close this issue.

**Comment by Jonta** [comment]
Only now do I notice that GitHub doesn't render my previous message the way I wanted

> How about a `<noscript>`-tag, listing the domains that have to be enabled? =)

I don't know whether @AriESQ would've written something else, if I'd gotten that to render properly the first time. =)
