### ISSUE TITLE
Live version not creating instance

### ISSUE THREAD

**Issue by hotkebab99** [play-with-docker/play-with-docker#464]
The live version doesn't start new instances.

When clicking on "+ ADD NEW INSTANCE", "CREATING..." is displayed but nothing happens.

The HTTP POST request on https://labs.play-with-docker.com/sessions/c24mmbvqf8u000dpjtqg/instances stays in pending state.

Any problem ?

**Comment by marcosnils** [comment]
Should be fixed now

**Comment by hotkebab99** [comment]
> Should be fixed now

Nice. Thanks a lot !
