### ISSUE TITLE
Live version not working well

### ISSUE THREAD

**Issue by hotkebab99** [play-with-docker/play-with-docker#471]
The live version seems very slow.

Got the message : "We are really sorry but we are out of capacity and cannot create your session at the moment. Please try again later."

When it works, i can't start containers because there is no more disk space...

Any problem ? Thanks a lot !

**Comment by hotkebab99** [comment]
When pulling images (mysql), got this message :
- No space left on device

**Comment by marcosnils** [comment]
Hi, which URL is this? Play-with-docker or Play-with-k8s?

**Comment by hotkebab99** [comment]
Play-with-docker
It seems better now but quite slow
