### ISSUE TITLE
SSH process for connecting to locally running PWD on a Macbook

### ISSUE THREAD

**Issue by bbarman4u** [play-with-docker/play-with-docker#472]
Hi Every One,

I looked through different open and closed issues, and while looks like all of them point to either SSH issues with the hosted PWD or with Self Hosted PWD in AWS etc. 

In my case I am running PWD locally on my mac using Docker Desktop for Mac. While all of the features of PWD works fine, but I am confused about how to ssh to one of the running docker hosts from my local machine. The generated IP address for the SSH are not resolvable on my local machine from the terminal. 

Is there a step that I am missing to be able to connect to the running hosts ? any help of pointer is appreciated.

Example that is not working:-

```
ssh ip10-0-1-6-c32d25daggtgjp9c6hsg@direct.localhost
sh: Could not resolve hostname direct.localhost: nodename nor servname provided, or not known
```

**Comment by marcosnils** [comment]
hey @bbarman4u. I think this is a mac specific thing. 

In linux, using systemd-resolve, all *.localhost domains resolve to 127.0.0.1. So, in you case you'd have to add `direct.localhost` to your /etc/resolve.conf for the SSH thing to work. Same thing will happen if you want to access any exposed services in the container as PWD will generate a *.direct.localhost hostname for you to access.

**Comment by bbarman4u** [comment]
@marcosnils Thanks for the hint. Unfortunately the /etc/resolve.conf apparently has no effect in MacOS. Anyways I was able to resolve the DNS issue using dnsmasq but the SSH connection gets refused. Any idea what could be still wrong ? 
Appreciate any guidance.

```
ssh ip10-0-3-4-c32gd7np3hegju4q3tn0@direct.localhost
ssh: connect to host direct.localhost port 22: Connection refused
```

**Comment by bbarman4u** [comment]
Ok Never Mind @marcosnils , after going through the docker compose file, realized the SSH port has been mapped to port 8022. It is very confusing of course since through out the issues over the years and between the main site looks like the SSH forward port # has bounced between 1022, 22 and 8022.

So as such following works -

`ssh -p 8022 ip10-0-3-4-c32gd7np3hegju4q3tn0@direct.localhost`
