### ISSUE TITLE
Published Port not accessible

### ISSUE THREAD

**Issue by yandok** [play-with-docker/play-with-docker#475]
Hi! 

I'm running the command `docker run -d -p 8083:80 docker/getting-started:pwd` in a docker playground instance.

The port pops up in the "open ports"-section,

![grafik](https://user-images.githubusercontent.com/59644731/122723930-c437df00-d273-11eb-9657-11b575534ac2.png)

but seems to be not accessible (connection refused).

2 days ago it worked. 

Regards Klaus

**Comment by marcosnils** [comment]
Should be fixed now

**Comment by yandok** [comment]
Thanks!
