### ISSUE TITLE
DOCKER_HOST="tcp://node_ip:2375" docker ps does not work

### ISSUE THREAD

**Issue by Yavdhesh** [play-with-docker/play-with-docker#476]
When I try above command. It asks me to check if docker daemon is running on the node.

**Comment by geekyouth** [comment]
Because this instance does not expose the public network ip 😢😢😢

**Comment by Yavdhesh** [comment]
okay, so there is not way we can change docker context from one node to another?

**Comment by marcosnils** [comment]
can you provide more info about what you're trying to do please? 

Are you running that command in your local machine and trying to connect to the play-with-docker docker daemon?

**Comment by Yavdhesh** [comment]
I created three nodes swarm. So I was trying to tcp other nodes from master in order to run docker ps command on them.

**Comment by marcosnils** [comment]
what are you using as `node_ip`? You need to use the `192.168.0.x` ip that you see on the left bar. Just tried it and it works ok.

**Comment by Yavdhesh** [comment]
Yes, I used this IP as well, but that did not work for me.
Apologies for the late reply.

**Comment by Yavdhesh** [comment]
Now, it is working for me. I don't know why, but at that point of time it was not working.
