### ISSUE TITLE
Take my money?

### ISSUE THREAD

**Issue by JackofSpades707** [play-with-docker/play-with-docker#482]
I'd love to donate to this to help cover expenses for running this.

**Comment by marcosnils** [comment]
hey Jack! thx for reaching out. 

Fortunately, for now, Docker is actually sponsoring for the infra costs to keep this running. If you want to contribute somehow, ideas, PR's and any kind of feedback is always welcome. Hope you like the project and to see you around this small crew of maintainers / contributors!
