### ISSUE TITLE
Unable to close Session Stack Builder window

### ISSUE THREAD

**Issue by ufukeskici** [play-with-docker/play-with-docker#484]
When I open the docker link, session starts but I'm unable to close Session Stack Builder window. 
What can be the problem? 
<img width="683" alt="docker_problem" src="https://user-images.githubusercontent.com/17970139/128643761-82388efe-3bf4-4e48-a8e8-cac34d66e7aa.PNG">

**Comment by marcosnils** [comment]
This has been fixed
