### ISSUE TITLE
Published ports refusing to connect on play-with-docker.com

### ISSUE THREAD

**Issue by MagicShoebox** [play-with-docker/play-with-docker#488]
When running a container that publishes a port, the provided URL to browse the port refuses to connect.

For example:
Run `docker run --rm -p 8080:80 nginx`
A link appears to view port 8080, of the form `http://ipxxx-xxx-xxx-xxx-xxxxxxxxxxxxxxxxxx-8080.direct.labs.play-with-docker.com/`.
The link refuses to connect.

This seems related or identical to the following issues:
#447 
#453 
#475

**Comment by grstein** [comment]
I'm having the same problem.

**Comment by marcosnils** [comment]
Can u try again? Should be fixed.
