### ISSUE TITLE
docker-compose not working

### ISSUE THREAD

**Issue by grstein** [play-with-docker/play-with-docker#489]
When `docker-compose up` I get the following error:

```
[node1] (local) root@192.168.0.28 ~
$ docker-compose 
Error relocating /usr/lib/libpython3.8.so.1.0: sched_setaffinity: symbol not found
```

Is docker-compose compatible with alpine?

**Comment by ScorpioBroker** [comment]
Hi can confirm
@grstein quick fix for me was to upgrade musl (apk upgrade musl)at first than it works again.

**Comment by marcosnils** [comment]
Just checked and it doesn't seem to be happening in all PWD sessions. I'll try to take a look if I have some time.

**Comment by grstein** [comment]
Yes, I tried to upgrade musl, but then I get a "out of space" message. In fact, the error I received from Python when try "docker-compose" `symbol not found` seems to be related to not have space in the node.

**Comment by ScorpioBroker** [comment]
@grstein yeah i had that too initially. but when i do it as the very first action after the instance creation it does successfully upgrade musl.

**Comment by grstein** [comment]
I'll try next time.

**Comment by marcosnils** [comment]
Fixed! it was a problem with the host where those PWD sessions were running.
