### ISSUE TITLE
how can i get external web address of the app

### ISSUE THREAD

**Issue by vyapaari** [play-with-docker/play-with-docker#493]
As per the FAQ
How can I connect to a published port from the outside world?

If you need to access your services from outside, use the following 
```
URL pattern http://ip<hyphen-ip>-<session_jd>-<port>.direct.labs.play-with-docker.com
```
(i.e: http://ip-2-135-3-b8ir6vbg5vr00095iil0-8080.direct.labs.play-with-docker.com).

There is some issue in URL pattern if i can get right pattern...

**Comment by marcosnils** [comment]
@vyapaari if you go to the playground and you do `docker run -d -p 8080:80 nginx` and then click in the blue badge that appears on the screen (see image). You'll get redirected to the public URL to access services.

![image](https://user-images.githubusercontent.com/1578458/132962495-2398670f-57bf-40a4-a312-4bea77342307.png)
