### ISSUE TITLE
No matching host key type found

### ISSUE THREAD

**Issue by kerrsmith** [play-with-docker/play-with-docker#499]
When trying to access an instance using SSH (directly copying the given SSH connection command), the following error appears:

Unable to negotiate with [IP] port 22: no matching host key type found. Their offer: ssh-rsa

According to the following OpenSSH release page the latest version (OpenSSH 8.8) has potentially incompatible changes:

[https://www.openssh.com/txt/release-8.8](https://www.openssh.com/txt/release-8.8)

In order to make a connection to the instance using SSH the following additions to the given connection command will allow access:

HostKeyAlgorithms=+ssh-rsa
PubkeyAcceptedAlgorithms=+ssh-rsa

Add both these options as shown below:

ssh -oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa  [connection string as given on instance page]

Example:

ssh -oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa ip172-18-0-55-c17893asvety00071ub56@direct.labs.play-with-docker.com

**Comment by marcosnils** [comment]
:+1: thx for the info
