### ISSUE TITLE
'Play with k8s' website not loading

### ISSUE THREAD

**Issue by jihoon-seo** [play-with-docker/play-with-docker#505]
In https://github.com/kubernetes/website/issues/30888 ,
@ashish211985 said:
> Play with k8s website is not loading after i sign in. Its giving the following error :
This page isn’t workinglabs.play-with-k8s.com is currently unable to handle this request.
HTTP ERROR 500

so I tested, and it's not loading for me too!
https://github.com/kubernetes/website/issues/30888#issuecomment-992275892

right after login with GitHub:
![image](https://user-images.githubusercontent.com/46767780/145786762-210f4c79-9632-4f80-99c4-84e94c27b8db.png)

---

after click the "Start" button:
![image](https://user-images.githubusercontent.com/46767780/145787281-a7177b33-93c9-4a77-862b-c6adfb63b3fc.png)

**Comment by systems1** [comment]
its working for me maybe check again and close it
