### ISSUE TITLE
Session keeps getting destroyed after a couple of minutes

### ISSUE THREAD

**Issue by Zoltanpetrik** [play-with-docker/play-with-docker#507]
I cannot use this service, as my session and instances get automatically destroyed after a couple of minutes of tinkering.

It happened twice in a row, using latest Chrome on Windows 10 (my environment should not matter though).

**Comment by marcosnils** [comment]
what are you running in the environment? We have some checks that detect some not permitted workloads and we could be having some false positives there.

**Comment by Zoltanpetrik** [comment]
@marcosnils I only copy & pasted commands from the steps shown in the terminal:

 - Created two nodes from the web interface
 - Initialized one node as master by running:  `kubeadm init --apiserver-advertise-address $(hostname -i) --pod-network-cidr 10.5.0.0/16`
 - Initialized cluster networking on the worker node by running: `kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml`
   - Got error message: `The connection to the server localhost:8080 was refused - did you specify the right host or port?`

I couldn't get any further that that.

**Comment by marcosnils** [comment]
> * Initialized cluster networking on the worker node by running: `kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml`

You need to run this on the master node as well..  not on the worker node. 

On the worker node you only need to run the `kubeadm join` output that the first command produces. 

Just tested this myself and my session doesn't get terminated

**Comment by marcosnils** [comment]
> It could be elasticsearch is cpu intensive?

yes, that's the reason. 



> @marcosnils Would it be possible to have a banner that warns the users when they exceed the permitted workloads?

Not something that's a priority for the moment. The environment is designed to learn docker and run "basic" examples. Anything resource intensive will automatically terminate the session
