### ISSUE TITLE
101-getting-started page appears to be broken.

### ISSUE THREAD

**Issue by AriESQ** [play-with-docker/play-with-docker#508]
Broken URL:
https://birthday.play-with-docker.com/101-getting-started/

Which is accessible from: 
https://birthday.play-with-docker.com/

My sense is that this is a github pages issue. Because I get the Github Pages 404 error. I'm not sure if Github Pages (Liver version of this project) is within the scope of this repository. I.e. I'm not sure I can submit a PR to fix it.

**Comment by marcosnils** [comment]
hey @AriESQ that website is outdated and the code is not OS unfortunately. Even though it uses PWD as a backend for the tutorials, this project is independent of that site. I'm closing this.
