### ISSUE TITLE
sudo: modprobe: command not found 

### ISSUE THREAD

**Issue by ivishalgandhi** [play-with-docker/play-with-docker#510]
I am trying to set up the play-with-docker locally on m1 mac. I am following the instructions https://github.com/play-with-docker/play-with-docker#development and getting the error as below 

`sudo: modprobe: command not found `

Please guide.

**Comment by marcosnils** [comment]
I don't have a mac so I can't really assist much here. Hopefully some other contributor can jump in.

**Comment by ivishalgandhi** [comment]
@marcosnils  The issue can be closed. There is no modprobe command in Mac OS. I will test `play-with-docker` on `ubuntu` or `alpine`. Thank you.
