### ISSUE TITLE
More CLI screen estate on Live PWD site with collapsible sidebar and top-view

### ISSUE THREAD

**Issue by miteshvohra** [play-with-docker/play-with-docker#512]
I love PWD and keep promoting it to my students who wish to start learning Linux without bothering the installation process to begin with. One of the common feedback is that on a laptop screens smaller than 16", the screen estate to work with CLI is too less. Is there a way to make the sidebar and top view collapsible to get more space to work with the command-line?

**Comment by marcosnils** [comment]
> Is there a way to make the sidebar and top view collapsible to get more space to work with the command-line?

You can maximize your terminal if you press alt + enter in windows/linux or cmd + enter in mac os. 

You can also customize that behavior in the settings section here: 

![image](https://user-images.githubusercontent.com/1578458/156114585-c60d377e-a0b2-4ac3-983c-00bc96ad09fc.png)

![image](https://user-images.githubusercontent.com/1578458/156114602-fca61bf8-2b46-4e13-bc7c-dbf192303210.png)



Hopefull that works!
