### ISSUE TITLE
kubeadm join fails as the docker version is 20 istead of 19.

### ISSUE THREAD

**Issue by hasibulbhaai** [play-with-docker/play-with-docker#514]
kubeadm join --token 4f924f.14eb7618a20d2ece 192.168.0.8:6443 --discovery-token-ca-cert-hash  sha256:a5c25aa4573e06a0c11b11df23c8f85c95bae36cbb07d5e7879d9341a3ec67b3 the command fails with error :

**[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 20.10.1. Latest validated version: 19.03**

**Comment by RockSolidScripts** [comment]
Same here. Can't able to create cluster.

**Comment by marcosnils** [comment]
can you add more information about where and how your're getting this error please? 

I can't seem to be able to reproduce: 

![Uploading image.png…]()

**Comment by RockSolidScripts** [comment]
After setting up control plane (Ref Image 1) we can't add other nodes to cluster (Ref Image 2)

Image 1
![image](https://user-images.githubusercontent.com/97788209/180741037-899b8b10-c158-41e9-ade9-38b1fa2517c4.png)

Image 2
![image](https://user-images.githubusercontent.com/97788209/180741439-a5b423a4-cd6f-4798-a941-f0dea6459c46.png)

**Comment by marcosnils** [comment]
@RockSolidScripts what happens after `image2`? It just gets stuck there? 

Seems to work fine here: 

![image](https://user-images.githubusercontent.com/1578458/180860547-c29752d4-8822-44f2-b4b7-1457685f2ab9.png)

**Comment by RockSolidScripts** [comment]
No. Returns to console failing with below error
![image](https://user-images.githubusercontent.com/97788209/180861620-4234fe90-99f7-4437-9cd8-8e4dd58acbd9.png)

**Comment by marcosnils** [comment]
are you running the `kubectl join` command in `node1`? 

To add another node you need to create a new node with the "Create instance" button and paste the command there, not on the same node where you ran the `kubeadm init`

**Comment by RockSolidScripts** [comment]
Nope.. In my case i ran kubeadm init on node2 and kubeadm join in node2

**Comment by RockSolidScripts** [comment]
@marcosnils 
The above snap is taken now. But the previous snap was taken yesterday in which "kubeadm init" was ran in node1 and 'kubeadm join" ran in node2

**Comment by marcosnils** [comment]
Weird.. I'll keep testing. I ran the initialization steps multiple times already and I can't seem to be able to reproduce.

**Comment by RockSolidScripts** [comment]
if you wann are-create,

1. Create two instance.
2. Run "kubeadm-init" in node 1
3. Run corresponding "kubeadm join" in node 2

I doubt the port 6443 isn't enabled in the master node. May be it blocks the API request.

**Comment by marcosnils** [comment]
I can't reproduce. 

It works all the time in my case.

**Comment by RockSolidScripts** [comment]
Hi @marcosnils,

It works for me now. Previously i was trying with root user by exporting config but actually it was a normal user which i should use. (Sincere apologies.)

Thanks a lot for you help and support.

**Comment by marcosnils** [comment]
:+1: glad it works now.
