### ISSUE TITLE
Delayed connection to opened ports on self hosted pwd

### ISSUE THREAD

**Issue by z3ky** [play-with-docker/play-with-docker#517]
I run two simple nginx server in a docker instance and open port 80 for both. 

The connection to nginx A works and l2 shows "Proxying http connection to..." in its logs.
When I try to connect nginx B, I get the content of the website from nginx A and l2 doesn't show any new logs.

When I refresh the site of nginx B after about a minute, I get the correct contents and l2 shows the connection. Then I have to wait again to get a new connection. No matter which nginx website I try to reload.

Even multiple reloads of one nginx only show one connection in l2. Then I have to wait again to get a new connection.

Does l2 have any kind of cache or time constraints for consecutive connections?

**Comment by marcosnils** [comment]
@z3ky forgot to ask. Can you please provide a bit more information about the environment you're using in PWD? Are you performing this test in your local machine? Which environment (OS, version, etc) are you working with

**Comment by ericwagner1** [comment]
I tested on ubuntu 20.04 and macOs.
On ubuntu, I changed the host in config.go to the server's DNS. I also tried to wget the opened port URLs from within instances. Same issues. Only the first call returns the correct data and a l2 log. The wget in the second instance returns the data from the other one and no l2 log. After about a minute or maybe less, I get connection to l2 again.

On macOs, I didn't changed any file. Here, the connection to direct.localhost only works in Chrome browser, but with the same issue.

To reproduce:
- docker-compose up
- create 2 instances
- instance 1
  - mkdir data && echo test_1 > data/index.html
  - docker run --name some-nginx -p 8080:80 -v /root/data:/usr/share/nginx/html:ro -d nginx
  - open port 8080
- instance 2
  - mkdir data && echo test_2 > data/index.html
  - docker run --name some-nginx -p 8090:80 -v /root/data:/usr/share/nginx/html:ro -d nginx
  - open port 8090

**Comment by marcosnils** [comment]
Are you connecting to the l2 directly or through haproxy? 

I'm testing this locally and I can't reproduce. Here are the steps I'm following: 

1 - docker-compose up -d
2 - Create  instance 1 and run `docker run -d -p 80:80 nginx`
3 - Create  instance 2 and run `docker run -d -p 80:80 nginx`

4 - Test with `curl ip<local_ip>-<session_id>.direct.localhost` on both instances and not getting any connection issues.

**Comment by ericwagner1** [comment]
Let the servers show different contents. The curl the first, then the second and the the first again.

**Comment by marcosnils** [comment]
Can you try adding `option http-server-close` in the `haproxy.cfg` file under the `defaults` section and try again?

**Comment by ericwagner1** [comment]
option http-server-close fixes the issue. now, all requests go through haproxy to l2.
