### ISSUE TITLE
No space left on device when trying to run the docker getting-started app

### ISSUE THREAD

**Issue by KevinKoetz** [play-with-docker/play-with-docker#518]
Following the official docker getting started tutorial it is suggested to try the created container in play-with-docker
Unfortunately the download fails with no space left on device 

![image](https://user-images.githubusercontent.com/8590427/162259891-c0dbca30-e0b8-4bf3-a063-6391f8694427.png)

**Comment by marcosnils** [comment]
can you try again? it should be good now

**Comment by KevinKoetz** [comment]
Working now, thank you very much.
