### ISSUE TITLE
Port exposed on PWD doesn't work

### ISSUE THREAD

**Issue by tanvp112** [play-with-docker/play-with-docker#520]
Hi, I start a session with 1 instance and run `docker run -it -p 8080:80 --rm nginx:alpine`, local connect with `curl localhost:8080` and get a response as expected. But the request timeout when I click on the `8080` link next to the "OPEN PORT" button.

This normally work without a glitch, what's missing here?

Thanks!

**Comment by marcosnils** [comment]
:wave: should work now
