### ISSUE TITLE
Published ports refused to connect

### ISSUE THREAD

**Issue by fizdiq** [play-with-docker/play-with-docker#525]
Hi I would like to report an issue during running the `docker run -dp 3000:3000 YOUR-USER-NAME/getting-started` command, it produces a correct port, but it refused to connect.
![image](https://user-images.githubusercontent.com/102731529/170196554-37a06472-1f7b-432e-8785-21c23a713c96.png)

![image](https://user-images.githubusercontent.com/102731529/170196951-cbd40ac9-f539-40ad-ad76-956c7eda07fc.png)

Thank you!

**Comment by marcosnils** [comment]
should be fixed now
