### ISSUE TITLE
Can't dismiss the modal for Session stack builder 

### ISSUE THREAD

**Issue by andrealeo83** [play-with-docker/play-with-docker#528]
Often clicking on the close button of the modal does not work.
![image](https://user-images.githubusercontent.com/9378770/172197045-c3e00d0b-b39d-4507-b054-4c7bf4c51757.png)

**Comment by marcosnils** [comment]
Does pressing ESC closes it?

**Comment by marcosnils** [comment]
gotcha.. the button doesn't work indeed. I'll try allocating some time to fix it. 

Contributions are welcome if you feel like taking a shot.

**Comment by andrealeo83** [comment]
This feature is very important for us.
We would like to use Play With Docker for our product [Tiledesk](https://tiledesk.com) to give our users the ability to run Tiledesk with a single click on Docker Compose with PlayWithDocker

We already created a guide here: https://github.com/Tiledesk/tiledesk-deployment/tree/master/docker-compose#try-online-with-play-with-docker but we don't advertise it too much because there is this error in closing the window.
Instead we would like to put the Try with PWD button directly on the tiledesk.com home page

**Comment by marcosnils** [comment]
If you have urgency for the fix, feel free to open a PR and I can merge it relatively fast. I work on this project in my spare time so I can't make any commitments about when this will be fixed.

**Comment by notzheng** [comment]
> If you have urgency for the fix, feel free to open a PR and I can merge it relatively fast. I work on this project in my spare time so I can't make any commitments about when this will be fixed.

Hi, I had the same problem and I tried to fix it in #546 .
