### ISSUE TITLE
Can’t run “apt update” in Ubuntu 22.04!

### ISSUE THREAD

**Issue by James1freedictionary** [play-with-docker/play-with-docker#531]
the repository 'http://archive.ubuntu.com/ubuntu jammy-backports inrelease' is not signed.

**Comment by marcosnils** [comment]
??? how is this related ti PWD? We don't have an `apt update` instructions in our repo?

**Comment by jassouline** [comment]
Hi, it's because of the Docker version, it's fixed since docker 20.10.9

**Comment by marcosnils** [comment]
fixed. Bumped docker version to latest
