### ISSUE TITLE
Editor button never works

### ISSUE THREAD

**Issue by GBKumbhar** [play-with-docker/play-with-docker#538]
Hi,
could anyone pls let me know the use of editor button on top.
I hope it's for uploading a file to VM or opening file from VM, but it never opened for me!

pls let me know if I m missing something here and need to do some settings/config.

Thanks & Regards

**Comment by marcosnils** [comment]
You can upload files to the VM by drag & dropping them in the terminal from
your file explorer. The editor is only to edit files already existing in
the VM

sent from mobile

Em sex, 15 de jul de 2022 12:40, Ganesh ***@***.***> escreveu:

**Comment by GBKumbhar** [comment]
awsm... got it now, Thanks!

what about copy issue... any trick to copy smoothly, apart from inspect and see :-D

**Comment by marcosnils** [comment]
> e.g. I need to copy key from ssh, it's very difficult. I also can't copy it from web console, just surprised to see that such a basic feature isn't there! any particular reason for that!?

you can copy, just press ctrl + insert. It has been discussed before, check in other issues
