### ISSUE TITLE
Try in PWD not working

### ISSUE THREAD

**Issue by ChubaOraka** [play-with-docker/play-with-docker#541]
I tried the [Try in PWD button](https://labs.play-with-docker.com/?stack=https://raw.githubusercontent.com/raesene/dockerized-security-tools/master/dradis/docker-compose.yml) from [Raesene's blog](https://raesene.github.io/blog/2018/10/21/Try-With-PWD/). It doesn't seem to work.

**Comment by marcosnils** [comment]
This shouldn't be opened here since we don't maintain Raesene's example.

**Comment by ChubaOraka** [comment]
I think the problem is the Try in PWD functionality. I tried other Try in PWD buttons and got the same result.

**Comment by ChubaOraka** [comment]
Raesene's example is just an example, I got the same result when I tried other Try in PWD buttons. If I remember correctly, the application would be launched immediately after login; now I have to click the start button to launch it. That's okay, might be that way now for security reasons. However, the link for the exposed application does not appear.

**Comment by marcosnils** [comment]
> However, the link for the exposed application does not appear.

sometimes this happens. You need to use the "Open port" option. 


> If I remember correctly, the application would be launched immediately after login; now I have to click the start button to launch it.

This is not the case. You always need to press "Start" to launch the env?

What's exactly not working in PWD? I don't have time to test Raesene's  example
