### ISSUE TITLE
Port exposed on PWD doesn't work

### ISSUE THREAD

**Issue by tisage** [play-with-docker/play-with-docker#544]
Hello,

I'm using Docker Playground to test my container but it seems that the published port number is blocked.

For example, when I deploy a simple nginx web app.
```docker run --name web -p 8080:80 nginx```

The published port 8080 has been blocked. See the screenshot below.

[![image](https://user-images.githubusercontent.com/7063641/180882124-8a733373-ce65-486b-a823-a19f333617a5.png)](url)

I also tried to switch to other port number, such as 8081, 8082, or 8001, 8002. It is still not working. 

I would appreciate that if you can tell me what should I do. Thank you!

**Comment by marcosnils** [comment]
Can you try now please? Just found some improvements I could make

**Comment by tisage** [comment]
It works!  Thank you!

**Comment by vijaykumarmanthena** [comment]
Hello I am having same issue how to solve it
