### ISSUE TITLE
Playground Exec Endpoint Always Exit with Code 2

### ISSUE THREAD

**Issue by AlperRehaYAZGAN** [play-with-docker/play-with-docker#548]
I have successfully run the application on my laptop. But I could not use **session/{sessionId}/instances/{instanceName}/exec** endpoint correctly. How can I use this endpoint. Yes I know this question is application specific question but my goal is return true or false with status code like below code:  
[Like Katakoda Validation](https://www.katacoda.com/scenario-examples/scenarios/verified-steps). 

This code could be in test.sh file or could run directly.
```
[ -d /home/this-file-should-exist/file.txt ] && exit 0
```

![play-with-docker](https://user-images.githubusercontent.com/43668181/188503097-3ceeecfb-f86e-4743-9d61-90b37dfb6e2f.png)

I saw on Err_CODE 2 is Misuse of Shell Built-in. [HERE](https://www.baeldung.com/linux/status-codes#:~:text=Exit%20code%202%20signifies%20invalid,alias%2C%20echo%2C%20and%20printf.) 

How can i use this endpoint with correct values for this example.

**Comment by marcosnils** [comment]
try with `sh -c "[ -d /tmp/foo ] && exit 0"`

that should work

**Comment by AlperRehaYAZGAN** [comment]
Thanks for your answer @marcosnils but it gives me 126 ERRCODE now :( 
It gives different ERRCODES for different use types and I could not find correct one. 

If I use this `sh -c "[ -d /tmp/foo ] && exit 0"` code like one string it gives me ERRCODE: 126 
![one-line](https://user-images.githubusercontent.com/43668181/188504765-7230ada0-f88b-48c9-a503-a55e54187e3a.png)

If I use like 1- `sh` 2- `-c "[ -d /tmp/foo ] && exit 0"` ERRCODE:2 
![two-line](https://user-images.githubusercontent.com/43668181/188504890-6301b190-4906-4b55-8e0c-73b9d9631972.png)

If I use as 1- `sh` 2- `-c` 3- `"[ -d /tmp/foo ] && exit 0"` ERRCODE:127
![three-line](https://user-images.githubusercontent.com/43668181/188505068-fd21543e-9675-4ef3-805a-9a94677e8908.png)

It should be error with our exec usage. 😞

**Comment by marcosnils** [comment]
:wave:

try this way:

curl -X POST
http://localhost/sessions/ccb53spq2rsgu3pojesg/instances/ccb53spq_ccb53tpq2rsgu3pojet0/exec
-d '{"command":["sh", "-c", "[ -d /etc ] && exit 0"]}

**Comment by AlperRehaYAZGAN** [comment]
Thank you very much, the code you wrote worked and when I deleted the reverse slash sign previous code, it worked in Postman.
Thanks
