### ISSUE TITLE
Set PWD_HOST_LOCAL_IP environment variable for published URL/ports

### ISSUE THREAD

**Issue by rojenzaman** [play-with-docker/play-with-docker#551]
Currently the URL pattern is is `http://ip<hyphen-ip>-<session_jd>-<port>.direct.labs.play-with-docker.com`

With PWD environment variables like `PWD_HOST_FQDN`, `SESSION_ID`, I can generate the published URL.

**hyphen-ip** (eth1) does not exist as a environment variable therefore I create **hyphen-ip** from eth1 ipv4. This command can generate published URLs for PWD host and host-networked containers: 

```bash
PWD_URL="ip$(ip a s eth1 | egrep -o 'inet [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d' ' -f2 | sed 's/\./\-/g')-${SESSION_ID}-${PWD_PORT}.direct.${PWD_HOST_FQDN}"
```

But I can't get the eth1 address in non host-networked containers. Because the eth1 interface is not attached to these containers.

Can you provide environment variable for eth1 address? Maybe it should be: `PWD_HOST_LOCAL_IP`. Thus, I will be able to generate the URL in any container.

**Comment by marcosnils** [comment]
:wave: you can use the PWD api to get the data that you need. 

i.e if you create an instante and you call the API with `curl https://labs.play-with-docker.com/sessions/$SESSION_ID` it'll return all the info you need to generate the URL's.

**Comment by rojenzaman** [comment]
Thank you!
