### ISSUE TITLE
PWD editor misses some bytes when opening a file

### ISSUE THREAD

**Issue by AndresFelipeVA** [play-with-docker/play-with-docker#553]
Following the Docker 101 tutorial, when the editor is used to make some changes to a file (app.js), it leaks some bytes at the end, so when the file is saved without noticing the issue, it become corrupted

**Comment by marcosnils** [comment]
thx for reporting this.

**Comment by marcosnils** [comment]
I can't seem to repro. Would you mind recording and share a quick video to double check? thx. cc @mikesir87

**Comment by AndresFelipeVA** [comment]
It is more evident if you make some change

**Comment by marcosnils** [comment]
I've tried doing multiple changes and still could not repro

sent from mobile

Em qui., 6 de out. de 2022 13:53, AndresFelipeVA ***@***.***>
escreveu:

**Comment by AndresFelipeVA** [comment]
😐....In the attached image I show you the end of the file (packaje.json)
on the command line and open it in the editor without making any changes,
but you can see a bracket that is missing.
In the video I made some changes and progressively more characters are lost

**Comment by marcosnils** [comment]
> In the attached image I show you the end of the file (packaje.json) on the command line and open it in the editor without making any changes, but you can see a bracket that is missing. In the video I made some changes and progressively more characters are lost

I don't see any attachments?

**Comment by AndresFelipeVA** [comment]
Sorry, it was my mistake, I was replying from the email and the attachments did not load here

https://user-images.githubusercontent.com/57731109/194381803-2f799c67-26aa-4a62-a293-49aac90311b0.mp4
![Capture](https://user-images.githubusercontent.com/57731109/194381947-e61bef1d-15d5-4963-898c-2c9c38afd382.PNG)

**Comment by marcosnils** [comment]
Np. looking forward for the video :pray:

**Comment by AndresFelipeVA** [comment]
https://user-images.githubusercontent.com/57731109/194383572-3db52ae8-9788-4736-a1f7-f33bdb6be9f6.mp4

**Comment by marcosnils** [comment]
I see what you mean now, it also happens to me. I'll take a look :eyes:

**Comment by marcosnils** [comment]
Found and fixed the issue, deploy coming soon. Thx again for reporting

**Comment by marcosnils** [comment]
deployed and fixed upstream :raised_hands:
