### ISSUE TITLE
Start a stack: no space left on device

### ISSUE THREAD

**Issue by t3easy** [play-with-docker/play-with-docker#554]
If I try to start a stack with a link like
`https://labs.play-with-docker.com/?stack=https://raw.githubusercontent.com/t3easy/docker-typo3/11.x/.docker/pwd/stack.yml`
I get an error:
`Error response from daemon: manager stopped: can't initialize raft node: failed to create WAL: no space left on device`

**Comment by agrondemiraj** [comment]
**/dev/sdb**  is running out of space on https://labs.play-with-k8s.com
kubadm init is failing due to this.

**Comment by Cnordbo** [comment]
This is still an issue. Keeps running out of space during init. Which makes the playground unusable. 

It also ends up refusing connection, like its not starting up even if the init command is successfull. Running `systemctl status kubelet` gives me an error saying it cant create temporary file: no space left on device. So cant verify that its running.

**Comment by marcosnils** [comment]
> This is still an issue. Keeps running out of space during init. Which makes the playground unusable.

can you try again please? Just forced some cleanup :pray:
