### ISSUE TITLE
Uploading and downloading files [New feature request]

### ISSUE THREAD

**Issue by Sandeep-source** [play-with-docker/play-with-docker#560]
When we want to try out multiple docker or docker-compose then we have to create them one by one using the editor.
Having an upload option will be convenient and we can also save our work on local computer with a download option.

**Comment by marcosnils** [comment]
> Having an upload option will be convenient and we can also save our work on local computer with a download option.

upload is already possible. You can just drag & drop files or folders into the terminal and they'll get uploaded automatically to the directory your shell is currently located at.

**Comment by Sandeep-source** [comment]
Thanks for the info, 

Please let me know if there is also an option for downloading files.

**Comment by Sandeep-source** [comment]
@marcosnils

**Comment by marcosnils** [comment]
> Please let me know if there is also an option for downloading files.

you can download files through `scp`. Since you can `ssh` to the PWD machine.
