### ISSUE TITLE
Instances not creating

### ISSUE THREAD

**Issue by harish343** [play-with-docker/play-with-docker#562]

**Comment by marcosnils** [comment]
which environment? provide more info

**Comment by harish343** [comment]
https://labs.play-with-k8s.com/

**Comment by harish343** [comment]
I am not able to create instances please fix it

**Comment by marcosnils** [comment]
![image](https://user-images.githubusercontent.com/1578458/209993061-380a7644-6eef-4ace-a4f2-f8e56d994681.png)
works here

**Comment by harish343** [comment]
yes now it is working thanks for attention
