### ISSUE TITLE
storage is full 

### ISSUE THREAD

**Issue by MONSERRAT343** [play-with-docker/play-with-docker#565]
storage is full I am not able to create containers

**Comment by hakcolt** [comment]
So clean the storage...

**Comment by agrondemiraj** [comment]
Host Storage is full ! Trying to launch k8s cluster, no pod is able to run. Host has only 64GB Storage and due to multiple users, it is getting full. Please increase to at least 200GB, storage is the cheapest resource nowadays.

**Comment by marcosnils** [comment]
> Please increase to at least 200GB, storage is the cheapest resource nowadays.

It's no that easy because nodes are currently using ephemeral NVMe disks that come with the VM. If we wanted to increase disks, we'd have to bump the VM which is costly.

Thx for your concerns though, very insightful

**Comment by marcosnils** [comment]
> Isn't there a way to only increase storage for some GBs ?

not now. You'll have to wait until some space is freed and try again later.

**Comment by marcosnils** [comment]
> Hey Marcos,
> 
> Truly appreciate your effort on offering this service to us, however this is not a working environment. If budget is the issue for you to upgrade the service, then add a minimal monthly subscription fee, and people who really need it will deffinitely pay for it.


hey, you're right. What I'll do is to add a check so people can't create more sessions if the storage is full with a message to come back later. Unfortunately, resources are not infinite and adding a payment wall is not within my plans.

**Comment by agrondemiraj** [comment]
That sounds better than current state. For the last session to be able to work correctly, I would suggest capping to 50GB out of 64GB, and perhaps lower the session time, as many might start and keep it idle. I believe 1h is sufficient.

**Comment by marcosnils** [comment]
storage has been increased

**Comment by agrondemiraj** [comment]
Thank you Marcos. One last help, How do you Copy in Shell ?
Pasting is Ctrl+Shift+V, but copying doesn't seem to work with known combinations ?

**Comment by marcosnils** [comment]
Try shift + insert. FWIW this is not a PWK problem. Xterm.js the lib that
we're  using for the terminal handles this.

sent from mobile

Em dom., 29 de jan. de 2023 13:51, agrondemiraj ***@***.***>
escreveu:

**Comment by agrondemiraj** [comment]
So for anyone else struggling, here it is how Copy/Paste seem to work in Xterm.js. Thanks Marco

Windows
Copy: Ctrl + Insert
Paste: Shift + Insert
