### ISSUE TITLE
(Self hosted) "No server is available to handle this request" message when trying to access home page

### ISSUE THREAD

**Issue by thehamdiaz** [play-with-docker/play-with-docker#566]
I am trying to host play-with-docker locally and after following the steps mentioned in [Readme.md ](https://github.com/play-with-docker/play-with-docker#development) I can not access the home page.

# Error message when executing `curl 127.0.0.1:80` :
```console
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```
# Logs:

## PWD:
```console
2023/01/18 15:28:25 Updating playgrounds configuration
2023/01/18 15:28:25 EVENT: Playground New 4a24b940-e23f-54f5-8867-137433240dd7
2023/01/18 15:28:25 Updating playgrounds configuration
2023/01/18 15:28:25 Listening on port 3000
2023/01/18 15:31:44 Error retrieving playground 4671c397-1381-593d-9cb4-94c9ae9706e4. Got: NotFound
2023/01/18 15:31:44 Playground for domain 172.25.0.2:3000 was not found!
[negroni] Started GET /
[negroni] Completed 404 Not Found in 228.355µs
2023/01/18 15:33:25 Updating playgrounds configuration
2023/01/18 15:38:25 Updating playgrounds configuration
[negroni] Started GET /
2023/01/18 15:42:44 Error retrieving playground 4671c397-1381-593d-9cb4-94c9ae9706e4. Got: NotFound
2023/01/18 15:42:44 Playground for domain 172.25.0.2:3000 was not found!
```

## L2:

```console
2023/01/18 15:28:03 Connected to network [play-with-docker_default] with ip []
```

## haproxy:

```console
[NOTICE]   (1) : haproxy version is 2.7.1-3e4af0e
[NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
[WARNING]  (1) : config : missing timeouts for frontend 'http-in'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING]  (1) : config : missing timeouts for backend 'pwd'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING]  (1) : config : missing timeouts for backend 'l2'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[NOTICE]   (1) : New worker (8) forked
[NOTICE]   (1) : Loading success.
[WARNING]  (8) : l2/node2 changed its IP from (none) to 172.25.0.4 by docker_resolver/dns.
[WARNING]  (8) : Server l2/node2 ('l2') is UP/READY (resolves again).
[WARNING]  (8) : Server l2/node2 administratively READY thanks to valid DNS answer.
[WARNING]  (8) : pwd/node1 changed its IP from (none) to 172.25.0.2 by docker_resolver/dns.
[WARNING]  (8) : Server pwd/node1 ('pwd') is UP/READY (resolves again).
[WARNING]  (8) : Server pwd/node1 administratively READY thanks to valid DNS answer.
[WARNING]  (8) : Server l2/node2 is DOWN, reason: Layer4 timeout, check duration: 10000ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[ALERT]    (8) : backend 'l2' has no server available!
[WARNING]  (8) : Server pwd/node1 is DOWN, reason: Layer4 timeout, check duration: 10002ms. 0 active and 0 backup servers left. 1 sessions active, 0 requeued, 0 remaining in queue.
[ALERT]    (8) : backend 'pwd' has no server available!

```

# Steps followed :
$ sudo modprobe xt_ipvs
$ docker swarm init 
$ docker pull franela/dind
$ go mod vendor
$ docker-compose up -d

# System info:
OS: Ubuntu 22.04
Docker version: Docker version 20.10.12
Docker-compose version: docker-compose version 1.29.2
Go version: go version go1.18.1 linux/amd64

Also when i execute `curl <pwd-container-ip-address>:3000` it executes but shows no output 

Can someone help identify the problem?

**Comment by salem017** [comment]
same issue. I think there is a issue on the docker compose.
I try to modify the volume but don t work

**Comment by marcosnils** [comment]
does this happen if you run it locally also?

**Comment by marcosnils** [comment]
I've just tried to run it locally and it works as expected. 

1. Clone the repo
2. run `docker compose up -d` 
3. access `localhost` in the browser and that's it.

**Comment by thehamdiaz** [comment]
I just tried to do the steps all over again and the issue still persists for me. What do you think the problem is?

**Comment by salem017** [comment]
ERROR: for 2a129f33e989_pwd  Cannot create container for service pwd: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: for ac0b4b3df652_l2  Cannot create container for service l2: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: for pwd  Cannot create container for service pwd: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: for l2  Cannot create container for service l2: create .: volume name is too short, names should be at least two alphanumeric characters
even locally on my side

**Comment by salem017** [comment]
I modify the docker compose to put ${PWD}/:/ but dont work either

**Comment by marcosnils** [comment]
I'm not sure, I can't reproduce

**Comment by salem017** [comment]
it is a fresh install in an ubuntu server. if it can help. ALso the full error log:
`~/play-with-docker$ sudo docker-compose  up
WARNING: The PWD variable is not set. Defaulting to a blank string.
Starting haproxy ... 
Creating l2      ... 
Creating pwd     ... error
Creating l2      ... error
Starting haproxy ... done

ERROR: for l2  Cannot create container for service l2: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for pwd  Cannot create container for service pwd: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for l2  Cannot create container for service l2: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.
`

**Comment by thehamdiaz** [comment]
> it is a fresh install in an ubuntu server. if it can help. ALso the full error log: `~/play-with-docker$ sudo docker-compose up WARNING: The PWD variable is not set. Defaulting to a blank string. Starting haproxy ... Creating l2 ... Creating pwd ... error Creating l2 ... error Starting haproxy ... done
> 
> ERROR: for l2 Cannot create container for service l2: create .: volume name is too short, names should be at least two alphanumeric characters
> 
> ERROR: for pwd Cannot create container for service pwd: create .: volume name is too short, names should be at least two alphanumeric characters
> 
> ERROR: for l2 Cannot create container for service l2: create .: volume name is too short, names should be at least two alphanumeric characters ERROR: Encountered errors while bringing up the project. `

I don't think we have the same issue. On my side all three containers build successfully, i just can't access the the home page due to  `503 Service Unavailable` error so it would be best to open a new issue to keep things organized.

**Comment by salem017** [comment]
hum okok I will create an other issue. When I modify my file, I have the same alert. Sorry about your issue. I will delete the discussion
