### ISSUE TITLE
How to get in touch regarding a security concern?

### ISSUE THREAD

**Issue by cokeBeer** [play-with-docker/play-with-docker#577]
Hello 👋

I found a potential security issue in paly-with-docker, how can I get in touch with you in a private way and submit my security report?

Could you add a SECURITY.md file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

**Comment by marcosnils** [comment]
:wave: thx for reporting. You can contact me at marcosnils (at) gmail.com for disclosure. 

I'll add the security policies later this week, thx for mentioning it out!.

**Comment by marcosnils** [comment]
closed since this is addressed already. I'll publish the security advisory in a bit

**Comment by cokeBeer** [comment]
@marcosnils Hi, is it still in progress ?

**Comment by marcosnils** [comment]
Hi! No, the security advisory has been published already https://github.com/play-with-docker/play-with-docker/security/advisories/GHSA-vq59-5x26-h639

**Comment by cokeBeer** [comment]
@marcosnils Hi, the page is 404 for me. Did you add me as collaborator ?

**Comment by marcosnils** [comment]
Just added you.

**Comment by cokeBeer** [comment]
@marcosnils  Could you assign a CVE id in that page? Only maintainers can do this.
