### ISSUE TITLE
:wave:  I think @teaim is referring to the "Add new terminal" that katacoda has on the terminal tab bar at the top (option available by clicking the three dotted lines)

### ISSUE THREAD

**Issue by a13dd1234** [play-with-docker/play-with-docker#586]
:wave:  I think @teaim is referring to the "Add new terminal" that katacoda has on the terminal tab bar at the top (option available by clicking the three dotted lines) 

This is something PWD could do, but we haven't added that feature since we generally use `tmux` to do terminal multiplexing. I do believe this is valuable for users, specially those who doesn't know how to use tmux. It's just that the demand / value out of this feature is quite small today to implement it. 

I'll leave this open in case someone wants to take a shot.

_Originally posted by @marcosnils in https://github.com/play-with-docker/play-with-docker/issues/463#issuecomment-878107594_
            

Sorry, But can you give an example of how to use tmux with (labs.play-with-docker.com) . tmux shortcut like ctrl + B + % to split the terminal does not work. And is there any Cheat Sheet for (labs.play-with-docker.com) one can use? Like change to other node with out using mouse
Thanks for your time

**Comment by marcosnils** [comment]
> Sorry, But can you give an example of how to use tmux with (labs.play-with-docker.com) . tmux shortcut like ctrl + B + % to split the terminal does not work.

![image](https://user-images.githubusercontent.com/1578458/236683740-d2714402-da3e-4a08-804d-ec86b81db821.png)


There's not too much to add here. You need to press ctrl+b and then the `%` key.



> And is there any Cheat Sheet for (labs.play-with-docker.com) one can use? Like change to other node with out using mouse

There's no such cheat sheet. PWD doesn't have any global shortcuts.

Closing this since there's no action items here.
