### ISSUE TITLE
can't able to ssh

### ISSUE THREAD

**Issue by chan18** [play-with-docker/play-with-docker#587]
![image](https://github.com/play-with-docker/play-with-docker/assets/13510817/e04ca997-3352-4fcf-9683-c74276971a78)

**Comment by marcosnils** [comment]
yeah... seem it broke in the last upgrade. I need to investigate what happened :S

**Comment by marcosnils** [comment]
should be fixed. Can you try again and close if it works? thanks!

**Comment by chan18** [comment]
![image](https://github.com/play-with-docker/play-with-docker/assets/13510817/ff11f66c-312d-4425-a831-6abbecf10070)
awesome thanks.

Thank you very much,
