### ISSUE TITLE
Play With Docker Used To Play Nicely In Tor; It Don't Wanna Play No More…

### ISSUE THREAD

**Issue by skepticoitusInteruptus** [play-with-docker/play-with-docker#592]
&hellip;

# Expected Behavior
I can login to and use Play With Docker in the Tor browser (*I'd been able to for years until a few months ago*).

# Actual Behavior
When I click the login button, Tor's attempt to resolve/load the Play With Docker login page goes into a continuous loop. Play With Docker is the ***onliest*** site on which I've ***ever*** encountered this issue.

# Steps To Reproduce
1. Launch the most up-to-date version of Tor
2. Go to https://labs.play-with-docker.com/
3. Click the `Login` - `docker` button

![issue 592 play with docker -10 b](https://github.com/play-with-docker/play-with-docker/assets/97033958/2c1541d3-94c6-40c4-bcee-6ab1328d965b)

----

![issue 592 play with docker -10 d](https://github.com/play-with-docker/play-with-docker/assets/97033958/aaca498b-9199-46f9-b570-4ac90f0bb35a)

----

***Browser***: Tor version 12.5.2 (based on Mozilla Firefox 102.14.0esr) (64-bit)
***OS***: Windows 7

**Comment by marcosnils** [comment]
doesn't seem related to play-with-docker. When you click the `login` button, a popup is displayed redirecting the user to Docker's SSO login page (https://login.docker.com/u/login/identifier?state=hKFo2SBzZjA0WWxGc3RTMG13RHA4bEpvMDVGXzNpaUFRYXhoTaFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIHJ4TTVzazQ3NkdEOUVYcEVSUEQtT01zWUlEbDBfX2oyo2NpZNkgR3hkRjhpSG4zZ3NaOG9NWWdsZ2NnTDV6eUVNWkgzREM). 

that's not something that PWD can do something about.
