### ISSUE TITLE
Got 500 when I try to add the PWD button into my readme

### ISSUE THREAD

**Issue by LinuxSuRen** [play-with-docker/play-with-docker#603]
See also the following content:

[![Try in PWD](https://github.com/play-with-docker/stacks/raw/cff22438cb4195ace27f9b15784bbb497047afa7/assets/images/button.png)](http://play-with-docker.com?stack=https://raw.githubusercontent.com/LinuxSuRen/api-testing/master/docs/manifests/docker-compose.yaml)

```md
[![Try in PWD](https://github.com/play-with-docker/stacks/raw/cff22438cb4195ace27f9b15784bbb497047afa7/assets/images/button.png)](http://play-with-docker.com?stack=https://raw.githubusercontent.com/LinuxSuRen/api-testing/master/docs/manifests/docker-compose.yaml)
```

**Comment by ArjunMenon-bit** [comment]
@LinuxSuRen  Can you give more details on this issue so that we can reproduce this?

**Comment by LinuxSuRen** [comment]
hi @ArjunMenon-bit , I'm not sure if I understand it correctly. I thought I could give an environment with the given compose file which is in the URL above. But I got a 500 error response when I clicked the above button (Try in PWD).

**Comment by LinuxSuRen** [comment]
It works well. Thanks for your help. @Koh42
