### ISSUE TITLE
unable to pull images from docker hub

### ISSUE THREAD

**Issue by DevangCoder** [play-with-docker/play-with-docker#613]
When trying to pull any image, getting the following error
Command: docker pull node
Error: `Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp 54.198.86.24:443: i/o timeout`

**Comment by marcosnils** [comment]
seems to be working fine here
![image](https://github.com/play-with-docker/play-with-docker/assets/1578458/bcca569c-4f91-43c4-bf6c-9cca21808c25)
