### ISSUE TITLE
Port exposed not working

### ISSUE THREAD

**Issue by yatishdang** [play-with-docker/play-with-docker#615]
PWD seems to awesome platform for docker practice.

 I am trying to access port exposed using nginx docker

docker run  -d -p 8080:80 nginx
Below is running container
<img width="1471" alt="image" src="https://github.com/play-with-docker/play-with-docker/assets/4208551/ceb09bcb-7d3a-4d8a-a8ca-94e121ebee26">

But getting below error
<img width="1125" alt="image" src="https://github.com/play-with-docker/play-with-docker/assets/4208551/0a2dcfa2-98a0-4ce4-8e71-01ec8fe2278a">

Sometimes get
<img width="1127" alt="image" src="https://github.com/play-with-docker/play-with-docker/assets/4208551/0c0a5604-4b9a-4096-87ed-bb1d4f2ddabe">

Hope this will be soon resolved and thanks in advance.

**Comment by rimelek** [comment]
I can confirm, it was reported on the Docker forum as well

https://forums.docker.com/t/stuck-on-getting-started-part-4/140350

so I checked and it didn't work for me either.

**Comment by marcosnils** [comment]
hi, this is fixed now!

**Comment by yatishdang** [comment]
> hi, this is fixed now!

Hey Marcosnils, you are superman.
Thanks alot :)
