### ISSUE TITLE
PWD problem with connect from outside

### ISSUE THREAD

**Issue by SiDLYpl** [play-with-docker/play-with-docker#618]
Hi, 

I was trying to connect outside to container but I received - timeout error all time. I tested it on a lot of options and a lot of ports. 
Something is wrong with outside opening -

http://ip172-18-0-54-cojdj70l2o9000aruhig-80.direct.labs.play-with-docker.com/
https://ip172-18-0-54-cojdj70l2o9000aruhig-8081.direct.labs.play-with-docker.com/

![image](https://github.com/play-with-docker/play-with-docker/assets/126084018/a43d5837-afff-4a8a-b173-f9626c7f703e)

**Comment by marcosnils** [comment]
hey! should be fixed now!
