### ISSUE TITLE
I'm doing a CLI tool, but authenticating is being a problem

### ISSUE THREAD

**Issue by d3cryptofc** [play-with-docker/play-with-docker#624]
I would like to ask if you know of any way so I can generate the OAuth URL for the user, he can authenticate himself and I can receive his session cookie.

Currently I am instructing them to open devtools to obtain the token, but this can be a hindrance for beginners and is not practical at all.

It would be an honor to have your support in this project.

Thank you very much!! :)

Repository: https://github.com/d3cryptofc/Doky

**Comment by marcosnils** [comment]
> I would like to ask if you know of any way so I can generate the OAuth URL for the user, he can authenticate himself and I can receive his session cookie.

 sorry it's currently not possible since the intention is that you use PWD from the web mostly. There are also no plans to currently support this use-case
