### ISSUE TITLE
Error 500 on https://labs.play-with-docker.com/

### ISSUE THREAD

**Issue by Minskaya** [play-with-docker/play-with-docker#625]
Hi,

I get an error 500 when trying to go to the https://[labs.play-with-docker.com](https://labs.play-with-docker.com/)/ page.
May the service is down ?

I logged with Github and found a similar issue here : https://github.com/play-with-docker/play-with-docker/issues/621

Thanks,
Mins

**Comment by Minskaya** [comment]
Hi,
I just made a try while login with email and got the same result

**Comment by azigriffin** [comment]
same issue

**Comment by Minskaya** [comment]
The thread of #621 has ended without a solution.
Does this mean that you have not determined what the problem cas or that it is the service that need to be restarted ?
Is there something i can try on my side ?

I have already tried :
- 2 browsers
- normal navigation and navigation in private
- login with Github or with email

Is there something i can check in my docker account ?

Thanks

**Comment by marcosnils** [comment]
should be working now

**Comment by Minskaya** [comment]
I confirm it is working now
Thanks a lot !!!
