### ISSUE TITLE
PWK not exposing port when port-forward

### ISSUE THREAD

**Issue by swapnilraut3** [play-with-docker/play-with-docker#632]
**I think this is recurring issue & requires site admin intervention everytime.** 
Steps

Create cluster
Create pod: kubectl run nginx --image=nginx --port=80
Create proxy listening on 0.0.0.0: kubectl port-forward --address 0.0.0.0 pod/nginx 8888:80
Test access:
e.g.
http://ip172-18-0-114-cseih9gi715g00ba0060-8888.direct.labs.play-with-k8s.com/
Result won't connect

**Comment by swapnilraut3** [comment]
This site can’t be reached
ip172-18-0-114-cseih9gi715g00ba0060-8888.direct.labs.play-with-k8s.com took too long to respond.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
[Running Connectivity Diagnostics](javascript:diagnoseErrors())
ERR_CONNECTION_TIMED_OUT

**Comment by marcosnils** [comment]
should be working now!

:pray:
