### ISSUE TITLE
Create an instance that doesn't function

### ISSUE THREAD

**Issue by MortenHaensch** [play-with-docker/play-with-docker#634]
1)  I logged in on the website https://labs.play-with-docker.com/#
2) Then I started a session (which sometimes failed because of an error message like that there are not enough resources available, and I should try it again later)
3) When a session started, I tried to create an instance... but no instance was created.
I tried to do some from my smartphone.
Are there any restrictions to use your service only from specific devices like desktop computers or notebooks?
Is the offer from your service stopped, or is the offer from your service temporarily stopped?
Could you please check that ?

Thank you very much.

**Comment by marcosnils** [comment]
Can you try again and close this issue it has been fixed?

**Comment by MortenHaensch** [comment]
Thank you very much! Now, it works! @marcosnils
