### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by snyff** [play-with-docker/play-with-docker#636]
Hi team,

I found a security issue and emailed marcosnils (at) gmail.com a few days ago. I just want to make sure you got the email (from louis (at) pentesterlab.com).

**Comment by marcosnils** [comment]
hey Louis, thx for reporting, I'll address that in a sec.

Marcos.

**Comment by snyff** [comment]
Thanks for the quick turnaround. Are you able to raise it as a security issue to ensure people using the project or forking it are aware of the issue.
