### ISSUE TITLE
Error on building container image ( yarn install)

### ISSUE THREAD

**Issue by emakkouche** [play-with-docker/play-with-docker#638]
I am using Play With Docker (PWD) to build a container image with the following Dockerfile

```
FROM node:10-alpine
WORKDIR /app
COPY . .
RUN yarn install --production
CMD ["node", "/app/src/index.js"]
```
When I run the command docker build -t docker-101 ., I encounter the following error:

**An unexpected error occurred: https://registry.yarnpkg.com/body-parser/-/body-parser-1.19.0.tgz: getaddrinfo EAI_AGAIN registry.yarnpkg.com registry.yarnpkg.com:443**

It seems to be a network-related issue. Has anyone faced a similar problem? Are there any suggestions on how to resolve this?

**Comment by gmccauley** [comment]
I'm having this same issue, did you find a solution?

**Comment by emakkouche** [comment]
Not yet. I have tried with npm instead of yarn but it does not works.

**Comment by marcosnils** [comment]
should be fixed now!
