### ISSUE TITLE
apt update doesn’t work on ubuntu and PWD

### ISSUE THREAD

**Issue by xaviblanes** [play-with-docker/play-with-docker#639]
I use Play With Docker frequently and recently discovered that if I run an Ubuntu or Debian container with -it and run it in the console as root (#) an apt update doesn’t work. It tries to load the repositories but it doesn’t work. I’ve changed my internet connection network. I’ve tried Ubuntu 18, 20, 22 or 24 and the same thing in all of them. It doesn’t work. And if you don’t update you can’t install. It used to work. Any idea why this could happen?

![image](https://github.com/user-attachments/assets/338b8c29-7010-48ea-bea1-0ac973be8419)
After 5 minutes I did esc, it doesn’t complete the update and nothing can be installed

**Comment by marcosnils** [comment]
hey @xaviblanes  should be fixed now!
