### ISSUE TITLE
Line breaks are weird for copy/pasting

### ISSUE THREAD

**Issue by gvilarino** [play-with-docker/play-with-docker#66]
When creating a new swarm, I do:

![image](https://cloud.githubusercontent.com/assets/2538465/20902570/718c1cf4-bb16-11e6-88fb-20d601518368.png)

I then select that whole text and then when I paste it in a new instance, I get:

![image](https://cloud.githubusercontent.com/assets/2538465/20902590/86e5233e-bb16-11e6-84d5-8f2aaee2e6cb.png)

It seems as though the line breaks or character encoding isn't entirely happy with the clipboard or something like that.

Running on macOS Sierra + Chrome latest

**Comment by marcosnils** [comment]
@gvilarino got what you say, basically when the newline occurs, if you copy then a `\n` character will be copied which makes it impossible to paste it afterwards

@akalipetis do you know anything about this?

**Comment by gvilarino** [comment]
Yeah, that's spot on

**Comment by akalipetis** [comment]
I'll take a look @marcosnils @gvilarino - I believe this has been fixed in a recent version of Xterm.js.

**Comment by marcosnils** [comment]
@akalipetis thx. I'll try to update locally and let you know. Is it fixed in the core or though a plugin?

**Comment by akalipetis** [comment]
I'll need to take a look @marcosnils, not sure about this sorry.

**Comment by marcosnils** [comment]
@akalipetis tried updating but nothing happened :(

**Comment by akalipetis** [comment]
Ok, I've lost track of this one. This is currently a bug in Xterm.js - the wrapped lines get a newline character at the end.

The best solution would be to give a minimum width to the Terminal maybe for now?

I have opened an Xterm.js issue too for tracking: sourcelair/xterm.js#443

**Comment by marcosnils** [comment]
@akalipetis thx for following up. I guess we can wait until this gets fixed in Xterm.js.

**Comment by marcosnils** [comment]
This has been finally fixed by the xterm.js team. Thx @tyriar for the hard work!
